/*
This file was automatically generated by the EntityCreator engine on Tue May 16 16:18:49 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the A11T0SCC database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(name = "A11T0SCC", schema = "CREQCMR")
public class A11t0scc extends BaseEntity<A11t0sccPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private A11t0sccPK id;

  @Override
  public A11t0sccPK getId() {
    return id;
  }

  @Override
  public void setId(A11t0sccPK id) {
    this.id = id;
  }

  @Column(name = "I_TABLE")
  private String iTable;

  @Column(name = "F_NUMRC_DUP")
  private String fNumrcDup;

  @Column(name = "F_LAST_NUMRC_DUP")
  private String fLastNumrcDup;

  @Column(name = "F_ALPHA_DUP")
  private String fAlphaDup;

  @Column(name = "F_LAST_ALPHA_DUP")
  private String fLastAlphaDup;

  @Column(name = "F_MULTPL_ZIPS")
  private String fMultplZips;

  @Column(name = "F_EXTRA_1")
  private String fExtra1;

  @Column(name = "F_EXTRA_2")
  private String fExtra2;

  @Column(name = "F_OTSD_CITY_LIMIT")
  private String fOtsdCityLimit;

  @Column(name = "D_SCC_ACTIV")
  private float dSccActive;

  @Column(name = "C_ST")
  private float cSt;

  @Column(name = "C_CNTY")
  private float cCnty;

  @Column(name = "C_CITY")
  private float cCity;

  public String getITable() {
    return iTable;
  }

  public void setiITable(String iTable) {
    this.iTable = iTable;
  }

  public String getfNumrcDup() {
    return fNumrcDup;
  }

  public void setfNumrcDup(String fNumrcDup) {
    this.fNumrcDup = fNumrcDup;
  }

  public String getfLastNumrcDup() {
    return fLastNumrcDup;
  }

  public void setfLastNumrcDup(String fLastNumrcDup) {
    this.fLastNumrcDup = fLastNumrcDup;
  }

  public String getfAlphaDup() {
    return fAlphaDup;
  }

  public void setfAlphaDup(String fAlphaDup) {
    this.fAlphaDup = fAlphaDup;
  }

  public String getfLastAlphaDup() {
    return fLastAlphaDup;
  }

  public void setfLastAlphaDup(String fLastAlphaDup) {
    this.fLastAlphaDup = fLastAlphaDup;
  }

  public String getfMultplZips() {
    return fMultplZips;
  }

  public void setfMultplZips(String fMultplZips) {
    this.fMultplZips = fMultplZips;
  }

  public String getfExtra1() {
    return fExtra1;
  }

  public void setfExtra1(String fExtra1) {
    this.fExtra1 = fExtra1;
  }

  public String getfExtra2() {
    return fExtra2;
  }

  public void setfExtra2(String fExtra2) {
    this.fExtra2 = fExtra2;
  }

  public String getfOtsdCityLimit() {
    return fOtsdCityLimit;
  }

  public void setfOtsdCityLimit(String fOtsdCityLimit) {
    this.fOtsdCityLimit = fOtsdCityLimit;
  }

  public float getdSccActive() {
    return dSccActive;
  }

  public void setdSccActive(float dSccActive) {
    this.dSccActive = dSccActive;
  }

  public float getcSt() {
    return cSt;
  }

  public void setcSt(float cSt) {
    this.cSt = cSt;
  }

  public float getcCnty() {
    return cCnty;
  }

  public void setcCnty(float cCnty) {
    this.cCnty = cCnty;
  }

  public float getcCity() {
    return cCity;
  }

  public void setcCity(float cCity) {
    this.cCity = cCity;
  }

}