/*
This file was automatically generated by the EntityCreator engine on Tue Feb 02 17:16:30 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang3.StringUtils;

/**
 * The primary key class for the ADDLCTRYDATA database table.
 * 
 * @author PriyRanjan
 */
@Embeddable
public class AddlctrydataPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  private String mandt;

  private String kunnr;

  @Column(name = "FIELD_NAME")
  private String fieldName;

  public String getMandt(){
    return this.mandt;
  }

  public void setMandt(String mandt){
    this.mandt = mandt;
  }


  public String getKunnr(){
    return this.kunnr;
  }

  public void setKunnr(String kunnr){
    this.kunnr = kunnr;
  }


  public String getFieldName(){
    return this.fieldName;
  }

  public void setFieldName(String fieldName){
    this.fieldName = fieldName;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof AddlctrydataPK)) {
      return false;
    }
    AddlctrydataPK o = (AddlctrydataPK) other;
    return this.mandt.equals(o.mandt) && this.kunnr.equals(o.kunnr) && this.fieldName.equals(o.fieldName);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.mandt != null ? this.mandt.hashCode() : 0);
    hash = hash * prime + (this.kunnr != null ? this.kunnr.hashCode() : 0);
    hash = hash * prime + (this.fieldName != null ? this.fieldName.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.mandt) && !StringUtils.isEmpty(this.kunnr) && !StringUtils.isEmpty(this.fieldName);

  }
}