/*
This file was automatically generated by the EntityCreator engine on Tue Feb 02 17:16:30 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the ADDLCTRYDATA database table.
 * 
 * @author PriyRanjan
 */
@Entity
@Table(name = "ADDLCTRYDATA", schema = "SAPR3")
public class Addlctrydata extends BaseEntity<AddlctrydataPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private AddlctrydataPK id;

  public AddlctrydataPK getId() {
    return id;
  }

  public void setId(AddlctrydataPK id) {
    this.id = id;
  }
  
  @Column(name = "FIELD_VALUE")
  private String fieldValue;

  @Column(name = "FIELD_QUALIFIER")
  private String fieldQualifier;

  private String loevm;

  @Column(name = "CREATE_DT")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createDt;

  @Column(name = "CREATED_BY")
  private String createdBy;

  @Column(name = "UPDATE_DT")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateDt;

  @Column(name = "UPDATED_BY")
  private String updatedBy;

  @Column(name = "UPDATE_TYPE")
  private String updateType;

  public String getFieldValue(){
    return this.fieldValue;
  }

  public void setFieldValue(String fieldValue){
    this.fieldValue = fieldValue;
  }


  public String getFieldQualifier(){
    return this.fieldQualifier;
  }

  public void setFieldQualifier(String fieldQualifier){
    this.fieldQualifier = fieldQualifier;
  }


  public String getLoevm(){
    return this.loevm;
  }

  public void setLoevm(String loevm){
    this.loevm = loevm;
  }


  public Date getCreateDt(){
    return this.createDt;
  }

  public void setCreateDt(Date createDt){
    this.createDt = createDt;
  }


  public String getCreatedBy(){
    return this.createdBy;
  }

  public void setCreatedBy(String createdBy){
    this.createdBy = createdBy;
  }


  public Date getUpdateDt(){
    return this.updateDt;
  }

  public void setUpdateDt(Date updateDt){
    this.updateDt = updateDt;
  }


  public String getUpdatedBy(){
    return this.updatedBy;
  }

  public void setUpdatedBy(String updatedBy){
    this.updatedBy = updatedBy;
  }


  public String getUpdateType(){
    return this.updateType;
  }

  public void setUpdateType(String updateType){
    this.updateType = updateType;
  }




}