/*
This file was automatically generated by the EntityCreator engine on Mon Oct 05 22:10:14 CST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the ADDR_RDC database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(name = "ADDR_RDC", schema = "CREQCMR")
public class AddrRdc extends BaseEntity<AddrPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private AddrPK id;

  @Override
  public AddrPK getId() {
    return id;
  }

  @Override
  public void setId(AddrPK id) {
    this.id = id;
  }

  @Column(name = "CUST_NM1")
  private String custNm1;

  @Column(name = "CUST_NM2")
  private String custNm2;

  @Column(name = "CUST_NM3")
  private String custNm3;

  @Column(name = "CUST_NM4")
  private String custNm4;

  @Column(name = "ADDR_TXT")
  private String addrTxt;

  private String city1;

  @Column(name = "CITY2")
  private String city2;

  @Column(name = "STATE_PROV")
  private String stateProv;

  @Column(name = "POST_CD")
  private String postCd;

  @Column(name = "LAND_CNTRY")
  private String landCntry;

  private String county;

  @Column(name = "BLDG")
  private String bldg;

  @Column(name = "FLOOR")
  private String floor;

  @Column(name = "OFFICE")
  private String office;

  @Column(name = "DEPT")
  private String dept;

  @Column(name = "PO_BOX")
  private String poBox;

  @Column(name = "PO_BOX_CITY")
  private String poBoxCity;

  @Column(name = "PO_BOX_POST_CD")
  private String poBoxPostCd;

  @Column(name = "CUST_FAX")
  private String custFax;

  @Column(name = "CUST_PHONE")
  private String custPhone;

  @Column(name = "TRANSPORT_ZONE")
  private String transportZone;

  @Column(name = "ADDR_STD_RESULT")
  private String addrStdResult;

  @Column(name = "ADDR_STD_ACCEPT_IND")
  private String addrStdAcceptInd;

  @Column(name = "ADDR_STD_REJ_REASON")
  private String addrStdRejReason;

  @Column(name = "ADDR_STD_REJ_CMT")
  private String addrStdRejCmt;

  @Column(name = "ADDR_STD_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date addrStdTs;

  @Column(name = "SAP_NO")
  private String sapNo;

  @Column(name = "IMPORT_IND")
  private String importInd;

  @Column(name = "DIVN")
  private String divn;

  @Column(name = "ADDR_TXT_2")
  private String addrTxt2;

  @Column(name = "TAX_CD_1")
  private String taxCd1;

  @Column(name = "TAX_CD_2")
  private String taxCd2;

  @Column(name = "VAT")
  private String vat;

  @Column(name = "PAIRED_ADDR_SEQ")
  private String pairedAddrSeq;

  @Column(name = "BILLING_PSTL_ADDR")
  private String billingPstlAddr;

  @Column(name = "COMPANY_SIZE")
  private int companySize;

  @Column(name = "ROL")
  private String rol;

  @Column(name = "ESTAB_FUNC_CD")
  private String estabFuncCd;

  @Column(name = "CONTACT")
  private String contact;

  @Column(name = "CUST_LANG_CD")
  private String custLangCd;

  @Column(name = "HW_INSTL_MSTR_FLG")
  private String hwInstlMstrFlg;

  @Column(name = "TAX_OFFICE")
  private String taxOffice;

  public String getBillingPstlAddr() {
    return billingPstlAddr;
  }

  public void setBillingPstlAddr(String billingPstlAddr) {
    this.billingPstlAddr = billingPstlAddr;
  }

  public String getCustNm1() {
    return this.custNm1;
  }

  public void setCustNm1(String custNm1) {
    this.custNm1 = custNm1;
  }

  public String getCustNm2() {
    return this.custNm2;
  }

  public void setCustNm2(String custNm2) {
    this.custNm2 = custNm2;
  }

  public String getCustNm3() {
    return this.custNm3;
  }

  public void setCustNm3(String custNm3) {
    this.custNm3 = custNm3;
  }

  public String getCustNm4() {
    return this.custNm4;
  }

  public void setCustNm4(String custNm4) {
    this.custNm4 = custNm4;
  }

  public String getAddrTxt() {
    return this.addrTxt;
  }

  public void setAddrTxt(String addrTxt) {
    this.addrTxt = addrTxt;
  }

  public String getCity1() {
    return this.city1;
  }

  public void setCity1(String city1) {
    this.city1 = city1;
  }

  public String getCity2() {
    return this.city2;
  }

  public void setCity2(String city2) {
    this.city2 = city2;
  }

  public String getStateProv() {
    return this.stateProv;
  }

  public void setStateProv(String stateProv) {
    this.stateProv = stateProv;
  }

  public String getPostCd() {
    return this.postCd;
  }

  public void setPostCd(String postCd) {
    this.postCd = postCd;
  }

  public String getLandCntry() {
    return this.landCntry;
  }

  public void setLandCntry(String landCntry) {
    this.landCntry = landCntry;
  }

  public String getCounty() {
    return this.county;
  }

  public void setCounty(String county) {
    this.county = county;
  }

  public String getBldg() {
    return this.bldg;
  }

  public void setBldg(String bldg) {
    this.bldg = bldg;
  }

  public String getFloor() {
    return this.floor;
  }

  public void setFloor(String floor) {
    this.floor = floor;
  }

  public String getOffice() {
    return this.office;
  }

  public String getTaxOffice() {
    return taxOffice;
  }

  public void setTaxOffice(String taxOffice) {
    this.taxOffice = taxOffice;
  }

  public void setOffice(String office) {
    this.office = office;
  }

  public String getDept() {
    return this.dept;
  }

  public void setDept(String dept) {
    this.dept = dept;
  }

  public String getPoBox() {
    return this.poBox;
  }

  public void setPoBox(String poBox) {
    this.poBox = poBox;
  }

  public String getPoBoxCity() {
    return this.poBoxCity;
  }

  public void setPoBoxCity(String poBoxCity) {
    this.poBoxCity = poBoxCity;
  }

  public String getPoBoxPostCd() {
    return this.poBoxPostCd;
  }

  public void setPoBoxPostCd(String poBoxPostCd) {
    this.poBoxPostCd = poBoxPostCd;
  }

  public String getCustFax() {
    return this.custFax;
  }

  public void setCustFax(String custFax) {
    this.custFax = custFax;
  }

  public String getCustPhone() {
    return this.custPhone;
  }

  public void setCustPhone(String custPhone) {
    this.custPhone = custPhone;
  }

  public String getTransportZone() {
    return this.transportZone;
  }

  public void setTransportZone(String transportZone) {
    this.transportZone = transportZone;
  }

  public String getAddrStdResult() {
    return this.addrStdResult;
  }

  public void setAddrStdResult(String addrStdResult) {
    this.addrStdResult = addrStdResult;
  }

  public String getAddrStdAcceptInd() {
    return this.addrStdAcceptInd;
  }

  public void setAddrStdAcceptInd(String addrStdAcceptInd) {
    this.addrStdAcceptInd = addrStdAcceptInd;
  }

  public String getAddrStdRejReason() {
    return this.addrStdRejReason;
  }

  public void setAddrStdRejReason(String addrStdRejReason) {
    this.addrStdRejReason = addrStdRejReason;
  }

  public String getAddrStdRejCmt() {
    return this.addrStdRejCmt;
  }

  public void setAddrStdRejCmt(String addrStdRejCmt) {
    this.addrStdRejCmt = addrStdRejCmt;
  }

  public Date getAddrStdTs() {
    return this.addrStdTs;
  }

  public void setAddrStdTs(Date addrStdTs) {
    this.addrStdTs = addrStdTs;
  }

  public String getSapNo() {
    return this.sapNo;
  }

  public void setSapNo(String sapNo) {
    this.sapNo = sapNo;
  }

  public String getImportInd() {
    return this.importInd;
  }

  public void setImportInd(String importInd) {
    this.importInd = importInd;
  }

  public String getDivn() {
    return divn;
  }

  public void setDivn(String divn) {
    this.divn = divn;
  }

  public String getAddrTxt2() {
    return addrTxt2;
  }

  public void setAddrTxt2(String addrTxt2) {
    this.addrTxt2 = addrTxt2;
  }

  public String getTaxCd1() {
    return taxCd1;
  }

  public void setTaxCd1(String taxCd1) {
    this.taxCd1 = taxCd1;
  }

  public String getTaxCd2() {
    return taxCd2;
  }

  public void setTaxCd2(String taxCd2) {
    this.taxCd2 = taxCd2;
  }

  public String getVat() {
    return vat;
  }

  public void setVat(String vat) {
    this.vat = vat;
  }

  public String getPairedAddrSeq() {
    return pairedAddrSeq;
  }

  public void setPairedAddrSeq(String pairedAddrSeq) {
    this.pairedAddrSeq = pairedAddrSeq;
  }

  public int getCompanySize() {
    return companySize;
  }

  public void setCompanySize(int companySize) {
    this.companySize = companySize;
  }

  public String getRol() {
    return rol;
  }

  public void setRol(String rol) {
    this.rol = rol;
  }

  public String getEstabFuncCd() {
    return estabFuncCd;
  }

  public void setEstabFuncCd(String estabFuncCd) {
    this.estabFuncCd = estabFuncCd;
  }

  public String getContact() {
    return contact;
  }

  public void setContact(String contact) {
    this.contact = contact;
  }

  public String getCustLangCd() {
    return custLangCd;
  }

  public void setCustLangCd(String custLangCd) {
    this.custLangCd = custLangCd;
  }

  public String getHwInstlMstrFlg() {
    return hwInstlMstrFlg;
  }

  public void setHwInstlMstrFlg(String hwInstlMstrFlg) {
    this.hwInstlMstrFlg = hwInstlMstrFlg;
  }
}