/*
This file was automatically generated by the EntityCreator engine on Mon Apr 17 13:48:59 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the APPROVAL_TYP database table.
 * 
 * @author Jeffrey Zamora
 */
@Embeddable
public class ApprovalTypPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "TYP_ID")
  private int typId;

  @Column(name = "GEO_CD")
  private String geoCd;

  public int getTypId() {
    return this.typId;
  }

  public void setTypId(int typId) {
    this.typId = typId;
  }

  public String getGeoCd() {
    return this.geoCd;
  }

  public void setGeoCd(String geoCd) {
    this.geoCd = geoCd;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof ApprovalTypPK)) {
      return false;
    }
    ApprovalTypPK o = (ApprovalTypPK) other;
    return this.typId == o.typId && this.geoCd.equals(o.geoCd);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + this.typId;
    hash = hash * prime + (this.geoCd != null ? this.geoCd.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.typId > 0 && !StringUtils.isEmpty(this.geoCd);

  }
}