/*
This file was automatically generated by the EntityCreator engine on Mon Apr 17 13:48:59 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the APPROVAL_TYP database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(
    name = "APPROVAL_TYP",
    schema = "CREQCMR")
public class ApprovalTyp extends BaseEntity<ApprovalTypPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private ApprovalTypPK id;

  @Override
  public ApprovalTypPK getId() {
    return id;
  }

  @Override
  public void setId(ApprovalTypPK id) {
    this.id = id;
  }

  private String title;

  private String description;

  @Column(
      name = "TEMPLATE_NAME")
  private String templateName;

  @Column(
      name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(
      name = "CREATE_BY")
  private String createBy;

  @Column(
      name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date lastUpdtTs;

  @Column(
      name = "LAST_UPDT_BY")
  private String lastUpdtBy;

  @Column(
      name = "GRP_APPROVAL_INDC")
  private String grpApprovalIndc;

  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getTemplateName() {
    return this.templateName;
  }

  public void setTemplateName(String templateName) {
    this.templateName = templateName;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getLastUpdtTs() {
    return this.lastUpdtTs;
  }

  public void setLastUpdtTs(Date lastUpdtTs) {
    this.lastUpdtTs = lastUpdtTs;
  }

  public String getLastUpdtBy() {
    return this.lastUpdtBy;
  }

  public void setLastUpdtBy(String lastUpdtBy) {
    this.lastUpdtBy = lastUpdtBy;
  }

  public String getGrpApprovalIndc() {
    return grpApprovalIndc;
  }

  public void setGrpApprovalIndc(String grpApprovalIndc) {
    this.grpApprovalIndc = grpApprovalIndc;
  }

}