/*
This file was automatically generated by the EntityCreator engine on Mon Apr 17 13:49:18 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the APPROVAL_HIST database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(name = "APPROVAL_HIST", schema = "CREQCMR")
public class ApprovalHist extends BaseEntity<ApprovalHistPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private ApprovalHistPK id;

  @Override
  public ApprovalHistPK getId() {
    return id;
  }

  @Override
  public void setId(ApprovalHistPK id) {
    this.id = id;
  }

  @Column(name = "USER_ID")
  private String userId;

  private String status;

  public String getUserId() {
    return this.userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

}