/*
This file was automatically generated by the EntityCreator engine on Mon Apr 17 13:49:00 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * The primary key class for the APPROVAL_COMMENTS database table.
 * 
 * @author Jeffrey Zamora
 */
@Embeddable
public class ApprovalCommentsPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "APPROVAL_CMT_ID")
  private long approvalCmtId;

  public long getApprovalCmtId() {
    return this.approvalCmtId;
  }

  public void setApprovalCmtId(long approvalCmtId) {
    this.approvalCmtId = approvalCmtId;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof ApprovalCommentsPK)) {
      return false;
    }
    ApprovalCommentsPK o = (ApprovalCommentsPK) other;
    return this.approvalCmtId == o.approvalCmtId;

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.approvalCmtId > 0 ? new java.lang.Long(this.approvalCmtId).hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.approvalCmtId > 0;

  }
}