/*
This file was automatically generated by the EntityCreator engine on Mon Apr 17 13:48:58 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.EntityResult;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.cio.cmr.request.entity.listeners.ChangeLogDetails;
import com.ibm.cio.cmr.request.entity.listeners.ChangeLogListener;
import com.ibm.cio.cmr.request.entity.listeners.NoLog;

/**
 * The persistent class for the APPROVAL_REQ database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(
    name = "APPROVAL_REQ",
    schema = "CREQCMR")
@SqlResultSetMappings({ @SqlResultSetMapping(
    name = "ApprovalListMapping",
    entities = { @EntityResult(
        entityClass = ApprovalReq.class) },
    columns = { @ColumnResult(
        name = "STATUS_STR"),
        @ColumnResult(
            name = "TYPE") }) })
@EntityListeners(ChangeLogListener.class)
@ChangeLogDetails(
    childTable = true,
    reqId = "reqId",
    userId = "lastUpdtBy")
public class ApprovalReq extends BaseEntity<ApprovalReqPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  public static String APPROVAL_LIST_MAPPING = "ApprovalListMapping";

  @EmbeddedId
  @NoLog
  private ApprovalReqPK id;

  @Override
  public ApprovalReqPK getId() {
    return id;
  }

  @Override
  public void setId(ApprovalReqPK id) {
    this.id = id;
  }

  @Column(
      name = "REQ_ID")
  private long reqId;

  @Column(
      name = "TYP_ID")
  private int typId;

  @Column(
      name = "GEO_CD")
  private String geoCd;

  @Column(
      name = "INTRANET_ID")
  private String intranetId;

  @NoLog
  @Column(
      name = "NOTES_ID")
  private String notesId;

  @NoLog
  @Column(
      name = "DISPLAY_NAME")
  private String displayName;

  private String status;

  @Column(
      name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  @NoLog
  private Date createTs;

  @Column(
      name = "CREATE_BY")
  private String createBy;

  @Column(
      name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  @NoLog
  private Date lastUpdtTs;

  @Column(
      name = "LAST_UPDT_BY")
  private String lastUpdtBy;

  @Column(
      name = "REQUIRED_INDC")
  private String requiredIndc;

  @Column(
      name = "DEFAULT_APPROVAL_ID")
  private long defaultApprovalId;

  public long getReqId() {
    return this.reqId;
  }

  public void setReqId(long reqId) {
    this.reqId = reqId;
  }

  public int getTypId() {
    return this.typId;
  }

  public void setTypId(int typId) {
    this.typId = typId;
  }

  public String getGeoCd() {
    return this.geoCd;
  }

  public void setGeoCd(String geoCd) {
    this.geoCd = geoCd;
  }

  public String getIntranetId() {
    return this.intranetId;
  }

  public void setIntranetId(String intranetId) {
    this.intranetId = intranetId;
  }

  public String getNotesId() {
    return this.notesId;
  }

  public void setNotesId(String notesId) {
    this.notesId = notesId;
  }

  public String getDisplayName() {
    return this.displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getLastUpdtTs() {
    return this.lastUpdtTs;
  }

  public void setLastUpdtTs(Date lastUpdtTs) {
    this.lastUpdtTs = lastUpdtTs;
  }

  public String getLastUpdtBy() {
    return this.lastUpdtBy;
  }

  public void setLastUpdtBy(String lastUpdtBy) {
    this.lastUpdtBy = lastUpdtBy;
  }

  public String getRequiredIndc() {
    return this.requiredIndc;
  }

  public void setRequiredIndc(String requiredIndc) {
    this.requiredIndc = requiredIndc;
  }

  public long getDefaultApprovalId() {
    return defaultApprovalId;
  }

  public void setDefaultApprovalId(long defaultApprovalId) {
    this.defaultApprovalId = defaultApprovalId;
  }

}