/*
This file was automatically generated by the EntityCreator engine on Thu Aug 20 16:15:31 IST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the ATTACHMENT database table.
 * 
 * @author Rama mohan
 */
@Entity
@Table(name = "ATTACHMENT", schema = "CREQCMR")
public class Attachment extends BaseEntity<AttachmentPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private AttachmentPK id;

  @Override
  public AttachmentPK getId() {
    return id;
  }

  @Override
  public void setId(AttachmentPK id) {
    this.id = id;
  }

  @Column(name = "DOC_CONTENT")
  private String docContent;

  @Column(name = "DOC_ATTACH_BY_ID")
  private String docAttachById;

  @Column(name = "DOC_ATTACH_BY_NM")
  private String docAttachByNm;

  @Column(name = "ATTACH_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Timestamp attachTs;

  private String cmt;

  public String getDocContent() {
    return this.docContent;
  }

  public void setDocContent(String docContent) {
    this.docContent = docContent;
  }

  public String getDocAttachById() {
    return this.docAttachById;
  }

  public void setDocAttachById(String docAttachById) {
    this.docAttachById = docAttachById;
  }

  public String getDocAttachByNm() {
    return this.docAttachByNm;
  }

  public void setDocAttachByNm(String docAttachByNm) {
    this.docAttachByNm = docAttachByNm;
  }

  public Timestamp getAttachTs() {
    return this.attachTs;
  }

  public void setAttachTs(Timestamp attachTs) {
    this.attachTs = attachTs;
  }

  public String getCmt() {
    return this.cmt;
  }

  public void setCmt(String cmt) {
    this.cmt = cmt;
  }

}