/*
This file was automatically generated by the EntityCreator engine on Tue Aug 27 22:40:25 SGT 2019.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the AUTOMATION_DATA database table.
 * 
 * @author JeffZAMORA
 */
@Entity
@Table(name = "AUTOMATION_DATA", schema = "CREQCMR")
public class AutomationData extends BaseEntity<AutomationDataPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private AutomationDataPK id;

  public AutomationDataPK getId() {
    return id;
  }

  public void setId(AutomationDataPK id) {
    this.id = id;
  }
  
  /** 
   * Old Value
   */ 
  @Column(name = "OLD_VALUE")
  private String oldValue;

  /** 
   * New Value
   */ 
  @Column(name = "NEW_VALUE")
  private String newValue;

  /** 
   * Imported Indicator
   */ 
  @Column(name = "IMPORTED_INDC")
  private String importedIndc;

  /** 
   * Created By
   */ 
  @Column(name = "CREATE_BY")
  private String createBy;

  /** 
   * Create Timestamp
   */ 
  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  /** 
   * Last Update By
   */ 
  @Column(name = "LAST_UPDT_BY")
  private String lastUpdtBy;

  /** 
   * Last Update Timestamp
   */ 
  @Column(name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date lastUpdtTs;

  public String getOldValue(){
    return this.oldValue;
  }

  public void setOldValue(String oldValue){
    this.oldValue = oldValue;
  }


  public String getNewValue(){
    return this.newValue;
  }

  public void setNewValue(String newValue){
    this.newValue = newValue;
  }


  public String getImportedIndc(){
    return this.importedIndc;
  }

  public void setImportedIndc(String importedIndc){
    this.importedIndc = importedIndc;
  }


  public String getCreateBy(){
    return this.createBy;
  }

  public void setCreateBy(String createBy){
    this.createBy = createBy;
  }


  public Date getCreateTs(){
    return this.createTs;
  }

  public void setCreateTs(Date createTs){
    this.createTs = createTs;
  }


  public String getLastUpdtBy(){
    return this.lastUpdtBy;
  }

  public void setLastUpdtBy(String lastUpdtBy){
    this.lastUpdtBy = lastUpdtBy;
  }


  public Date getLastUpdtTs(){
    return this.lastUpdtTs;
  }

  public void setLastUpdtTs(Date lastUpdtTs){
    this.lastUpdtTs = lastUpdtTs;
  }




}