/*
This file was automatically generated by the EntityCreator engine on Tue Aug 27 22:40:25 SGT 2019.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the AUTOMATION_DATA database table.
 * 
 * @author JeffZAMORA
 */
@Embeddable
public class AutomationDataPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  /** 
   * Automation Result Identifier
   */ 
  @Column(name = "AUTOMATION_RESULT_ID")
  private long automationResultId;

  /** 
   * Process Code
   */ 
  @Column(name = "PROCESS_CD")
  private String processCd;

  /** 
   * Address Type
   */ 
  @Column(name = "ADDR_TYP")
  private String addrTyp;

  /** 
   * Field Name
   */ 
  @Column(name = "FIELD_NAME")
  private String fieldName;

  public long getAutomationResultId(){
    return this.automationResultId;
  }

  public void setAutomationResultId(long automationResultId){
    this.automationResultId = automationResultId;
  }


  public String getProcessCd(){
    return this.processCd;
  }

  public void setProcessCd(String processCd){
    this.processCd = processCd;
  }


  public String getAddrTyp(){
    return this.addrTyp;
  }

  public void setAddrTyp(String addrTyp){
    this.addrTyp = addrTyp;
  }


  public String getFieldName(){
    return this.fieldName;
  }

  public void setFieldName(String fieldName){
    this.fieldName = fieldName;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof AutomationDataPK)) {
      return false;
    }
    AutomationDataPK o = (AutomationDataPK) other;
    return this.automationResultId == o.automationResultId && this.processCd.equals(o.processCd) && this.addrTyp.equals(o.addrTyp) && this.fieldName.equals(o.fieldName);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.automationResultId > 0 ? new java.lang.Long(this.automationResultId).hashCode() : 0);
    hash = hash * prime + (this.processCd != null ? this.processCd.hashCode() : 0);
    hash = hash * prime + (this.addrTyp != null ? this.addrTyp.hashCode() : 0);
    hash = hash * prime + (this.fieldName != null ? this.fieldName.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.automationResultId > 0 && !StringUtils.isEmpty(this.processCd) && !StringUtils.isEmpty(this.addrTyp) && !StringUtils.isEmpty(this.fieldName);

  }
}