/*
This file was automatically generated by the EntityCreator engine on Tue Aug 27 22:40:22 SGT 2019.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityResult;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the AUTOMATION_RESULTS database table.
 * 
 * @author JeffZAMORA
 */
@SqlResultSetMappings({ @SqlResultSetMapping(
    name = "AutoResultsMapping",
    entities = { @EntityResult(
        entityClass = AutomationResults.class) },
    columns = { @ColumnResult(
        name = "MATCH_IMPORT"), @ColumnResult(
        name = "OVERRIDE_IMPORT") }) })
@Entity
@Table(
    name = "AUTOMATION_RESULTS",
    schema = "CREQCMR")
public class AutomationResults extends BaseEntity<AutomationResultsPK> implements Serializable {
  private static final long serialVersionUID = 1L;
  public static final String AUTO_RESULTS_MAPPING = "AutoResultsMapping";

  @EmbeddedId
  private AutomationResultsPK id;

  @Override
  public AutomationResultsPK getId() {
    return id;
  }

  @Override
  public void setId(AutomationResultsPK id) {
    this.id = id;
  }

  /**
   * Process Type
   */
  @Column(
      name = "PROCESS_TYP")
  private String processTyp;

  /**
   * Process Description
   */
  @Column(
      name = "PROCESS_DESC")
  private String processDesc;

  /**
   * Process Result
   */
  @Column(
      name = "PROCESS_RESULT")
  private String processResult;

  /**
   * Detailed Results
   */
  @Column(
      name = "DETAILED_RESULTS")
  private String detailedResults;

  /**
   * Created By
   */
  @Column(
      name = "CREATE_BY")
  private String createBy;

  /**
   * Create Timestamp
   */
  @Column(
      name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(
      name = "FAILURE_INDC")
  private String failureIndc;

  public String getProcessTyp() {
    return this.processTyp;
  }

  public void setProcessTyp(String processTyp) {
    this.processTyp = processTyp;
  }

  public String getProcessDesc() {
    return this.processDesc;
  }

  public void setProcessDesc(String processDesc) {
    this.processDesc = processDesc;
  }

  public String getProcessResult() {
    return this.processResult;
  }

  public void setProcessResult(String processResult) {
    this.processResult = processResult;
  }

  public String getDetailedResults() {
    return this.detailedResults;
  }

  public void setDetailedResults(String detailedResults) {
    this.detailedResults = detailedResults;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getFailureIndc() {
    return failureIndc;
  }

  public void setFailureIndc(String failureIndc) {
    this.failureIndc = failureIndc;
  }

}