/*
This file was automatically generated by the EntityCreator engine on Tue Aug 27 22:40:23 SGT 2019.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the AUTO_ENGINE_CONFIG database table.
 * 
 * @author JeffZAMORA
 */
@Entity
@Table(name = "AUTO_ENGINE_CONFIG", schema = "CREQCMR")
public class AutoEngineConfig extends BaseEntity<AutoEngineConfigPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private AutoEngineConfigPK id;

  public AutoEngineConfigPK getId() {
    return id;
  }

  public void setId(AutoEngineConfigPK id) {
    this.id = id;
  }
  
  /** 
   * Execution Order
   */ 
  @Column(name = "EXEC_ORD")
  private int execOrd;

  /** 
   * Process Code
   */ 
  @Column(name = "PROCESS_CD")
  private String processCd;

  /** 
   * Request Type
   */ 
  @Column(name = "REQUEST_TYP")
  private String requestTyp;

  /** 
   * Action on Error
   */ 
  @Column(name = "ACTION_ON_ERROR")
  private String actionOnError;

  /** 
   * Override Data Indicator
   */ 
  @Column(name = "OVERRIDE_DATA_INDC")
  private String overrideDataIndc;

  /** 
   * Stop on Error Indicator
   */ 
  @Column(name = "STOP_ON_ERROR_INDC")
  private String stopOnErrorIndc;

  /** 
   * Status
   */ 
  private String status;

  /** 
   * Created By
   */ 
  @Column(name = "CREATE_BY")
  private String createBy;

  /** 
   * Create Timestamp
   */ 
  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  /** 
   * Last Update By
   */ 
  @Column(name = "LAST_UPDT_BY")
  private String lastUpdtBy;

  /** 
   * Last Update Timestamp
   */ 
  @Column(name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date lastUpdtTs;

  public int getExecOrd(){
    return this.execOrd;
  }

  public void setExecOrd(int execOrd){
    this.execOrd = execOrd;
  }


  public String getProcessCd(){
    return this.processCd;
  }

  public void setProcessCd(String processCd){
    this.processCd = processCd;
  }


  public String getRequestTyp(){
    return this.requestTyp;
  }

  public void setRequestTyp(String requestTyp){
    this.requestTyp = requestTyp;
  }


  public String getActionOnError(){
    return this.actionOnError;
  }

  public void setActionOnError(String actionOnError){
    this.actionOnError = actionOnError;
  }


  public String getOverrideDataIndc(){
    return this.overrideDataIndc;
  }

  public void setOverrideDataIndc(String overrideDataIndc){
    this.overrideDataIndc = overrideDataIndc;
  }


  public String getStopOnErrorIndc(){
    return this.stopOnErrorIndc;
  }

  public void setStopOnErrorIndc(String stopOnErrorIndc){
    this.stopOnErrorIndc = stopOnErrorIndc;
  }


  public String getStatus(){
    return this.status;
  }

  public void setStatus(String status){
    this.status = status;
  }


  public String getCreateBy(){
    return this.createBy;
  }

  public void setCreateBy(String createBy){
    this.createBy = createBy;
  }


  public Date getCreateTs(){
    return this.createTs;
  }

  public void setCreateTs(Date createTs){
    this.createTs = createTs;
  }


  public String getLastUpdtBy(){
    return this.lastUpdtBy;
  }

  public void setLastUpdtBy(String lastUpdtBy){
    this.lastUpdtBy = lastUpdtBy;
  }


  public Date getLastUpdtTs(){
    return this.lastUpdtTs;
  }

  public void setLastUpdtTs(Date lastUpdtTs){
    this.lastUpdtTs = lastUpdtTs;
  }




}