/*
This file was automatically generated by the EntityCreator engine on Tue Aug 27 22:40:25 SGT 2019.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the AUTOMATION_MATCHING database table.
 * 
 * @author JeffZAMORA
 */
@Embeddable
public class AutomationMatchingPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  /**
   * Automation Result Identifier
   */
  @Column(
      name = "AUTOMATION_RESULT_ID")
  private long automationResultId;

  /**
   * Process Code
   */
  @Column(
      name = "PROCESS_CD")
  private String processCd;

  /**
   * Match Key Name
   */
  @Column(
      name = "MATCH_KEY_NAME")
  private String matchKeyName;

  /**
   * Match Key Value
   */
  @Column(
      name = "MATCH_KEY_VALUE")
  private String matchKeyValue;

  /**
   * Item Number
   */
  @Column(
      name = "ITEM_NO")
  private int itemNo;

  public long getAutomationResultId() {
    return this.automationResultId;
  }

  public void setAutomationResultId(long automationResultId) {
    this.automationResultId = automationResultId;
  }

  public String getProcessCd() {
    return this.processCd;
  }

  public void setProcessCd(String processCd) {
    this.processCd = processCd;
  }

  public String getMatchKeyName() {
    return this.matchKeyName;
  }

  public void setMatchKeyName(String matchKeyName) {
    this.matchKeyName = matchKeyName;
  }

  public String getMatchKeyValue() {
    return this.matchKeyValue;
  }

  public void setMatchKeyValue(String matchKeyValue) {
    this.matchKeyValue = matchKeyValue;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof AutomationMatchingPK)) {
      return false;
    }
    AutomationMatchingPK o = (AutomationMatchingPK) other;
    return this.automationResultId == o.automationResultId && this.processCd.equals(o.processCd) && this.matchKeyName.equals(o.matchKeyName)
        && this.matchKeyValue.equals(o.matchKeyValue) && this.itemNo == o.itemNo;

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.automationResultId > 0 ? new java.lang.Long(this.automationResultId).hashCode() : 0);
    hash = hash * prime + (this.itemNo > 0 ? new java.lang.Integer(this.itemNo).hashCode() : 0);
    hash = hash * prime + (this.processCd != null ? this.processCd.hashCode() : 0);
    hash = hash * prime + (this.matchKeyName != null ? this.matchKeyName.hashCode() : 0);
    hash = hash * prime + (this.matchKeyValue != null ? this.matchKeyValue.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.automationResultId > 0 && !StringUtils.isEmpty(this.processCd) && !StringUtils.isEmpty(this.matchKeyName)
        && !StringUtils.isEmpty(this.matchKeyValue) && this.itemNo > 0;

  }

  public int getItemNo() {
    return itemNo;
  }

  public void setItemNo(int itemNo) {
    this.itemNo = itemNo;
  }
}