/*
This file was automatically generated by the EntityCreator engine on Thu Aug 06 19:58:15 CST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the BDS_TBL_INFO database table.
 * 
 * @author Jeffrey Zamora
 */
@Embeddable
public class BdsTblInfoPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "FIELD_ID")
  private String fieldId;

  public String getFieldId() {
    return this.fieldId;
  }

  public void setFieldId(String fieldId) {
    this.fieldId = fieldId;
  }

  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof BdsTblInfoPK)) {
      return false;
    }
    BdsTblInfoPK o = (BdsTblInfoPK) other;
    return this.fieldId.equals(o.fieldId);

  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.fieldId != null ? this.fieldId.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.fieldId);

  }
}