/*
This file was automatically generated by the EntityCreator engine on Thu Aug 06 19:58:15 CST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the BDS_TBL_INFO database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(name = "BDS_TBL_INFO", schema = "CREQCMR")
public class BdsTblInfo extends BaseEntity<BdsTblInfoPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private BdsTblInfoPK id;

  @Override
  public BdsTblInfoPK getId() {
    return id;
  }

  @Override
  public void setId(BdsTblInfoPK id) {
    this.id = id;
  }

  private String schema;

  private String tbl;

  private String cd;

  private String desc;

  @Column(name = "DISP_TYPE")
  private String dispType;

  @Column(name = "ORDER_BY_FIELD")
  private String orderByField;

  private String cmt;

  public String getSchema() {
    return this.schema;
  }

  public void setSchema(String schema) {
    this.schema = schema;
  }

  public String getTbl() {
    return this.tbl;
  }

  public void setTbl(String tbl) {
    this.tbl = tbl;
  }

  public String getCd() {
    return this.cd;
  }

  public void setCd(String cd) {
    this.cd = cd;
  }

  public String getDesc() {
    return this.desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }

  public String getDispType() {
    return this.dispType;
  }

  public void setDispType(String dispType) {
    this.dispType = dispType;
  }

  public String getOrderByField() {
    return this.orderByField;
  }

  public void setOrderByField(String orderByField) {
    this.orderByField = orderByField;
  }

  public String getCmt() {
    return this.cmt;
  }

  public void setCmt(String cmt) {
    this.cmt = cmt;
  }

}