/*
This file was automatically generated by the EntityCreator engine on Tue May 16 16:18:49 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.StringUtils;

/**
 * The primary key class for the US_BP_INT_CODES database table.
 * 
 * @author Jeffrey Zamora
 */
@Embeddable
public class BPCodeIntPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "BP_CODE")
  private String bpCode;

  @Column(name = "MANDT")
  private String mandt;

  public String getMandt() {
    return mandt;
  }

  public void setMandt(String mandt) {
    this.mandt = mandt;
  }

  public String getBpCode() {
    return bpCode;
  }

  public void setBpCode(String bpCode) {
    this.bpCode = bpCode;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof BPCodeIntPK)) {
      return false;
    }
    BPCodeIntPK o = (BPCodeIntPK) other;
    return this.bpCode.equals(o.bpCode) && this.mandt.equals(o.mandt);
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.bpCode != null ? this.bpCode.hashCode() : 0);
    hash = hash * prime + (this.mandt != null ? this.mandt.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.bpCode) && !StringUtils.isEmpty(this.mandt);
  }
}