/*
This file was automatically generated by the EntityCreator engine on Mon Apr 12 19:01:20 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the CHANGELOG database table.
 * 
 * @author PriyRanjan
 */
@Entity
@Table(name = "CHANGELOG", schema = "SAPR3")
public class Changelog implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private ChangelogPK id;

  public ChangelogPK getId() {
    return id;
  }

  public void setId(ChangelogPK id) {
    this.id = id;
  }

  /**
   * Old Changes
   */
  private String old;

  /**
   * New
   */
  @Column(name = "NEW")
  private String newValue;

  /**
   * Account group
   */
  private String actgrp;

  private String action;

  /**
   * User Identifier
   */
  private String userid;

  /**
   * Change Point
   */
  private String chgpnt;

  /**
   * Tabkey1
   */
  private String tabkey1;

  /**
   * Tabkey1
   */
  private String tabkey2;

  /**
   * Tabkey1
   */
  private String tabkey3;

  /**
   * Tabkey1
   */
  private String tabkey4;

  /**
   * Tabkey1
   */
  private String tabkey5;

  /**
   * Tabkey1
   */
  private String tabkey6;

  /**
   * Tabkey1
   */
  private String tabkey7;

  /**
   * Tabkey1
   */
  private String tabkey8;

  /**
   * Name of the File Load
   */
  private String loadfilename;

  /**
   * Line Number
   */
  private String linenumber;

  public String getOld() {
    return this.old;
  }

  public void setOld(String old) {
    this.old = old;
  }

  public String getNewValue() {
    return newValue;
  }

  public void setNewValue(String newValue) {
    this.newValue = newValue;
  }

  public String getActgrp() {
    return this.actgrp;
  }

  public void setActgrp(String actgrp) {
    this.actgrp = actgrp;
  }

  public String getAction() {
    return this.action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public String getUserid() {
    return this.userid;
  }

  public void setUserid(String userid) {
    this.userid = userid;
  }

  public String getChgpnt() {
    return this.chgpnt;
  }

  public void setChgpnt(String chgpnt) {
    this.chgpnt = chgpnt;
  }

  public String getTabkey1() {
    return this.tabkey1;
  }

  public void setTabkey1(String tabkey1) {
    this.tabkey1 = tabkey1;
  }

  public String getTabkey2() {
    return this.tabkey2;
  }

  public void setTabkey2(String tabkey2) {
    this.tabkey2 = tabkey2;
  }

  public String getTabkey3() {
    return this.tabkey3;
  }

  public void setTabkey3(String tabkey3) {
    this.tabkey3 = tabkey3;
  }

  public String getTabkey4() {
    return this.tabkey4;
  }

  public void setTabkey4(String tabkey4) {
    this.tabkey4 = tabkey4;
  }

  public String getTabkey5() {
    return this.tabkey5;
  }

  public void setTabkey5(String tabkey5) {
    this.tabkey5 = tabkey5;
  }

  public String getTabkey6() {
    return this.tabkey6;
  }

  public void setTabkey6(String tabkey6) {
    this.tabkey6 = tabkey6;
  }

  public String getTabkey7() {
    return this.tabkey7;
  }

  public void setTabkey7(String tabkey7) {
    this.tabkey7 = tabkey7;
  }

  public String getTabkey8() {
    return this.tabkey8;
  }

  public void setTabkey8(String tabkey8) {
    this.tabkey8 = tabkey8;
  }

  public String getLoadfilename() {
    return this.loadfilename;
  }

  public void setLoadfilename(String loadfilename) {
    this.loadfilename = loadfilename;
  }

  public String getLinenumber() {
    return this.linenumber;
  }

  public void setLinenumber(String linenumber) {
    this.linenumber = linenumber;
  }

}