/*
This file was automatically generated by the EntityCreator engine on Mon Apr 12 19:01:20 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The primary key class for the CHANGELOG database table.
 * 
 * @author PriyRanjan
 */
@Embeddable
public class ChangelogPK implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  /**
   * SAP instance
   */
  private String mandt;

  /**
   * Last updated date
   */
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CHGTS", columnDefinition = "TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP")
  private Date chgts;

  /**
   * TABLE
   */
  private String tab;

  /**
   * SAP Customer number
   */
  private String kunnr;

  /**
   * FIELD
   */
  private String field;

  public String getMandt() {
    return this.mandt;
  }

  public void setMandt(String mandt) {
    this.mandt = mandt;
  }

  public Date getChgts() {
    return this.chgts;
  }

  public void setChgts(Date chgts) {
    this.chgts = chgts;
  }

  public String getTab() {
    return this.tab;
  }

  public void setTab(String tab) {
    this.tab = tab;
  }

  public String getKunnr() {
    return this.kunnr;
  }

  public void setKunnr(String kunnr) {
    this.kunnr = kunnr;
  }

  public String getField() {
    return this.field;
  }

  public void setField(String field) {
    this.field = field;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof ChangelogPK)) {
      return false;
    }
    ChangelogPK o = (ChangelogPK) other;
    return this.mandt.equals(o.mandt) && this.chgts.equals(o.chgts) && this.tab.equals(o.tab) && this.kunnr.equals(o.kunnr)
        && this.field.equals(o.field);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.mandt != null ? this.mandt.hashCode() : 0);
    hash = hash * prime + (this.chgts != null ? this.chgts.hashCode() : 0);
    hash = hash * prime + (this.tab != null ? this.tab.hashCode() : 0);
    hash = hash * prime + (this.kunnr != null ? this.kunnr.hashCode() : 0);
    hash = hash * prime + (this.field != null ? this.field.hashCode() : 0);

    return hash;
  }

  /*
   * @Override protected boolean allKeysAssigned() { return
   * !StringUtils.isEmpty(this.mandt) && !StringUtils.isEmpty(this.chgts) &&
   * !StringUtils.isEmpty(this.tab) && !StringUtils.isEmpty(this.kunnr) &&
   * !StringUtils.isEmpty(this.field);
   * 
   * }
   */
}