/*
This file was automatically generated by the EntityCreator engine on Wed Jan 11 18:15:54 SGT 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityResult;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the CLAIM_ROLES database table.
 * 
 * @author Eduard Bernardo
 */
@Entity
@Table(name = "CLAIM_ROLES", schema = "CREQCMR")
@SqlResultSetMappings({
    @SqlResultSetMapping(name = "ClaimRoleListMapping", entities = { @EntityResult(entityClass = ClaimRoles.class) }, columns = {
        @ColumnResult(name = "COUNTRY"), @ColumnResult(name = "REQ_STATUS_DESC"), @ColumnResult(name = "CLAIM_ROLE_DESC"),
        @ColumnResult(name = "CLAIM_SUB_ROLE_DESC"), @ColumnResult(name = "INTERNAL_TYP_DESC") }),
    @SqlResultSetMapping(name = "ClaimRoleMapping", entities = { @EntityResult(entityClass = ClaimRoles.class) }, columns = {
        @ColumnResult(name = "COUNTRY"), @ColumnResult(name = "REQ_STATUS_DESC"), @ColumnResult(name = "INTERNAL_TYP_DESC") }) })
public class ClaimRoles extends BaseEntity<ClaimRolesPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  public static String CLAIM_ROLES_LIST_MAPPING = "ClaimRoleListMapping";
  public static String CLAIM_ROLES_MAPPING = "ClaimRoleMapping";

  @EmbeddedId
  private ClaimRolesPK id;

  @Override
  public ClaimRolesPK getId() {
    return id;
  }

  @Override
  public void setId(ClaimRolesPK id) {
    this.id = id;
  }

  @Column(name = "CLAIM_ROLE_ID")
  private String claimRoleId;

  @Column(name = "CLAIM_SUB_ROLE_ID")
  private String claimSubRoleId;

  @Column(name = "STATUS")
  private String status;

  @Column(name = "CREATE_BY")
  private String createBy;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(name = "UPDATE_BY")
  private String updateBy;

  @Column(name = "UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateTs;

  public String getClaimRoleId() {
    return this.claimRoleId;
  }

  public void setClaimRoleId(String claimRoleId) {
    this.claimRoleId = claimRoleId;
  }

  public String getClaimSubRoleId() {
    return this.claimSubRoleId;
  }

  public void setClaimSubRoleId(String claimSubRoleId) {
    this.claimSubRoleId = claimSubRoleId;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getUpdateBy() {
    return this.updateBy;
  }

  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  public Date getUpdateTs() {
    return this.updateTs;
  }

  public void setUpdateTs(Date updateTs) {
    this.updateTs = updateTs;
  }

}