/*
This file was automatically generated by the EntityCreator engine on Mon Jan 18 14:50:53 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang3.StringUtils;

/**
 * The primary key class for the CMR_CLONING_PROCESS database table.
 * 
 * @author PriyRanjan
 */
@Embeddable
public class CmrCloningProcessPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "CMR_CLONING_PROCESS_ID")
  private long cmrCloningProcessId;

  public long getCmrCloningProcessId(){
    return this.cmrCloningProcessId;
  }

  public void setCmrCloningProcessId(long cmrCloningProcessId){
    this.cmrCloningProcessId = cmrCloningProcessId;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof CmrCloningProcessPK)) {
      return false;
    }
    CmrCloningProcessPK o = (CmrCloningProcessPK) other;
    return this.cmrCloningProcessId == o.cmrCloningProcessId;


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.cmrCloningProcessId > 0 ? new java.lang.Long(this.cmrCloningProcessId).hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.cmrCloningProcessId > 0;

  }
}