/*
This file was automatically generated by the EntityCreator engine on Thu Sep 22 17:54:22 CST 2016.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the CMR_INTERNAL_TYPES database table.
 * 
 * @author Jeffrey Zamora
 */
@Embeddable
public class CmrInternalTypesPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "CMR_ISSUING_CNTRY")
  private String cmrIssuingCntry;

  @Column(name = "INTERNAL_TYP")
  private String internalTyp;

  public String getCmrIssuingCntry(){
    return this.cmrIssuingCntry;
  }

  public void setCmrIssuingCntry(String cmrIssuingCntry){
    this.cmrIssuingCntry = cmrIssuingCntry;
  }


  public String getInternalTyp(){
    return this.internalTyp;
  }

  public void setInternalTyp(String internalTyp){
    this.internalTyp = internalTyp;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof CmrInternalTypesPK)) {
      return false;
    }
    CmrInternalTypesPK o = (CmrInternalTypesPK) other;
    return this.cmrIssuingCntry.equals(o.cmrIssuingCntry) && this.internalTyp.equals(o.internalTyp);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.cmrIssuingCntry != null ? this.cmrIssuingCntry.hashCode() : 0);
    hash = hash * prime + (this.internalTyp != null ? this.internalTyp.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.cmrIssuingCntry) && !StringUtils.isEmpty(this.internalTyp);

  }
}