/*
This file was automatically generated by the EntityCreator engine on Thu Aug 16 11:17:36 SGT 2018.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the CMRTALNK database table.
 * 
 * @author JeffZAMORA
 */
@Embeddable
public class CmrtAddrLinkPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  /**
   * COUNTRY 2 CODE
   */
  @Column(name = "RCYAA2")
  private String cntryCd2;

  /**
   * CUSTOMER 2 NUMBER
   */
  @Column(name = "RCUXA2")
  private String customerNumber2;

  /**
   * COUNTRY 1 CODE(OWN)
   */
  @Column(name = "RCYAA1")
  private String cntryCd1;

  /**
   * CUSTOMER 1 NUMBER
   */
  @Column(name = "RCUXA1")
  private String customerNumber1;

  /**
   * ADDRESS NUMBER
   */
  @Column(name = "RASXA1")
  private int addrNo;

  /**
   * ADDR USE OF BORROVING CN
   */
  /*
   * @Column( name = "ADDRUSE2") private String addrUse2;
   */

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof CmrtAddrLinkPK)) {
      return false;
    }
    CmrtAddrLinkPK o = (CmrtAddrLinkPK) other;
    return this.cntryCd1.equals(o.cntryCd1) && this.cntryCd2.equals(o.cntryCd2) && this.customerNumber1.equals(o.customerNumber1)
        && this.customerNumber2.equals(o.customerNumber2) && this.addrNo == o.addrNo;

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.cntryCd1 != null ? this.cntryCd1.hashCode() : 0);
    hash = hash * prime + (this.cntryCd2 != null ? this.cntryCd2.hashCode() : 0);
    hash = hash * prime + (this.customerNumber1 != null ? this.customerNumber1.hashCode() : 0);
    hash = hash * prime + (this.customerNumber2 != null ? this.customerNumber2.hashCode() : 0);
    hash = hash * prime + this.addrNo;

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.cntryCd1) && !StringUtils.isEmpty(this.cntryCd2) && !StringUtils.isEmpty(this.customerNumber1)
        && !StringUtils.isEmpty(this.customerNumber2) && this.addrNo > 0;

  }

  public String getCntryCd2() {
    return cntryCd2;
  }

  public void setCntryCd2(String cntryCd2) {
    this.cntryCd2 = cntryCd2;
  }

  public String getCustomerNumber2() {
    return customerNumber2;
  }

  public void setCustomerNumber2(String customerNumber2) {
    this.customerNumber2 = customerNumber2;
  }

  public String getCntryCd1() {
    return cntryCd1;
  }

  public void setCntryCd1(String cntryCd1) {
    this.cntryCd1 = cntryCd1;
  }

  public String getCustomerNumber1() {
    return customerNumber1;
  }

  public void setCustomerNumber1(String customerNumber1) {
    this.customerNumber1 = customerNumber1;
  }

  public int getAddrNo() {
    return addrNo;
  }

  public void setAddrNo(int addrNo) {
    this.addrNo = addrNo;
  }

  /*
   * public String getAddrUse2() { return addrUse2; }
   * 
   * public void setAddrUse2(String addrUse2) { this.addrUse2 = addrUse2; }
   */
}