/*
This file was automatically generated by the EntityCreator engine on Thu Aug 16 11:17:38 SGT 2018.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.cio.cmr.request.util.legacy.LegacyXmlTag;

/**
 * The persistent class for the CMRTCUST database table.
 * 
 * @author JeffZAMORA
 */
@Entity
@Table(
    name = "CMRTCUST",
    schema = "CMRDB2D")
public class CmrtCust extends BaseEntity<CmrtCustPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private CmrtCustPK id;

  @Override
  public CmrtCustPK getId() {
    return id;
  }

  @Override
  public void setId(CmrtCustPK id) {
    this.id = id;
  }

  /**
   * Real Country code
   */
  @Column(
      name = "REALCTY")
  private String realCtyCd;

  /**
   * A-active CN/C-cancelled
   */
  @Column(
      name = "STATUS")
  @LegacyXmlTag("Status")
  private String status;

  /**
   * CUSTOMER NAME ABBREVIATED
   */
  @Column(
      name = "NCUXB")
  @LegacyXmlTag("CompanyName")
  private String abbrevNm;

  /**
   * Abbreviated Location
   */
  @Column(
      name = "LCUXB")
  @LegacyXmlTag("AbbreviatedLocation")
  private String abbrevLocn;

  /**
   * Location Number
   */
  @Column(
      name = "RLCXB")
  @LegacyXmlTag("LocationNumber")
  private String locNo;

  /**
   * DC Repeat Agreement
   */
  @Column(
      name = "CAGXB")
  @LegacyXmlTag("RepeatAgreement")
  private String dcRepeatAgreement;

  /**
   * CE division
   */
  @Column(
      name = "CCEDA")
  @LegacyXmlTag("CEdivision")
  private String ceDivision;

  /**
   * Alliance Type ABBREVIATED
   */
  @Column(
      name = "CCOXA")
  @LegacyXmlTag("AllianceType")
  private String abbrevAllianceType;

  /**
   * Currency Code
   */
  @Column(
      name = "CCRXA")
  @LegacyXmlTag("CurrencyCode")
  private String currencyCd;

  /**
   * Education Allowance
   */
  @Column(
      name = "CEAXC")
  @LegacyXmlTag("EducationAllowance")
  private String educAllowance;

  /**
   * Leasing Company ind.
   */
  @Column(
      name = "CIEDC")
  @LegacyXmlTag("LeasingCompany")
  private String leasingInd;

  /**
   * AUTHORISED REMARKETER IND
   */
  @Column(
      name = "CIEXJ")
  @LegacyXmlTag("ARemark")
  private String authRemarketerInd;

  /**
   * Economic Code
   */
  @Column(
      name = "CIYXB")
  @LegacyXmlTag("EconomicCd")
  private String economicCd;

  /**
   * IMS Code
   */
  @Column(
      name = "IMS")
  @LegacyXmlTag("IMS")
  private String imsCd;

  /**
   * Language Code
   */
  @Column(
      name = "CLGXA")
  @LegacyXmlTag("LangCode")
  private String langCd;

  /**
   * DEPARTMENT CODE
   */
  @Column(
      name = "CLGXC")
  @LegacyXmlTag("DepartmentNumber")
  private String deptCd;

  /**
   * OVERSEAS TERRITORY
   */
  @Column(
      name = "CLGXD")
  @LegacyXmlTag("OverseasTerritory")
  private String overseasTerritory;

  /**
   * Marketing Responsibility Cd
   */
  @Column(
      name = "CMKDA")
  @LegacyXmlTag("MarketingResponseCode")
  private String mrcCd;

  /**
   * Mode Of Payment/CoF
   */
  @Column(
      name = "CPMXA")
  @LegacyXmlTag("ModeOfPayment")
  private String modeOfPayment;

  /**
   * ISU
   */
  @Column(
      name = "CRGAA")
  @LegacyXmlTag("ISU")
  private String isuCd;

  /**
   * CREDIT CODE
   */
  @Column(
      name = "CRDXA")
  @LegacyXmlTag("CreditCode")
  private String creditCd;

  /**
   * Tax Code
   */
  @Column(
      name = "CTXXA")
  @LegacyXmlTag(
      tags = { "TaxCode", "SpecialTaxCd" })
  private String taxCd;

  /**
   * BRANCH OFFICE NB ENGINEERING
   */
  @Column(
      name = "CEBO")
  @LegacyXmlTag("DPCEBO")
  private String ceBo;

  /**
   * BRANCH OFFICE NB INSTALLING
   */
  @Column(
      name = "SBO")
  @LegacyXmlTag("SBO")
  private String sbo;

  /**
   * BRANCH OFFICE NB SELLING
   */
  @Column(
      name = "IBO")
  @LegacyXmlTag("IBO")
  private String ibo;

  /**
   * SALESMAN NUMBER
   */
  @Column(
      name = "REMXA")
  @LegacyXmlTag("SR")
  private String salesRepNo;

  /**
   * SALES GROUP REPRESENTATIVE
   */
  @Column(
      name = "REMXD")
  @LegacyXmlTag("SRGroup")
  private String salesGroupRep;

  /**
   * ENTERPRISE NUMBER
   */
  @Column(
      name = "RENXA")
  @LegacyXmlTag("EnterpriseNo")
  private String enterpriseNo;

  /**
   * Bank Account Number
   */
  @Column(
      name = "RABXA")
  @LegacyXmlTag("BankAccountNo")
  private String bankAcctNo;

  /**
   * Bank Branch Number
   */
  @Column(
      name = "RBBXA")
  @LegacyXmlTag("BankBranchNo")
  private String bankBranchNo;

  /**
   * Bank Number
   */
  @Column(
      name = "RBKXA")
  @LegacyXmlTag("BankNumber")
  private String bankNo;

  /**
   * Collection Code
   */
  @Column(
      name = "CCLXA")
  @LegacyXmlTag("CollectionCode")
  private String collectionCd;

  /**
   * Mailing Condition
   */
  @Column(
      name = "CMLXA")
  @LegacyXmlTag("MailingCondition")
  private String mailingCond;

  /**
   * District Code
   */
  @Column(
      name = "CRGAC")
  @LegacyXmlTag("DistrictCode")
  private String districtCd;

  /**
   * ACCT ADMIN.BRANCH OFFICE
   */
  @Column(
      name = "RACBO")
  @LegacyXmlTag("AccAdBo")
  private String accAdminBo;

  /**
   * Type of Customer
   */
  @Column(
      name = "CCUAI")
  @LegacyXmlTag("CustomerType")
  private String custType;

  /**
   * Embargo Code
   */
  @Column(
      name = "CEMXA")
  @LegacyXmlTag("EmbargoCode")
  private String embargoCd;

  /**
   * ISIC
   */
  @Column(
      name = "CIYXA")
  @LegacyXmlTag("ISIC")
  private String isicCd;

  /**
   * INAC
   */
  @Column(
      name = "RAIXA")
  @LegacyXmlTag("INAC")
  private String inacCd;

  /**
   * telephone number or VAT
   */
  @Column(
      name = "RTPNO")
  @LegacyXmlTag("PhoneOrVat")
  private String telNoOrVat;

  /**
   * date CN has been created
   */
  @Column(
      name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  /**
   * date CN has been updated
   */
  @Column(
      name = "UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateTs;

  /**
   * date status has been updated
   */
  @Column(
      name = "UPDSTATUS_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updStatusTs;

  /**
   * VAT
   */
  @Column(
      name = "VAT")
  @LegacyXmlTag("VAT")
  private String vat;
  
  /**
   * RLAXA
   */
  @Column(
      name = "RLAXA")
  private String leadingAccNo;


  /**
   * QUBXD
   */
  @Column(
      name = "QUBXD")
  private String invoiceCpyReqd;

  
  public String getInvoiceCpyReqd() {
    return invoiceCpyReqd;
  }

  public void setInvoiceCpyReqd(String invoiceCpyReqd) {
    this.invoiceCpyReqd = invoiceCpyReqd;
  }

  public String getRealCtyCd() {
    return realCtyCd;
  }

  public void setRealCtyCd(String realCtyCd) {
    this.realCtyCd = realCtyCd;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getAbbrevNm() {
    return abbrevNm;
  }

  public void setAbbrevNm(String abbrevNm) {
    this.abbrevNm = abbrevNm;
  }

  public String getAbbrevLocn() {
    return abbrevLocn;
  }

  public void setAbbrevLocn(String abbrevLocn) {
    this.abbrevLocn = abbrevLocn;
  }

  public String getLocNo() {
    return locNo;
  }

  public void setLocNo(String locNo) {
    this.locNo = locNo;
  }

  public String getDcRepeatAgreement() {
    return dcRepeatAgreement;
  }

  public void setDcRepeatAgreement(String dcRepeatAgreement) {
    this.dcRepeatAgreement = dcRepeatAgreement;
  }

  public String getCeDivision() {
    return ceDivision;
  }

  public void setCeDivision(String ceDivision) {
    this.ceDivision = ceDivision;
  }

  public String getAbbrevAllianceType() {
    return abbrevAllianceType;
  }

  public void setAbbrevAllianceType(String abbrevAllianceType) {
    this.abbrevAllianceType = abbrevAllianceType;
  }

  public String getCurrencyCd() {
    return currencyCd;
  }

  public void setCurrencyCd(String currencyCd) {
    this.currencyCd = currencyCd;
  }

  public String getEducAllowance() {
    return educAllowance;
  }

  public void setEducAllowance(String educAllowance) {
    this.educAllowance = educAllowance;
  }

  public String getLeasingInd() {
    return leasingInd;
  }

  public void setLeasingInd(String leasingInd) {
    this.leasingInd = leasingInd;
  }

  public String getAuthRemarketerInd() {
    return authRemarketerInd;
  }

  public void setAuthRemarketerInd(String authRemarketerInd) {
    this.authRemarketerInd = authRemarketerInd;
  }

  public String getEconomicCd() {
    return economicCd;
  }

  public void setEconomicCd(String economicCd) {
    this.economicCd = economicCd;
  }

  public String getImsCd() {
    return imsCd;
  }

  public void setImsCd(String imsCd) {
    this.imsCd = imsCd;
  }

  public String getLangCd() {
    return langCd;
  }

  public void setLangCd(String langCd) {
    this.langCd = langCd;
  }

  public String getDeptCd() {
    return deptCd;
  }

  public void setDeptCd(String deptCd) {
    this.deptCd = deptCd;
  }

  public String getOverseasTerritory() {
    return overseasTerritory;
  }

  public void setOverseasTerritory(String overseasTerritory) {
    this.overseasTerritory = overseasTerritory;
  }

  public String getMrcCd() {
    return mrcCd;
  }

  public void setMrcCd(String mrcCd) {
    this.mrcCd = mrcCd;
  }

  public String getModeOfPayment() {
    return modeOfPayment;
  }

  public void setModeOfPayment(String modeOfPayment) {
    this.modeOfPayment = modeOfPayment;
  }

  public String getIsuCd() {
    return isuCd;
  }

  public void setIsuCd(String isuCd) {
    this.isuCd = isuCd;
  }

  public String getCreditCd() {
    return creditCd;
  }

  public void setCreditCd(String creditCd) {
    this.creditCd = creditCd;
  }

  public String getTaxCd() {
    return taxCd;
  }

  public void setTaxCd(String taxCd) {
    this.taxCd = taxCd;
  }

  public String getCeBo() {
    return ceBo;
  }

  public void setCeBo(String ceBo) {
    this.ceBo = ceBo;
  }

  public String getSbo() {
    return sbo;
  }

  public void setSbo(String sbo) {
    this.sbo = sbo;
  }

  public String getIbo() {
    return ibo;
  }

  public void setIbo(String ibo) {
    this.ibo = ibo;
  }

  public String getSalesRepNo() {
    return salesRepNo;
  }

  public void setSalesRepNo(String salesRepNo) {
    this.salesRepNo = salesRepNo;
  }

  public String getEnterpriseNo() {
    return enterpriseNo;
  }

  public void setEnterpriseNo(String enterpriseNo) {
    this.enterpriseNo = enterpriseNo;
  }

  public String getBankAcctNo() {
    return bankAcctNo;
  }

  public void setBankAcctNo(String bankAcctNo) {
    this.bankAcctNo = bankAcctNo;
  }

  public String getBankBranchNo() {
    return bankBranchNo;
  }

  public void setBankBranchNo(String bankBranchNo) {
    this.bankBranchNo = bankBranchNo;
  }

  public String getBankNo() {
    return bankNo;
  }

  public void setBankNo(String bankNo) {
    this.bankNo = bankNo;
  }

  public String getCollectionCd() {
    return collectionCd;
  }

  public void setCollectionCd(String collectionCd) {
    this.collectionCd = collectionCd;
  }

  public String getMailingCond() {
    return mailingCond;
  }

  public void setMailingCond(String mailingCond) {
    this.mailingCond = mailingCond;
  }

  public String getDistrictCd() {
    return districtCd;
  }

  public void setDistrictCd(String districtCd) {
    this.districtCd = districtCd;
  }

  public String getAccAdminBo() {
    return accAdminBo;
  }

  public void setAccAdminBo(String accAdminBo) {
    this.accAdminBo = accAdminBo;
  }

  public String getCustType() {
    return custType;
  }

  public void setCustType(String custType) {
    this.custType = custType;
  }

  public String getEmbargoCd() {
    return embargoCd;
  }

  public void setEmbargoCd(String embargoCd) {
    this.embargoCd = embargoCd;
  }

  public String getIsicCd() {
    return isicCd;
  }

  public void setIsicCd(String isicCd) {
    this.isicCd = isicCd;
  }

  public String getInacCd() {
    return inacCd;
  }

  public void setInacCd(String inacCd) {
    this.inacCd = inacCd;
  }

  public String getTelNoOrVat() {
    return telNoOrVat;
  }

  public void setTelNoOrVat(String telNoOrVat) {
    this.telNoOrVat = telNoOrVat;
  }

  public Date getCreateTs() {
    return createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public Date getUpdateTs() {
    return updateTs;
  }

  public void setUpdateTs(Date updateTs) {
    this.updateTs = updateTs;
  }

  public Date getUpdStatusTs() {
    return updStatusTs;
  }

  public void setUpdStatusTs(Date updStatusTs) {
    this.updStatusTs = updStatusTs;
  }

  public String getVat() {
    return vat;
  }

  public void setVat(String vat) {
    this.vat = vat;
  }

  public String getSalesGroupRep() {
    return salesGroupRep;
  }

  public void setSalesGroupRep(String salesGroupRep) {
    this.salesGroupRep = salesGroupRep;
  }

  public String getLeadingAccNo() {
    return leadingAccNo;
  }

  public void setLeadingAccNo(String leadingAccNo) {
    this.leadingAccNo = leadingAccNo;
  }

}