/*
This file was automatically generated by the EntityCreator engine on Thu Aug 16 11:17:36 SGT 2018.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.StringUtils;

import com.ibm.cio.cmr.request.util.legacy.LegacyXmlTag;

/**
 * The primary key class for the CMRTADDR database table.
 * 
 * @author JeffZAMORA
 */
@Embeddable
public class CmrtAddrPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  /**
   * SOF COUNTRY NAME
   */
  @Column(name = "RCYAA")
  private String sofCntryCode;

  /**
   * CUSTOMER NUMBER
   */
  @Column(name = "RCUXA")
  private String customerNo;

  /**
   * ADDRESS NUMBER/SEQUENCE
   */
  @Column(name = "ADDRNO")
  @LegacyXmlTag("AddressNumber")
  // Story 1698123
  private String addrNo;

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof CmrtAddrPK)) {
      return false;
    }
    CmrtAddrPK o = (CmrtAddrPK) other;
    return this.sofCntryCode.equals(o.sofCntryCode) && this.customerNo.equals(o.customerNo) && this.addrNo.equals(o.addrNo);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.sofCntryCode != null ? this.sofCntryCode.hashCode() : 0);
    hash = hash * prime + (this.customerNo != null ? this.customerNo.hashCode() : 0);
    hash = hash * prime + (this.addrNo != null ? this.addrNo.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.sofCntryCode) && !StringUtils.isEmpty(this.customerNo) && !StringUtils.isEmpty(this.addrNo);

  }

  public String getSofCntryCode() {
    return sofCntryCode;
  }

  public void setSofCntryCode(String sofCntryCode) {
    this.sofCntryCode = sofCntryCode;
  }

  public String getCustomerNo() {
    return customerNo;
  }

  public void setCustomerNo(String customerNo) {
    this.customerNo = customerNo;
  }

  public String getAddrNo() {
    return addrNo;
  }

  public void setAddrNo(String addrNo) {
    this.addrNo = addrNo;
  }
}