/*
This file was automatically generated by the EntityCreator engine on Sun Jul 02 21:42:01 CST 2017.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the CNTRY_GEO_DEF database table.
 * 
 * @author 134944
 */
@Embeddable
public class CntryGeoDefPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "GEO_CD")
  private String geoCd;

  @Column(name = "CMR_ISSUING_CNTRY")
  private String cmrIssuingCntry;

  public String getGeoCd(){
    return this.geoCd;
  }

  public void setGeoCd(String geoCd){
    this.geoCd = geoCd;
  }


  public String getCmrIssuingCntry(){
    return this.cmrIssuingCntry;
  }

  public void setCmrIssuingCntry(String cmrIssuingCntry){
    this.cmrIssuingCntry = cmrIssuingCntry;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof CntryGeoDefPK)) {
      return false;
    }
    CntryGeoDefPK o = (CntryGeoDefPK) other;
    return this.geoCd.equals(o.geoCd) && this.cmrIssuingCntry.equals(o.cmrIssuingCntry);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.geoCd != null ? this.geoCd.hashCode() : 0);
    hash = hash * prime + (this.cmrIssuingCntry != null ? this.cmrIssuingCntry.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.geoCd) && !StringUtils.isEmpty(this.cmrIssuingCntry);

  }
}