/*
This file was automatically generated by the EntityCreator engine on Thu Apr 26 19:06:51 SGT 2018.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the COLLECTOR_NAME_NO database table.
 * 
 * @author DennisNATAD
 */
@Entity
@Table(name = "COLLECTOR_NAME_NO", schema = "CREQCMR")
public class CollectorNameNo extends BaseEntity<CollectorNameNoPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private CollectorNameNoPK id;

  public CollectorNameNoPK getId() {
    return id;
  }

  public void setId(CollectorNameNoPK id) {
    this.id = id;
  }
  
  @Column(name = "COLLECTOR_NAME")
  private String collectorName;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(name = "CREATE_BY_ID")
  private String createById;

  @Column(name = "UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateTs;

  @Column(name = "UPDATE_BY_ID")
  private String updateById;

  public String getCollectorName(){
    return this.collectorName;
  }

  public void setCollectorName(String collectorName){
    this.collectorName = collectorName;
  }


  public Date getCreateTs(){
    return this.createTs;
  }

  public void setCreateTs(Date createTs){
    this.createTs = createTs;
  }


  public String getCreateById(){
    return this.createById;
  }

  public void setCreateById(String createById){
    this.createById = createById;
  }


  public Date getUpdateTs(){
    return this.updateTs;
  }

  public void setUpdateTs(Date updateTs){
    this.updateTs = updateTs;
  }


  public String getUpdateById(){
    return this.updateById;
  }

  public void setUpdateById(String updateById){
    this.updateById = updateById;
  }




}