/*
This file was automatically generated by the EntityCreator engine on Fri Aug 11 17:41:43 CST 2017.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the CUST_SCENARIOS database table.
 * 
 * @author Jeffrey Zamora
 */
@Embeddable
public class CustScenariosPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "LOC_CD")
  private String locCd;

  @Column(name = "CUST_TYP")
  private String custTyp;

  @Column(name = "CUST_SUB_TYP")
  private String custSubTyp;

  @Column(name = "FIELD_ID")
  private String fieldId;

  @Column(name = "ADDR_TYP")
  private String addrTyp;

  @Column(name = "SEQ_NO")
  private int seqNo;

  public String getLocCd(){
    return this.locCd;
  }

  public void setLocCd(String locCd){
    this.locCd = locCd;
  }


  public String getCustTyp(){
    return this.custTyp;
  }

  public void setCustTyp(String custTyp){
    this.custTyp = custTyp;
  }


  public String getCustSubTyp(){
    return this.custSubTyp;
  }

  public void setCustSubTyp(String custSubTyp){
    this.custSubTyp = custSubTyp;
  }


  public String getFieldId(){
    return this.fieldId;
  }

  public void setFieldId(String fieldId){
    this.fieldId = fieldId;
  }


  public String getAddrTyp(){
    return this.addrTyp;
  }

  public void setAddrTyp(String addrTyp){
    this.addrTyp = addrTyp;
  }


  public int getSeqNo(){
    return this.seqNo;
  }

  public void setSeqNo(int seqNo){
    this.seqNo = seqNo;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof CustScenariosPK)) {
      return false;
    }
    CustScenariosPK o = (CustScenariosPK) other;
    return this.locCd.equals(o.locCd) && this.custTyp.equals(o.custTyp) && this.custSubTyp.equals(o.custSubTyp) && this.fieldId.equals(o.fieldId) && this.addrTyp.equals(o.addrTyp) && this.seqNo == o.seqNo;


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.locCd != null ? this.locCd.hashCode() : 0);
    hash = hash * prime + (this.custTyp != null ? this.custTyp.hashCode() : 0);
    hash = hash * prime + (this.custSubTyp != null ? this.custSubTyp.hashCode() : 0);
    hash = hash * prime + (this.fieldId != null ? this.fieldId.hashCode() : 0);
    hash = hash * prime + (this.addrTyp != null ? this.addrTyp.hashCode() : 0);
    hash = hash * prime + this.seqNo;


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.locCd) && !StringUtils.isEmpty(this.custTyp) && !StringUtils.isEmpty(this.custSubTyp) && !StringUtils.isEmpty(this.fieldId) && !StringUtils.isEmpty(this.addrTyp) && this.seqNo > 0;

  }
}