/*
This file was automatically generated by the EntityCreator engine on Mon Oct 05 22:10:13 CST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the DATA_RDC database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(
    name = "DATA_RDC",
    schema = "CREQCMR")
public class DataRdc extends BaseEntity<DataPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private DataPK id;

  @Override
  public DataPK getId() {
    return id;
  }

  @Override
  public void setId(DataPK id) {
    this.id = id;
  }

  @Column(
      name = "ABBREV_NM")
  private String abbrevNm;

  private String affiliate;

  @Column(
      name = "BP_REL_TYPE")
  private String bpRelType;

  @Column(
      name = "CAP_IND")
  private String capInd;

  @Column(
      name = "CLIENT_TIER")
  private String clientTier;

  @Column(
      name = "CMR_ISSUING_CNTRY")
  private String cmrIssuingCntry;

  @Column(
      name = "CMR_NO")
  private String cmrNo;

  @Column(
      name = "CMR_OWNER")
  private String cmrOwner;

  private String company;

  @Column(
      name = "CUST_CLASS")
  private String custClass;

  private String enterprise;

  @Column(
      name = "CUST_PREF_LANG")
  private String custPrefLang;

  @Column(
      name = "INAC_CD")
  private String inacCd;

  @Column(
      name = "INAC_TYPE")
  private String inacType;

  @Column(
      name = "ISU_CD")
  private String isuCd;

  @Column(
      name = "TAX_CD1")
  private String taxCd1;

  @Column(
      name = "TAX_CD2")
  private String taxCd2;

  @Column(
      name = "TAX_CD3")
  private String taxCd3;

  @Column(
      name = "MEM_LVL")
  private String memLvl;

  private String ppsceid;

  @Column(
      name = "SEARCH_TERM")
  private String searchTerm;

  @Column(
      name = "SENSITIVE_FLAG")
  private String sensitiveFlag;

  @Column(
      name = "ISIC_CD")
  private String isicCd;

  @Column(
      name = "SITE_PARTY_ID")
  private String sitePartyId;

  @Column(
      name = "SUB_INDUSTRY_CD")
  private String subIndustryCd;

  private String vat;

  @Column(
      name = "COV_ID")
  private String covId;

  @Column(
      name = "BG_ID")
  private String bgId;

  @Column(
      name = "GBG_ID")
  private String gbgId;

  @Column(
      name = "GEO_LOC_CD")
  private String geoLocCd;

  @Column(
      name = "DUNS_NO")
  private String dunsNo;

  @Column(
      name = "COV_DESC")
  private String covDesc;

  @Column(
      name = "BG_DESC")
  private String bgDesc;

  @Column(
      name = "GBG_DESC")
  private String gbgDesc;

  @Column(
      name = "GEO_LOC_DESC")
  private String geoLocDesc;

  @Column(
      name = "BG_RULE_ID")
  private String bgRuleId;

  @Column(
      name = "ORD_BLK")
  private String ordBlk;

  @Column(
      name = "RESTRICT_IND")
  private String restrictInd;

  @Column(
      name = "RESTRICT_TO")
  private String restrictTo;

  @Column(
      name = "OEM_IND")
  private String oemInd;

  @Column(
      name = "BP_ACCT_TYP")
  private String bpAcctTyp;

  @Column(
      name = "MKTG_DEPT")
  private String mktgDept;

  @Column(
      name = "MTKG_AR_DEPT")
  private String mtkgArDept;

  @Column(
      name = "PCC_MKTG_DEPT")
  private String pccMktgDept;

  @Column(
      name = "PCC_AR_DEPT")
  private String pccArDept;

  @Column(
      name = "SVC_AR_OFFICE")
  private String svcArOffice;

  @Column(
      name = "OUT_CITY_LIMIT")
  private String outCityLimit;

  @Column(
      name = "CSO_SITE")
  private String csoSite;

  @Column(
      name = "FED_SITE_IND")
  private String fedSiteInd;

  @Column(
      name = "SIZE_CD")
  private String sizeCd;

  @Column(
      name = "SVC_TERRITORY_ZONE")
  private String svcTerritoryZone;

  @Column(
      name = "MISC_BILL_CD")
  private String miscBillCd;

  @Column(
      name = "BP_NAME")
  private String bpName;

  @Column(
      name = "ICC_TAX_CLASS")
  private String iccTaxClass;

  @Column(
      name = "ICC_TAX_EXEMPT_STATUS")
  private String iccTaxExemptStatus;

  @Column(
      name = "NON_IBM_COMPANY_IND")
  private String nonIbmCompanyInd;

  private String div;

  private String dept;

  private String func;

  @Column(
      name = "\"USER\"")
  private String user;

  private String loc;

  @Column(
      name = "COLL_BO_ID")
  private String collBoId;

  @Column(
      name = "COLLECTOR_NO")
  private String collectorNo;

  @Column(
      name = "MARKETING_CHNL_INDC_VALUE")
  private String marketingChnlIndcValue;

  @Column(
      name = "REPRESENTATIVE_TEAM_MEMBER_NO")
  private String representativeTeamMemberNo;

  @Column(
      name = "CONTACT_NAME1")
  private String contactName1;

  @Column(
      name = "CONTACT_NAME2")
  private String contactName2;

  @Column(
      name = "CONTACT_NAME3")
  private String contactName3;

  private String phone1;

  private String phone2;

  private String phone3;

  private String email1;

  private String email2;

  private String email3;

  @Column(
      name = "BUSN_TYP")
  private String busnType;

  @Column(
      name = "ICMS_IND")
  private String icmsInd;

  @Column(
      name = "MRC_CD")
  private String mrcCd;

  @Column(
      name = "SALES_BO_CD")
  private String salesBusOffCd;

  @Column(
      name = "VAT_EXEMPT")
  private String vatExempt;

  @Column(
      name = "VAT_IND")
  private String vatInd;

  @Column(
      name = "REP_TEAM_MEMBER_NO")
  private String repTeamMemberNo;

  @Column(
      name = "SPECIAL_TAX_CD")
  private String specialTaxCd;

  @Column(
      name = "TAX_EXEMPT_STATUS_1")
  private String taxExempt1;

  public String getTaxExempt1() {
    return taxExempt1;
  }

  public void setTaxExempt1(String taxExempt1) {
    this.taxExempt1 = taxExempt1;
  }

  @Column(
      name = "TAX_EXEMPT_STATUS_2")
  private String taxExempt2;

  @Column(
      name = "TAX_EXEMPT_STATUS_3")
  private String taxExempt3;

  public String getTaxExempt2() {
    return taxExempt2;
  }

  public void setTaxExempt2(String taxExempt2) {
    this.taxExempt2 = taxExempt2;
  }

  public String getTaxExempt3() {
    return taxExempt3;
  }

  public void setTaxExempt3(String taxExempt3) {
    this.taxExempt3 = taxExempt3;
  }

  @Column(
      name = "ABBREV_LOCN")
  private String abbrevLocn;

  @Column(
      name = "COLLECTION_CD")
  private String collectionCd;

  @Column(
      name = "ECONOMIC_CD")
  private String economicCd;

  @Column(
      name = "ENGINEERING_BO")
  private String engineeringBo;

  @Column(
      name = "MAILING_COND")
  private String mailingCondition;

  @Column(
      name = "AP_CUST_CLUSTER_ID")
  private String apCustClusterId;

  @Column(
      name = "BP_SALES_REP_NO")
  private String bpSalesRepNo;

  @Column(
      name = "EMBARGO_CD")
  private String embargoCd;

  @Column(
      name = "AGREEMENT_SIGN_DATE")
  private String agreementSignDate;

  @Column(
      name = "CIS_SERVICE_CUST_INDC")
  private String cisServiceCustIndc;

  @Column(
      name = "COMMERCIAL_FINANCED")
  private String commercialFinanced;

  @Column(
      name = "INSTALL_BRANCH_OFF")
  private String installBranchOff;

  @Column(
      name = "LEGACY_CURRENCY_CD")
  private String legacyCurrencyCd;

  @Column(
      name = "CURRENCY_CD")
  private String currencyCd;

  @Column(
      name = "CREDIT_CD")
  private String creditCd;

  @Column(
      name = "DUP_SALES_REP_NO")
  private String dupSalesRepNo;

  @Column(
      name = "DUP_ENTERPRISE_NO")
  private String dupEnterpriseNo;

  @Column(
      name = "DUP_SALES_BO_CD")
  private String dupSalesBoCd;

  @Column(
      name = "DUP_ISU_CD")
  private String dupIsuCd;

  @Column(
      name = "DUP_CLIENT_TIER_CD")
  private String dupClientTierCd;

  @Column(
      name = "IDENT_CLIENT")
  private String identClient;

  @Column(
      name = "MODE_OF_PAYMENT")
  private String modeOfPayment;

  @Column(
      name = "GOVERNMENT")
  private String govType;

  @Column(
      name = "ISBU_CD")
  private String isbuCd;

  // @Column(name = "ESTAB_NO")
  // private String estabNo;

  @Column(
      name = "JSIC_CD")
  private String jsicCd;

  @Column(
      name = "TIER_2")
  private String tier2;

  @Column(
      name = "CS_BO")
  private String csBo;

  @Column(
      name = "CS_DIV")
  private String csDiv;

  @Column(
      name = "IIN_IND")
  private String iinInd;

  @Column(
      name = "VALUE_ADD_REM")
  private String valueAddRem;

  @Column(
      name = "SI_IND")
  private String siInd;

  @Column(
      name = "CRS_CD")
  private String crsCd;

  @Column(
      name = "BILLING_PROC_CD")
  private String billingProcCd;

  @Column(
      name = "CHANNEL_CD")
  private String channelCd;

  @Column(
      name = "INVOICE_SPLIT_CD")
  private String invoiceSplitCd;

  @Column(
      name = "BILL_TO_CUST_NO")
  private String billToCustNo;

  @Column(
      name = "CREDIT_TO_CUST_NO")
  private String creditToCustNo;

  // @Column(name = "GOV_OFFICE_DIV_CD")
  // private String govOfficeDivCd;
  //
  // @Column(name = "DEALER_NO")
  // private String dealerNo;

  @Column(
      name = "SO_PRJ_CD")
  private String soProjectCd;

  @Column(
      name = "PROD_TYPE")
  private String prodType;

  @Column(
      name = "ADMIN_DEPT_CD")
  private String adminDeptCd;

  @Column(
      name = "ADMIN_DEPT_LN")
  private String adminDeptLine;

  @Column(
      name = "CHARGE_CD")
  private String chargeCd;

  @Column(
      name = "OUTSOURCING_SERV")
  private String outsourcingService;

  @Column(
      name = "CREDIT_BP")
  private String creditBp;

  @Column(
      name = "ZSERIES_SW")
  private String zseriesSw;

  @Column(
      name = "REQUEST_DUE_DATE")
  private Date requestDueDate;

  @Column(
      name = "LEASING_COMP_INDC")
  private String leasingCompanyIndc;

  @Column(
      name = "ORG_NO")
  private String orgNo;

  @Column(
      name = "SALES_TEAM_CD")
  private String salesTeamCd;

  @Column(
      name = "EDUC_ALLOW_CD")
  private String educAllowCd;

  @Column(
      name = "NATIONAL_CUS_IND")
  private String nationalCusId;

  // Italy Legacy Fields
  @Column(
      name = "HW_SVCS_REP_TEAM_NO")
  private String hwSvcsRepTeamNo;

  @Column(
      name = "CROS_SUB_TYP")
  private String crosSubTyp;

  @Column(
      name = "US_SICMEN")
  private String usSicmen;

  private String military;

  @Column(
      name = "CUST_ACCT_TYP")
  private String custAcctType;

  @Column(
      name = "CUST_INVOICE_COPIES")
  private String cusInvoiceCopies;

  @Column(
      name = "LOCN_NO")
  private String locationNumber;

  @Column(
      name = "TAX_PAYER_CUST_CD")
  private String taxPayerCustCd;

  @Column(
      name = "MEXICO_BILLING_NAME")
  private String mexicoBillingName;

  public String getMexicoBillingName() {
    return mexicoBillingName;
  }

  public void setMexicoBillingName(String mexicoBillingName) {
    this.mexicoBillingName = mexicoBillingName;
  }

  public String getCusInvoiceCopies() {
    return cusInvoiceCopies;
  }

  public void setCusInvoiceCopies(String cusInvoiceCopies) {
    this.cusInvoiceCopies = cusInvoiceCopies;
  }

  public String getAbbrevNm() {
    return this.abbrevNm;
  }

  public void setAbbrevNm(String abbrevNm) {
    this.abbrevNm = abbrevNm;
  }

  public String getAffiliate() {
    return this.affiliate;
  }

  public void setAffiliate(String affiliate) {
    this.affiliate = affiliate;
  }

  public String getBpRelType() {
    return this.bpRelType;
  }

  public void setBpRelType(String bpRelType) {
    this.bpRelType = bpRelType;
  }

  public String getCapInd() {
    return this.capInd;
  }

  public void setCapInd(String capInd) {
    this.capInd = capInd;
  }

  public String getClientTier() {
    return this.clientTier;
  }

  public void setClientTier(String clientTier) {
    this.clientTier = clientTier;
  }

  public String getCmrIssuingCntry() {
    return this.cmrIssuingCntry;
  }

  public void setCmrIssuingCntry(String cmrIssuingCntry) {
    this.cmrIssuingCntry = cmrIssuingCntry;
  }

  public String getCmrNo() {
    return this.cmrNo;
  }

  public void setCmrNo(String cmrNo) {
    this.cmrNo = cmrNo;
  }

  public String getCmrOwner() {
    return this.cmrOwner;
  }

  public void setCmrOwner(String cmrOwner) {
    this.cmrOwner = cmrOwner;
  }

  public String getCompany() {
    return this.company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public String getCustClass() {
    return this.custClass;
  }

  public void setCustClass(String custClass) {
    this.custClass = custClass;
  }

  public String getEnterprise() {
    return this.enterprise;
  }

  public void setEnterprise(String enterprise) {
    this.enterprise = enterprise;
  }

  public String getCustPrefLang() {
    return this.custPrefLang;
  }

  public void setCustPrefLang(String custPrefLang) {
    this.custPrefLang = custPrefLang;
  }

  public String getInacCd() {
    return this.inacCd;
  }

  public void setInacCd(String inacCd) {
    this.inacCd = inacCd;
  }

  public String getInacType() {
    return this.inacType;
  }

  public void setInacType(String inacType) {
    this.inacType = inacType;
  }

  public String getIsuCd() {
    return this.isuCd;
  }

  public void setIsuCd(String isuCd) {
    this.isuCd = isuCd;
  }

  public String getTaxCd1() {
    return this.taxCd1;
  }

  public void setTaxCd1(String taxCd1) {
    this.taxCd1 = taxCd1;
  }

  public String getTaxCd2() {
    return this.taxCd2;
  }

  public void setTaxCd2(String taxCd2) {
    this.taxCd2 = taxCd2;
  }

  public String getMemLvl() {
    return this.memLvl;
  }

  public void setMemLvl(String memLvl) {
    this.memLvl = memLvl;
  }

  public String getPpsceid() {
    return this.ppsceid;
  }

  public void setPpsceid(String ppsceid) {
    this.ppsceid = ppsceid;
  }

  public String getSearchTerm() {
    return this.searchTerm;
  }

  public void setSearchTerm(String searchTerm) {
    this.searchTerm = searchTerm;
  }

  public String getSensitiveFlag() {
    return this.sensitiveFlag;
  }

  public void setSensitiveFlag(String sensitiveFlag) {
    this.sensitiveFlag = sensitiveFlag;
  }

  public String getIsicCd() {
    return this.isicCd;
  }

  public void setIsicCd(String isicCd) {
    this.isicCd = isicCd;
  }

  public String getSitePartyId() {
    return this.sitePartyId;
  }

  public void setSitePartyId(String sitePartyId) {
    this.sitePartyId = sitePartyId;
  }

  public String getSubIndustryCd() {
    return this.subIndustryCd;
  }

  public void setSubIndustryCd(String subIndustryCd) {
    this.subIndustryCd = subIndustryCd;
  }

  public String getVat() {
    return this.vat;
  }

  public void setVat(String vat) {
    this.vat = vat;
  }

  public String getVatInd() {
    return vatInd;
  }

  public void setVatInd(String vatInd) {
    this.vatInd = vatInd;
  }

  public String getCovId() {
    return this.covId;
  }

  public void setCovId(String covId) {
    this.covId = covId;
  }

  public String getBgId() {
    return this.bgId;
  }

  public void setBgId(String bgId) {
    this.bgId = bgId;
  }

  public String getGbgId() {
    return this.gbgId;
  }

  public void setGbgId(String gbgId) {
    this.gbgId = gbgId;
  }

  public String getGeoLocCd() {
    return this.geoLocCd;
  }

  public void setGeoLocCd(String geoLocCd) {
    this.geoLocCd = geoLocCd;
  }

  public String getDunsNo() {
    return this.dunsNo;
  }

  public void setDunsNo(String dunsNo) {
    this.dunsNo = dunsNo;
  }

  public String getCovDesc() {
    return this.covDesc;
  }

  public void setCovDesc(String covDesc) {
    this.covDesc = covDesc;
  }

  public String getBgDesc() {
    return this.bgDesc;
  }

  public void setBgDesc(String bgDesc) {
    this.bgDesc = bgDesc;
  }

  public String getGbgDesc() {
    return this.gbgDesc;
  }

  public void setGbgDesc(String gbgDesc) {
    this.gbgDesc = gbgDesc;
  }

  public String getGeoLocDesc() {
    return this.geoLocDesc;
  }

  public void setGeoLocDesc(String geoLocDesc) {
    this.geoLocDesc = geoLocDesc;
  }

  public String getBgRuleId() {
    return this.bgRuleId;
  }

  public void setBgRuleId(String bgRuleId) {
    this.bgRuleId = bgRuleId;
  }

  public String getOrdBlk() {
    return this.ordBlk;
  }

  public void setOrdBlk(String ordBlk) {
    this.ordBlk = ordBlk;
  }

  public String getRestrictInd() {
    return this.restrictInd;
  }

  public void setRestrictInd(String restrictInd) {
    this.restrictInd = restrictInd;
  }

  public String getRestrictTo() {
    return this.restrictTo;
  }

  public void setRestrictTo(String restrictTo) {
    this.restrictTo = restrictTo;
  }

  public String getOemInd() {
    return this.oemInd;
  }

  public void setOemInd(String oemInd) {
    this.oemInd = oemInd;
  }

  public String getBpAcctTyp() {
    return this.bpAcctTyp;
  }

  public void setBpAcctTyp(String bpAcctTyp) {
    this.bpAcctTyp = bpAcctTyp;
  }

  public String getMktgDept() {
    return this.mktgDept;
  }

  public void setMktgDept(String mktgDept) {
    this.mktgDept = mktgDept;
  }

  public String getMtkgArDept() {
    return this.mtkgArDept;
  }

  public void setMtkgArDept(String mtkgArDept) {
    this.mtkgArDept = mtkgArDept;
  }

  public String getPccMktgDept() {
    return this.pccMktgDept;
  }

  public void setPccMktgDept(String pccMktgDept) {
    this.pccMktgDept = pccMktgDept;
  }

  public String getPccArDept() {
    return this.pccArDept;
  }

  public void setPccArDept(String pccArDept) {
    this.pccArDept = pccArDept;
  }

  public String getSvcArOffice() {
    return this.svcArOffice;
  }

  public void setSvcArOffice(String svcArOffice) {
    this.svcArOffice = svcArOffice;
  }

  public String getOutCityLimit() {
    return this.outCityLimit;
  }

  public void setOutCityLimit(String outCityLimit) {
    this.outCityLimit = outCityLimit;
  }

  public String getCsoSite() {
    return this.csoSite;
  }

  public void setCsoSite(String csoSite) {
    this.csoSite = csoSite;
  }

  public String getFedSiteInd() {
    return this.fedSiteInd;
  }

  public void setFedSiteInd(String fedSiteInd) {
    this.fedSiteInd = fedSiteInd;
  }

  public String getSizeCd() {
    return this.sizeCd;
  }

  public void setSizeCd(String sizeCd) {
    this.sizeCd = sizeCd;
  }

  public String getSvcTerritoryZone() {
    return this.svcTerritoryZone;
  }

  public void setSvcTerritoryZone(String svcTerritoryZone) {
    this.svcTerritoryZone = svcTerritoryZone;
  }

  public String getMiscBillCd() {
    return this.miscBillCd;
  }

  public void setMiscBillCd(String miscBillCd) {
    this.miscBillCd = miscBillCd;
  }

  public String getBpName() {
    return this.bpName;
  }

  public void setBpName(String bpName) {
    this.bpName = bpName;
  }

  public String getIccTaxClass() {
    return this.iccTaxClass;
  }

  public void setIccTaxClass(String iccTaxClass) {
    this.iccTaxClass = iccTaxClass;
  }

  public String getIccTaxExemptStatus() {
    return this.iccTaxExemptStatus;
  }

  public void setIccTaxExemptStatus(String iccTaxExemptStatus) {
    this.iccTaxExemptStatus = iccTaxExemptStatus;
  }

  public String getNonIbmCompanyInd() {
    return this.nonIbmCompanyInd;
  }

  public void setNonIbmCompanyInd(String nonIbmCompanyInd) {
    this.nonIbmCompanyInd = nonIbmCompanyInd;
  }

  public String getDiv() {
    return this.div;
  }

  public void setDiv(String div) {
    this.div = div;
  }

  public String getDept() {
    return this.dept;
  }

  public void setDept(String dept) {
    this.dept = dept;
  }

  public String getFunc() {
    return this.func;
  }

  public void setFunc(String func) {
    this.func = func;
  }

  public String getUser() {
    return this.user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public String getLoc() {
    return this.loc;
  }

  public void setLoc(String loc) {
    this.loc = loc;
  }

  public String getCollBoId() {
    return this.collBoId;
  }

  public void setCollBoId(String collBoId) {
    this.collBoId = collBoId;
  }

  public String getCollectorNo() {
    return this.collectorNo;
  }

  public void setCollectorNo(String collectorNo) {
    this.collectorNo = collectorNo;
  }

  public String getMarketingChnlIndcValue() {
    return this.marketingChnlIndcValue;
  }

  public void setMarketingChnlIndcValue(String marketingChnlIndcValue) {
    this.marketingChnlIndcValue = marketingChnlIndcValue;
  }

  public String getRepresentativeTeamMemberNo() {
    return this.representativeTeamMemberNo;
  }

  public void setRepresentativeTeamMemberNo(String representativeTeamMemberNo) {
    this.representativeTeamMemberNo = representativeTeamMemberNo;
  }

  public String getContactName1() {
    return this.contactName1;
  }

  public void setContactName1(String contactName1) {
    this.contactName1 = contactName1;
  }

  public String getContactName2() {
    return this.contactName2;
  }

  public void setContactName2(String contactName2) {
    this.contactName2 = contactName2;
  }

  public String getContactName3() {
    return this.contactName3;
  }

  public void setContactName3(String contactName3) {
    this.contactName3 = contactName3;
  }

  public String getPhone1() {
    return this.phone1;
  }

  public void setPhone1(String phone1) {
    this.phone1 = phone1;
  }

  public String getPhone2() {
    return this.phone2;
  }

  public void setPhone2(String phone2) {
    this.phone2 = phone2;
  }

  public String getPhone3() {
    return this.phone3;
  }

  public void setPhone3(String phone3) {
    this.phone3 = phone3;
  }

  public String getEmail1() {
    return this.email1;
  }

  public void setEmail1(String email1) {
    this.email1 = email1;
  }

  public String getEmail2() {
    return this.email2;
  }

  public void setEmail2(String email2) {
    this.email2 = email2;
  }

  public String getEmail3() {
    return this.email3;
  }

  public void setEmail3(String email3) {
    this.email3 = email3;
  }

  public String getBusnType() {
    return this.busnType;
  }

  public void setBusnType(String busnType) {
    this.busnType = busnType;
  }

  public String getIcmsInd() {
    return this.icmsInd;
  }

  public void setIcmsInd(String icmsInd) {
    this.icmsInd = icmsInd;
  }

  public String getMrcCd() {
    return this.mrcCd;
  }

  public void setMrcCd(String mrcCd) {
    this.mrcCd = mrcCd;
  }

  public String getSalesBusOffCd() {
    return salesBusOffCd;
  }

  public void setSalesBusOffCd(String salesBusOffCd) {
    this.salesBusOffCd = salesBusOffCd;
  }

  public String getVatExempt() {
    return vatExempt;
  }

  public void setVatExempt(String vatExempt) {
    this.vatExempt = vatExempt;
  }

  public String getRepTeamMemberNo() {
    return repTeamMemberNo;
  }

  public void setRepTeamMemberNo(String repTeamMemberNo) {
    this.repTeamMemberNo = repTeamMemberNo;
  }

  public String getSpecialTaxCd() {
    return specialTaxCd;
  }

  public void setSpecialTaxCd(String specialTaxCd) {
    this.specialTaxCd = specialTaxCd;
  }

  public String getAbbrevLocn() {
    return abbrevLocn;
  }

  public void setAbbrevLocn(String abbrevLocn) {
    this.abbrevLocn = abbrevLocn;
  }

  public String getCollectionCd() {
    return collectionCd;
  }

  public void setCollectionCd(String collectionCd) {
    this.collectionCd = collectionCd;
  }

  public String getEconomicCd() {
    return economicCd;
  }

  public void setEconomicCd(String economicCd) {
    this.economicCd = economicCd;
  }

  public String getEngineeringBo() {
    return engineeringBo;
  }

  public void setEngineeringBo(String engineeringBo) {
    this.engineeringBo = engineeringBo;
  }

  public String getMailingCondition() {
    return mailingCondition;
  }

  public void setMailingCondition(String mailingCondition) {
    this.mailingCondition = mailingCondition;
  }

  public String getBpSalesRepNo() {
    return this.bpSalesRepNo;
  }

  public void setBpSalesRepNo(String bpSalesRepNo) {
    this.bpSalesRepNo = bpSalesRepNo;
  }

  public String getEmbargoCd() {
    return this.embargoCd;
  }

  public void setEmbargoCd(String embargoCd) {
    this.embargoCd = embargoCd;
  }

  public String getAgreementSignDate() {
    return this.agreementSignDate;
  }

  public void setAgreementSignDate(String agreementSignDate) {
    this.agreementSignDate = agreementSignDate;
  }

  public String getCisServiceCustIndc() {
    return this.cisServiceCustIndc;
  }

  public void setCisServiceCustIndc(String cisServiceCustIndc) {
    this.cisServiceCustIndc = cisServiceCustIndc;
  }

  public String getCommercialFinanced() {
    return commercialFinanced;
  }

  public void setCommercialFinanced(String commercialFinanced) {
    this.commercialFinanced = commercialFinanced;
  }

  public String getInstallBranchOff() {
    return installBranchOff;
  }

  public void setInstallBranchOff(String installBranchOff) {
    this.installBranchOff = installBranchOff;
  }

  public String getLegacyCurrencyCd() {
    return this.legacyCurrencyCd;
  }

  public void setLegacyCurrencyCd(String legacyCurrencyCd) {
    this.legacyCurrencyCd = legacyCurrencyCd;
  }

  public String getCurrencyCd() {
    return currencyCd;
  }

  public void setCurrencyCd(String currencyCd) {
    this.currencyCd = currencyCd;
  }

  public String getCreditCd() {
    return creditCd;
  }

  public void setCreditCd(String creditCd) {
    this.creditCd = creditCd;
  }

  public String getDupSalesRepNo() {
    return dupSalesRepNo;
  }

  public void setDupSalesRepNo(String dupSalesRepNo) {
    this.dupSalesRepNo = dupSalesRepNo;
  }

  public String getDupEnterpriseNo() {
    return dupEnterpriseNo;
  }

  public void setDupEnterpriseNo(String dupEnterpriseNo) {
    this.dupEnterpriseNo = dupEnterpriseNo;
  }

  public String getDupSalesBoCd() {
    return dupSalesBoCd;
  }

  public void setDupSalesBoCd(String dupSalesBoCd) {
    this.dupSalesBoCd = dupSalesBoCd;
  }

  public String getDupIsuCd() {
    return dupIsuCd;
  }

  public void setDupIsuCd(String dupIsuCd) {
    this.dupIsuCd = dupIsuCd;
  }

  public String getDupClientTierCd() {
    return dupClientTierCd;
  }

  public void setDupClientTierCd(String dupClientTierCd) {
    this.dupClientTierCd = dupClientTierCd;
  }

  public String getIdentClient() {
    return identClient;
  }

  public void setIdentClient(String identClient) {
    this.identClient = identClient;
  }

  public String getModeOfPayment() {
    return modeOfPayment;
  }

  public void setModeOfPayment(String modeOfPayment) {
    this.modeOfPayment = modeOfPayment;
  }

  public String getGovType() {
    return govType;
  }

  public void setGovType(String govType) {
    this.govType = govType;
  }

  public String getIsbuCd() {
    return isbuCd;
  }

  public void setIsbuCd(String isbuCd) {
    this.isbuCd = isbuCd;
  }

  // public String getEstabNo() {
  // return estabNo;
  // }
  //
  // public void setEstabNo(String estabNo) {
  // this.estabNo = estabNo;
  // }

  public String getJsicCd() {
    return jsicCd;
  }

  public void setJsicCd(String jsicCd) {
    this.jsicCd = jsicCd;
  }

  public String getTier2() {
    return tier2;
  }

  public void setTier2(String tier2) {
    this.tier2 = tier2;
  }

  public String getCsBo() {
    return csBo;
  }

  public void setCsBo(String csBo) {
    this.csBo = csBo;
  }

  public String getCsDiv() {
    return csDiv;
  }

  public void setCsDiv(String csDiv) {
    this.csDiv = csDiv;
  }

  public String getIinInd() {
    return iinInd;
  }

  public void setIinInd(String iinInd) {
    this.iinInd = iinInd;
  }

  public String getValueAddRem() {
    return valueAddRem;
  }

  public void setValueAddRem(String valueAddRem) {
    this.valueAddRem = valueAddRem;
  }

  public String getSiInd() {
    return siInd;
  }

  public void setSiInd(String siInd) {
    this.siInd = siInd;
  }

  public String getCrsCd() {
    return crsCd;
  }

  public void setCrsCd(String crsCd) {
    this.crsCd = crsCd;
  }

  public String getBillingProcCd() {
    return billingProcCd;
  }

  public void setBillingProcCd(String billingProcCd) {
    this.billingProcCd = billingProcCd;
  }

  public String getChannelCd() {
    return channelCd;
  }

  public void setChannelCd(String channelCd) {
    this.channelCd = channelCd;
  }

  public String getInvoiceSplitCd() {
    return invoiceSplitCd;
  }

  public void setInvoiceSplitCd(String invoiceSplitCd) {
    this.invoiceSplitCd = invoiceSplitCd;
  }

  public String getBillToCustNo() {
    return billToCustNo;
  }

  public void setBillToCustNo(String billToCustNo) {
    this.billToCustNo = billToCustNo;
  }

  public String getCreditToCustNo() {
    return creditToCustNo;
  }

  public void setCreditToCustNo(String creditToCustNo) {
    this.creditToCustNo = creditToCustNo;
  }

  // public String getGovOfficeDivCd() {
  // return govOfficeDivCd;
  // }
  //
  // public void setGovOfficeDivCd(String govOfficeDivCd) {
  // this.govOfficeDivCd = govOfficeDivCd;
  // }
  //
  // public String getDealerNo() {
  // return dealerNo;
  // }
  //
  // public void setDealerNo(String dealerNo) {
  // this.dealerNo = dealerNo;
  // }

  public String getSoProjectCd() {
    return soProjectCd;
  }

  public void setSoProjectCd(String soProjectCd) {
    this.soProjectCd = soProjectCd;
  }

  public String getProdType() {
    return prodType;
  }

  public void setProdType(String prodType) {
    this.prodType = prodType;
  }

  public String getAdminDeptCd() {
    return adminDeptCd;
  }

  public void setAdminDeptCd(String adminDeptCd) {
    this.adminDeptCd = adminDeptCd;
  }

  public String getAdminDeptLine() {
    return adminDeptLine;
  }

  public void setAdminDeptLine(String adminDeptLine) {
    this.adminDeptLine = adminDeptLine;
  }

  public String getChargeCd() {
    return chargeCd;
  }

  public void setChargeCd(String chargeCd) {
    this.chargeCd = chargeCd;
  }

  public String getOutsourcingService() {
    return outsourcingService;
  }

  public void setOutsourcingService(String outsourcingService) {
    this.outsourcingService = outsourcingService;
  }

  public String getCreditBp() {
    return creditBp;
  }

  public void setCreditBp(String creditBp) {
    this.creditBp = creditBp;
  }

  public String getZseriesSw() {
    return zseriesSw;
  }

  public void setZseriesSw(String zseriesSw) {
    this.zseriesSw = zseriesSw;
  }

  public Date getRequestDueDate() {
    return requestDueDate;
  }

  public void setRequestDueDate(Date requestDueDate) {
    this.requestDueDate = requestDueDate;
  }

  public String getLeasingCompanyIndc() {
    return leasingCompanyIndc;
  }

  public void setLeasingCompanyIndc(String leasingCompanyIndc) {
    this.leasingCompanyIndc = leasingCompanyIndc;
  }

  public String getOrgNo() {
    return orgNo;
  }

  public void setOrgNo(String orgNo) {
    this.orgNo = orgNo;
  }

  public String getSalesTeamCd() {
    return salesTeamCd;
  }

  public void setSalesTeamCd(String salesTeamCd) {
    this.salesTeamCd = salesTeamCd;
  }

  public String getEducAllowCd() {
    return educAllowCd;
  }

  public void setEducAllowCd(String educAllowCd) {
    this.educAllowCd = educAllowCd;
  }

  // public String getSalesBoCd() {
  // return this.salesBusOffCd;
  // }
  //
  // public void setSalesBoCd(String salesBoCd) {
  // this.salesBusOffCd = salesBoCd;
  // }

  public String getNationalCusId() {
    return nationalCusId;
  }

  public void setNationalCusId(String nationalCusId) {
    this.nationalCusId = nationalCusId;
  }

  public String getHwSvcsRepTeamNo() {
    return hwSvcsRepTeamNo;
  }

  public void setHwSvcsRepTeamNo(String hwSvcsRepTeamNo) {
    this.hwSvcsRepTeamNo = hwSvcsRepTeamNo;
  }

  public String getCrosSubTyp() {
    return crosSubTyp;
  }

  public void setCrosSubTyp(String crosSubTyp) {
    this.crosSubTyp = crosSubTyp;
  }

  public String getUsSicmen() {
    return usSicmen;
  }

  public void setUsSicmen(String usSicmen) {
    this.usSicmen = usSicmen;
  }

  public String getMilitary() {
    return military;
  }

  public void setMilitary(String military) {
    this.military = military;
  }

  public String getApCustClusterId() {
    return apCustClusterId;
  }

  public void setApCustClusterId(String apCustClusterId) {
    this.apCustClusterId = apCustClusterId;
  }

  public String getCustAcctType() {
    return custAcctType;
  }

  public void setCustAcctType(String custAcctType) {
    this.custAcctType = custAcctType;
  }

  public String getTaxPayerCustCd() {
    return taxPayerCustCd;
  }

  public void setTaxPayerCustCd(String taxPayerCustCd) {
    this.taxPayerCustCd = taxPayerCustCd;
  }

  public String getLocationNumber() {
    return locationNumber;
  }

  public void setLocationNumber(String locationNumber) {
    this.locationNumber = locationNumber;
  }

  public String getTaxCd3() {
    return this.taxCd3;
  }

  public void setTaxCd3(String taxCd3) {
    this.taxCd3 = taxCd3;
  }

}