/*
This file was automatically generated by the EntityCreator engine on Wed Jun 07 16:05:57 SGT 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the DEFAULT_APPROVAL_RECIPIENTS database table.
 * 
 * @author Eduard Bernardo
 */
@Entity
@Table(name = "DEFAULT_APPROVAL_RECIPIENTS", schema = "CREQCMR")
public class DefaultApprovalRecipients extends BaseEntity<DefaultApprovalRecipientsPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private DefaultApprovalRecipientsPK id;

  @Override
  public DefaultApprovalRecipientsPK getId() {
    return id;
  }

  @Override
  public void setId(DefaultApprovalRecipientsPK id) {
    this.id = id;
  }

  @Column(name = "NOTES_ID")
  private String notesId;

  @Column(name = "DISPLAY_NAME")
  private String displayName;

  public String getNotesId() {
    return this.notesId;
  }

  public void setNotesId(String notesId) {
    this.notesId = notesId;
  }

  public String getDisplayName() {
    return this.displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

}