/*
This file was automatically generated by the EntityCreator engine on Wed Jun 07 16:05:57 SGT 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityResult;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the DEFAULT_APPROVALS database table.
 * 
 * @author Eduard Bernardo
 */
@Entity
@Table(
    name = "DEFAULT_APPROVALS",
    schema = "CREQCMR")
@SqlResultSetMappings({ @SqlResultSetMapping(
    name = DefaultApprovals.DEFAULT_APPROVAL_MAPPING,
    entities = { @EntityResult(
        entityClass = DefaultApprovals.class) },
    columns = { @ColumnResult(
        name = "TITLE"),
        @ColumnResult(
            name = "COUNTRY") }),
    @SqlResultSetMapping(
        name = "DefaultApprovalReqMapping",
        entities = { @EntityResult(
            entityClass = DefaultApprovals.class),
            @EntityResult(
                entityClass = DefaultApprovalRecipients.class) }) })
public class DefaultApprovals extends BaseEntity<DefaultApprovalsPK> implements Serializable {

  public static final String DEFAULT_APPROVAL_MAPPING = "DefaultApprovals";
  public static String DEFLT_APPROVAL_REQ_MAPPING = "DefaultApprovalReqMapping";

  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private DefaultApprovalsPK id;

  @Override
  public DefaultApprovalsPK getId() {
    return id;
  }

  @Override
  public void setId(DefaultApprovalsPK id) {
    this.id = id;
  }

  @Column(
      name = "TYP_ID")
  private int typId;

  @Column(
      name = "GEO_CD")
  private String geoCd;

  @Column(
      name = "DEFAULT_APPROVAL_DESC")
  private String defaultApprovalDesc;

  @Column(
      name = "REQUEST_TYP")
  private String requestTyp;

  @Column(
      name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(
      name = "CREATE_BY")
  private String createBy;

  @Column(
      name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date lastUpdtTs;

  @Column(
      name = "LAST_UPDT_BY")
  private String lastUpdtBy;

  @Column(
      name = "APPROVAL_MAIL_CONTENT")
  private String approvalMailContent;

  public int getTypId() {
    return this.typId;
  }

  public void setTypId(int typId) {
    this.typId = typId;
  }

  public String getGeoCd() {
    return this.geoCd;
  }

  public void setGeoCd(String geoCd) {
    this.geoCd = geoCd;
  }

  public String getDefaultApprovalDesc() {
    return this.defaultApprovalDesc;
  }

  public void setDefaultApprovalDesc(String defaultApprovalDesc) {
    this.defaultApprovalDesc = defaultApprovalDesc;
  }

  public String getRequestTyp() {
    return this.requestTyp;
  }

  public void setRequestTyp(String requestTyp) {
    this.requestTyp = requestTyp;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getLastUpdtTs() {
    return this.lastUpdtTs;
  }

  public void setLastUpdtTs(Date lastUpdtTs) {
    this.lastUpdtTs = lastUpdtTs;
  }

  public String getLastUpdtBy() {
    return this.lastUpdtBy;
  }

  public void setLastUpdtBy(String lastUpdtBy) {
    this.lastUpdtBy = lastUpdtBy;
  }

  public String getApprovalMailContent() {
    return approvalMailContent;
  }

  public void setApprovalMailContent(String approvalMailContent) {
    this.approvalMailContent = approvalMailContent;
  }

}