/*
This file was automatically generated by the EntityCreator engine on Wed Jun 07 16:05:57 SGT 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the DEFAULT_APPROVAL_RECIPIENTS database table.
 * 
 * @author Eduard Bernardo
 */
@Embeddable
public class DefaultApprovalRecipientsPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "DEFAULT_APPROVAL_ID")
  private long defaultApprovalId;

  @Column(name = "INTRANET_ID")
  private String intranetId;

  public long getDefaultApprovalId() {
    return this.defaultApprovalId;
  }

  public void setDefaultApprovalId(long defaultApprovalId) {
    this.defaultApprovalId = defaultApprovalId;
  }

  public String getIntranetId() {
    return this.intranetId;
  }

  public void setIntranetId(String intranetId) {
    this.intranetId = intranetId;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof DefaultApprovalRecipientsPK)) {
      return false;
    }
    DefaultApprovalRecipientsPK o = (DefaultApprovalRecipientsPK) other;
    return this.defaultApprovalId == o.defaultApprovalId && this.intranetId.equals(o.intranetId);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.defaultApprovalId > 0 ? new java.lang.Long(this.defaultApprovalId).hashCode() : 0);
    hash = hash * prime + (this.intranetId != null ? this.intranetId.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.defaultApprovalId > 0 && !StringUtils.isEmpty(this.intranetId);

  }
}