/*
This file was automatically generated by the EntityCreator engine on Thu Aug 06 14:04:30 CST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the DELEGATE database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(name = "DELEGATE", schema = "CREQCMR")
public class Delegate extends BaseEntity<DelegatePK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private DelegatePK id;

  @Override
  public DelegatePK getId() {
    return id;
  }

  @Override
  public void setId(DelegatePK id) {
    this.id = id;
  }

  @Column(name = "DELEGATE_NM")
  private String delegateNm;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Timestamp createTs;

  public String getDelegateNm() {
    return this.delegateNm;
  }

  public void setDelegateNm(String delegateNm) {
    this.delegateNm = delegateNm;
  }

  public Timestamp getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Timestamp createTs) {
    this.createTs = createTs;
  }

}