/*
This file was automatically generated by the EntityCreator engine on Thu Aug 20 16:16:32 IST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityResult;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;

/**
 * The persistent class for the FIELD_INFO database table.
 * 
 * @author Rama mohan
 */
@Entity
@Table(name = "FIELD_INFO", schema = "CREQCMR")
@SqlResultSetMappings({ @SqlResultSetMapping(name = "FieldInfoMap", entities = { @EntityResult(entityClass = FieldInfo.class) }, columns = { @ColumnResult(name = "LBL_CNTRY") }) })
public class FieldInfo extends BaseEntity<FieldInfoPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String FIELD_INFO_MAP = "FieldInfoMap";

  @EmbeddedId
  private FieldInfoPK id;

  @Override
  public FieldInfoPK getId() {
    return id;
  }

  @Override
  public void setId(FieldInfoPK id) {
    this.id = id;
  }

  private String type;

  private String choice;

  @Column(name = "MIN_LENGTH")
  private int minLength;

  @Column(name = "MAX_LENGTH")
  private int maxLength;

  private String validation;

  private String required;

  @Column(name = "DEPENDS_ON")
  private String dependsOn;

  @Column(name = "DEPENDS_SETTING")
  private String dependsSetting;

  @Column(name = "COND_REQ_IND")
  private String condReqInd;

  @Column(name = "READ_ONLY_REQ_IND")
  private String readOnlyReqInd;

  @Column(name = "READ_ONLY_INFO_IND")
  private String readOnlyInfoInd;

  @Column(name = "READ_ONLY_REV_IND")
  private String readOnlyRevInd;

  @Column(name = "READ_ONLY_PROC_IND")
  private String readOnlyProcInd;

  private String cmt;

  @Column(name = "VAL_DEPENDS_ON")
  private String valDependsOn;

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getChoice() {
    return this.choice;
  }

  public void setChoice(String choice) {
    this.choice = choice;
  }

  public int getMinLength() {
    return this.minLength;
  }

  public void setMinLength(int minLength) {
    this.minLength = minLength;
  }

  public int getMaxLength() {
    return this.maxLength;
  }

  public void setMaxLength(int maxLength) {
    this.maxLength = maxLength;
  }

  public String getValidation() {
    return this.validation;
  }

  public void setValidation(String validation) {
    this.validation = validation;
  }

  public String getRequired() {
    return this.required;
  }

  public void setRequired(String required) {
    this.required = required;
  }

  public String getDependsOn() {
    return this.dependsOn;
  }

  public void setDependsOn(String dependsOn) {
    this.dependsOn = dependsOn;
  }

  public String getDependsSetting() {
    return this.dependsSetting;
  }

  public void setDependsSetting(String dependsSetting) {
    this.dependsSetting = dependsSetting;
  }

  public String getCondReqInd() {
    return this.condReqInd;
  }

  public void setCondReqInd(String condReqInd) {
    this.condReqInd = condReqInd;
  }

  public String getReadOnlyReqInd() {
    return this.readOnlyReqInd;
  }

  public void setReadOnlyReqInd(String readOnlyReqInd) {
    this.readOnlyReqInd = readOnlyReqInd;
  }

  public String getReadOnlyInfoInd() {
    return this.readOnlyInfoInd;
  }

  public void setReadOnlyInfoInd(String readOnlyInfoInd) {
    this.readOnlyInfoInd = readOnlyInfoInd;
  }

  public String getReadOnlyRevInd() {
    return this.readOnlyRevInd;
  }

  public void setReadOnlyRevInd(String readOnlyRevInd) {
    this.readOnlyRevInd = readOnlyRevInd;
  }

  public String getReadOnlyProcInd() {
    return this.readOnlyProcInd;
  }

  public void setReadOnlyProcInd(String readOnlyProcInd) {
    this.readOnlyProcInd = readOnlyProcInd;
  }

  public String getCmt() {
    return this.cmt;
  }

  public void setCmt(String cmt) {
    this.cmt = cmt;
  }

  public String getValDependsOn() {
    return valDependsOn;
  }

  public void setValDependsOn(String valDependsOn) {
    this.valDependsOn = valDependsOn;
  }

}