/*
This file was automatically generated by the EntityCreator engine on Thu Aug 20 16:17:12 IST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the FIELD_LBL database table.
 * 
 * @author Rama mohan
 */
@Embeddable
public class FieldLblPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "FIELD_ID")
  private String fieldId;

  @Column(name = "CMR_ISSUING_CNTRY")
  private String cmrIssuingCntry;

  public String getFieldId() {
    return this.fieldId;
  }

  public void setFieldId(String fieldId) {
    this.fieldId = fieldId;
  }

  public String getCmrIssuingCntry() {
    return this.cmrIssuingCntry;
  }

  public void setCmrIssuingCntry(String cmrIssuingCntry) {
    this.cmrIssuingCntry = cmrIssuingCntry;
  }

  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof FieldLblPK)) {
      return false;
    }
    FieldLblPK o = (FieldLblPK) other;
    return this.fieldId.equals(o.fieldId) && this.cmrIssuingCntry.equals(o.cmrIssuingCntry);

  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.fieldId != null ? this.fieldId.hashCode() : 0);
    hash = hash * prime + (this.cmrIssuingCntry != null ? this.cmrIssuingCntry.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.fieldId) && !StringUtils.isEmpty(this.cmrIssuingCntry);

  }
}