/*
This file was automatically generated by the EntityCreator engine on Tue Jul 25 21:37:53 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.ibm.cio.cmr.request.entity.listeners.AutoTrimStrings;
import com.ibm.cio.cmr.request.entity.listeners.ChangeLogDetails;
import com.ibm.cio.cmr.request.entity.listeners.ChangeLogListener;
import com.ibm.cio.cmr.request.entity.listeners.TrimListener;

/**
 * The persistent class for the GEO_ADL_CONT_DTL database table. Additional
 * contact information entity.
 * 
 * @author Neil Sherwin Espolong
 */
@Entity
@Table(name = "GEO_ADL_CONT_DTL", schema = "CREQCMR")
@EntityListeners({ TrimListener.class, ChangeLogListener.class })
@AutoTrimStrings
@ChangeLogDetails(childTable = true, reqId = "id.reqId")
public class GeoContactInfo extends BaseEntity<GeoContactInfoPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private GeoContactInfoPK id;

  @Override
  public GeoContactInfoPK getId() {
    return id;
  }

  @Override
  public void setId(GeoContactInfoPK id) {
    this.id = id;
  }

  @Column(name = "CONTACT_TYPE")
  private String contactType;

  @Column(name = "CONTACT_NAME")
  private String contactName;

  @Column(name = "PHONE")
  private String contactPhone;

  @Column(name = "EMAIL")
  private String contactEmail;

  @Column(name = "CONTACT_NUM")
  private String contactSeqNum;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(name = "CREATE_BY_ID")
  private String createById;

  @Column(name = "UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updtTs;

  @Column(name = "UPDT_BY_ID")
  private String updtById;

  @Transient
  private String reqType;

  @Transient
  private String cmrIssuingCntry;

  @Transient
  private String currentEmail1;

  @Column(name = "TREATMENT")
  private String contactTreatment;

  @Column(name = "FUNC")
  private String contactFunc;

  public String getContactType() {
    return this.contactType;
  }

  public void setContactType(String contactType) {
    this.contactType = contactType;
  }

  public String getContactName() {
    return this.contactName;
  }

  public void setContactName(String contactName) {
    this.contactName = contactName;
  }

  public String getContactPhone() {
    return contactPhone;
  }

  public void setContactPhone(String contactPhone) {
    this.contactPhone = contactPhone;
  }

  public String getContactEmail() {
    return contactEmail;
  }

  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  public String getContactSeqNum() {
    return contactSeqNum;
  }

  public void setContactSeqNum(String contactSeqNum) {
    this.contactSeqNum = contactSeqNum;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateById() {
    return this.createById;
  }

  public void setCreateById(String createById) {
    this.createById = createById;
  }

  public Date getUpdtTs() {
    return this.updtTs;
  }

  public void setUpdtTs(Date updtTs) {
    this.updtTs = updtTs;
  }

  public String getUpdtById() {
    return this.updtById;
  }

  public void setUpdtById(String updtById) {
    this.updtById = updtById;
  }

  public String getReqType() {
    return reqType;
  }

  public void setReqType(String reqType) {
    this.reqType = reqType;
  }

  public String getCmrIssuingCntry() {
    return cmrIssuingCntry;
  }

  public void setCmrIssuingCntry(String cmrIssuingCntry) {
    this.cmrIssuingCntry = cmrIssuingCntry;
  }

  public String getCurrentEmail1() {
    return currentEmail1;
  }

  public void setCurrentEmail1(String currentEmail1) {
    this.currentEmail1 = currentEmail1;
  }

  public String getContactTreatment() {
    return contactTreatment;
  }

  public void setContactTreatment(String contactTreatment) {
    this.contactTreatment = contactTreatment;
  }

  public String getContactFunc() {
    return contactFunc;
  }

  public void setContactFunc(String contactFunc) {
    this.contactFunc = contactFunc;
  }

}