/*
This file was automatically generated by the EntityCreator engine on Mon Jun 10 22:48:52 SGT 2019.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the GEO_CITIES database table.
 * 
 * @author DennisNATAD
 */
@Embeddable
public class GeoCitiesPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "ISSUING_CNTRY")
  private String issuingCntry;

  @Column(name = "CITY_ID")
  private String cityId;

  public String getIssuingCntry(){
    return this.issuingCntry;
  }

  public void setIssuingCntry(String issuingCntry){
    this.issuingCntry = issuingCntry;
  }


  public String getCityId(){
    return this.cityId;
  }

  public void setCityId(String cityId){
    this.cityId = cityId;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof GeoCitiesPK)) {
      return false;
    }
    GeoCitiesPK o = (GeoCitiesPK) other;
    return this.issuingCntry.equals(o.issuingCntry) && this.cityId.equals(o.cityId);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.issuingCntry != null ? this.issuingCntry.hashCode() : 0);
    hash = hash * prime + (this.cityId != null ? this.cityId.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.issuingCntry) && !StringUtils.isEmpty(this.cityId);

  }
}