/*
This file was automatically generated by the EntityCreator engine on Mon Jun 10 22:48:52 SGT 2019.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the GEO_CITIES database table.
 * 
 * @author DennisNATAD
 */
@Entity
@Table(name = "GEO_CITIES", schema = "CREQCMR")
public class GeoCities extends BaseEntity<GeoCitiesPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private GeoCitiesPK id;

  public GeoCitiesPK getId() {
    return id;
  }

  public void setId(GeoCitiesPK id) {
    this.id = id;
  }
  
  @Column(name = "CITY_DESC")
  private String cityDesc;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(name = "CREATE_BY_ID")
  private String createById;

  @Column(name = "UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updtTs;

  @Column(name = "UPDT_BY_ID")
  private String updtById;

  public String getCityDesc(){
    return this.cityDesc;
  }

  public void setCityDesc(String cityDesc){
    this.cityDesc = cityDesc;
  }


  public Date getCreateTs(){
    return this.createTs;
  }

  public void setCreateTs(Date createTs){
    this.createTs = createTs;
  }


  public String getCreateById(){
    return this.createById;
  }

  public void setCreateById(String createById){
    this.createById = createById;
  }


  public Date getUpdtTs(){
    return this.updtTs;
  }

  public void setUpdtTs(Date updtTs){
    this.updtTs = updtTs;
  }


  public String getUpdtById(){
    return this.updtById;
  }

  public void setUpdtById(String updtById){
    this.updtById = updtById;
  }




}