/*
This file was automatically generated by the EntityCreator engine on Tue Jul 25 21:37:53 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * The primary key class for the GEO_ADL_CONT_DTL database table.
 * 
 * @author Neil Sherwin Espolong
 */
@Embeddable
public class GeoContactInfoPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "REQ_ID")
  private long reqId;

  @Column(name = "GEO_ADL_CONT_DTL_ID")
  private int contactInfoId;

  public long getReqId() {
    return this.reqId;
  }

  public void setReqId(long reqId) {
    this.reqId = reqId;
  }

  public int getContactInfoId() {
    return contactInfoId;
  }

  public void setContactInfoId(int contactInfoId) {
    this.contactInfoId = contactInfoId;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof GeoContactInfoPK)) {
      return false;
    }
    GeoContactInfoPK o = (GeoContactInfoPK) other;
    return this.reqId == o.reqId && this.contactInfoId == o.contactInfoId;

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.reqId > 0 ? new java.lang.Long(this.reqId).hashCode() : 0);
    hash = hash * prime + (this.contactInfoId > 0 ? new java.lang.Integer(this.contactInfoId).hashCode() : 0);
    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.reqId > 0 && this.contactInfoId > 0;
  }
}