/*
This file was automatically generated by the EntityCreator engine on Fri Mar 10 12:29:56 IST 2017.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the GEO_TAX_INFO database table.
 * 
 * @author ibm_admin
 */
@Entity
@Table(name = "GEO_TAX_INFO", schema = "CREQCMR")
public class GeoTaxInfo extends BaseEntity<GeoTaxInfoPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private GeoTaxInfoPK id;

  public GeoTaxInfoPK getId() {
    return id;
  }

  public void setId(GeoTaxInfoPK id) {
    this.id = id;
  }
  
  @Column(name = "TAX_NUM")
  private String taxNum;

  @Column(name = "TAX_CD")
  private String taxCd;

  @Column(name = "TAX_SEPARATION_INDC")
  private String taxSeparationIndc;

  @Column(name = "BILLING_PRINT_INDC")
  private String billingPrintIndc;

  @Column(name = "CONTRACT_PRINT_INDC")
  private String contractPrintIndc;

  @Column(name = "CNTRY_USE")
  private String cntryUse;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(name = "CREATE_BY_ID")
  private String createById;

  @Column(name = "UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updtTs;

  @Column(name = "UPDT_BY_ID")
  private String updtById;

  public String getTaxNum(){
    return this.taxNum;
  }

  public void setTaxNum(String taxNum){
    this.taxNum = taxNum;
  }


  public String getTaxCd(){
    return this.taxCd;
  }

  public void setTaxCd(String taxCd){
    this.taxCd = taxCd;
  }


  public String getTaxSeparationIndc(){
    return this.taxSeparationIndc;
  }

  public void setTaxSeparationIndc(String taxSeparationIndc){
    this.taxSeparationIndc = taxSeparationIndc;
  }


  public String getBillingPrintIndc(){
    return this.billingPrintIndc;
  }

  public void setBillingPrintIndc(String billingPrintIndc){
    this.billingPrintIndc = billingPrintIndc;
  }


  public String getContractPrintIndc(){
    return this.contractPrintIndc;
  }

  public void setContractPrintIndc(String contractPrintIndc){
    this.contractPrintIndc = contractPrintIndc;
  }


  public String getCntryUse(){
    return this.cntryUse;
  }

  public void setCntryUse(String cntryUse){
    this.cntryUse = cntryUse;
  }


  public Date getCreateTs(){
    return this.createTs;
  }

  public void setCreateTs(Date createTs){
    this.createTs = createTs;
  }


  public String getCreateById(){
    return this.createById;
  }

  public void setCreateById(String createById){
    this.createById = createById;
  }


  public Date getUpdtTs(){
    return this.updtTs;
  }

  public void setUpdtTs(Date updtTs){
    this.updtTs = updtTs;
  }


  public String getUpdtById(){
    return this.updtById;
  }

  public void setUpdtById(String updtById){
    this.updtById = updtById;
  }




}