/*
This file was automatically generated by the EntityCreator engine on Thu Jul 05 17:24:11 CST 2018.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.StringUtils;

/**
 * The primary key class for the JP_JSIC_CODE_MAP database table.
 * 
 * @author XiangBinLiu
 */
@Embeddable
public class JpBoCodesMapPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "SUBSIDIARY_CD")
  private String subsidiaryCd;

  @Column(name = "OFFICE_CD")
  private String officeCd;

  @Column(name = "SUB_OFFICE_CD")
  private String subOfficeCd;

  public String getSubsidiaryCd() {
    return subsidiaryCd;
  }

  public void setSubsidiaryCd(String subsidiaryCd) {
    this.subsidiaryCd = subsidiaryCd;
  }

  public String getOfficeCd() {
    return officeCd;
  }

  public void setOfficeCd(String officeCd) {
    this.officeCd = officeCd;
  }

  public String getSubOfficeCd() {
    return subOfficeCd;
  }

  public void setSubOfficeCd(String subOfficeCd) {
    this.subOfficeCd = subOfficeCd;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof JpBoCodesMapPK)) {
      return false;
    }
    JpBoCodesMapPK o = (JpBoCodesMapPK) other;
    return this.subsidiaryCd.equals(o.subsidiaryCd) && this.officeCd.equals(o.officeCd) && this.subOfficeCd.equals(o.subOfficeCd);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;

    hash = hash * prime + (this.subsidiaryCd != null ? this.subsidiaryCd.hashCode() : 0);
    hash = hash * prime + (this.officeCd != null ? this.officeCd.hashCode() : 0);
    hash = hash * prime + (this.subOfficeCd != null ? this.subOfficeCd.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.subsidiaryCd) && !StringUtils.isEmpty(this.officeCd) && !StringUtils.isEmpty(this.subOfficeCd);

  }
}