/*
This file was automatically generated by the EntityCreator engine on Thu Jul 05 17:24:11 CST 2018.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the JPINTERIM.BO_CODES_MAP database table.
 * 
 * @author XiangBinLiu
 */
@Entity
@Table(name = "BO_CODES_MAP", schema = "JPINTERIM")
public class JpBoCodesMap extends BaseEntity<JpBoCodesMapPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private JpBoCodesMapPK id;

  @Override
  public JpBoCodesMapPK getId() {
    return id;
  }

  @Override
  public void setId(JpBoCodesMapPK id) {
    this.id = id;
  }

  @Column(name = "BO_CD")
  private String boCd;

  @Column(name = "FIELD_SALES_CD")
  private String fieldSalesCd;

  @Column(name = "SALES_OFFICE_CD")
  private String salesOfficeCd;

  @Column(name = "MKTG_DIV_CD")
  private String mktgDivCd;

  @Column(name = "MRC_CD")
  private String mrcCd;

  @Column(name = "DEPT_CD")
  private String deptCd;

  @Column(name = "MKTG_DEPT_NAME")
  private String mktgDeptName;

  @Column(name = "CLUSTER_ID")
  private String clusterId;

  @Column(name = "CLIENT_TIER_CD")
  private String clientTierCd;

  @Column(name = "ISU_CD_OVERRIDE")
  private String isuCdOverride;

  @Column(name = "ISIC_CD")
  private String isicCd;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(name = "CREATE_BY")
  private String createBy;

  @Column(name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateTs;

  @Column(name = "LAST_UPDT_BY")
  private String updateBy;

  public String getBoCd() {
    return boCd;
  }

  public void setBoCd(String boCd) {
    this.boCd = boCd;
  }

  public String getFieldSalesCd() {
    return fieldSalesCd;
  }

  public void setFieldSalesCd(String fieldSalesCd) {
    this.fieldSalesCd = fieldSalesCd;
  }

  public String getSalesOfficeCd() {
    return salesOfficeCd;
  }

  public void setSalesOfficeCd(String salesOfficeCd) {
    this.salesOfficeCd = salesOfficeCd;
  }

  public String getMktgDivCd() {
    return mktgDivCd;
  }

  public void setMktgDivCd(String mktgDivCd) {
    this.mktgDivCd = mktgDivCd;
  }

  public String getMrcCd() {
    return mrcCd;
  }

  public void setMrcCd(String mrcCd) {
    this.mrcCd = mrcCd;
  }

  public String getDeptCd() {
    return deptCd;
  }

  public void setDeptCd(String deptCd) {
    this.deptCd = deptCd;
  }

  public String getMktgDeptName() {
    return mktgDeptName;
  }

  public void setMktgDeptName(String mktgDeptName) {
    this.mktgDeptName = mktgDeptName;
  }

  public String getClusterId() {
    return clusterId;
  }

  public void setClusterId(String clusterId) {
    this.clusterId = clusterId;
  }

  public String getClientTierCd() {
    return clientTierCd;
  }

  public void setClientTierCd(String clientTierCd) {
    this.clientTierCd = clientTierCd;
  }

  public String getIsuCdOverride() {
    return isuCdOverride;
  }

  public void setIsuCdOverride(String isuCdOverride) {
    this.isuCdOverride = isuCdOverride;
  }

  public String getIsicCd() {
    return isicCd;
  }

  public void setIsicCd(String isicCd) {
    this.isicCd = isicCd;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getUpdateTs() {
    return this.updateTs;
  }

  public void setUpdateTs(Date updateTs) {
    this.updateTs = updateTs;
  }

  public String getUpdateBy() {
    return this.updateBy;
  }

  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

}