/*
This file was automatically generated by the EntityCreator engine on Thu Jul 05 17:24:11 CST 2018.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the JPINTERIM.ISIC_TO_JSIC_MAP database table.
 * 
 * @author XiangBinLiu
 */
@Entity
@Table(name = "ISIC_TO_JSIC_MAP", schema = "JPINTERIM")
public class JpIsicToJsicMap extends BaseEntity<JpIsicToJsicMapPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private JpIsicToJsicMapPK id;

  @Override
  public JpIsicToJsicMapPK getId() {
    return id;
  }

  @Override
  public void setId(JpIsicToJsicMapPK id) {
    this.id = id;
  }

  @Column(name = "ISIC_CD")
  private String isicCd;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(name = "CREATE_BY")
  private String createBy;

  @Column(name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateTs;

  @Column(name = "LAST_UPDT_BY")
  private String updateBy;

  public String getIsicCd() {
    return isicCd;
  }

  public void setIsicCd(String isicCd) {
    this.isicCd = isicCd;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getUpdateTs() {
    return this.updateTs;
  }

  public void setUpdateTs(Date updateTs) {
    this.updateTs = updateTs;
  }

  public String getUpdateBy() {
    return this.updateBy;
  }

  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

}