/*
This file was automatically generated by the EntityCreator engine on Thu Jul 05 17:24:11 CST 2018.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the JP_JSIC_CODE_MAP database table.
 * 
 * @author XiangBinLiu
 */
@Embeddable
public class JpJsicCodeMapPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(
      name = "JSIC_CD")
  private String jsicCd;

  @Column(
      name = "SUB_INDUSTRY_CD")
  private String subIndustryCd;

  @Column(
      name = "ISU_CD")
  private String isuCd;

  @Column(
      name = "ISIC_CD")
  private String isicCd;

  public String getJsicCd() {
    return jsicCd;
  }

  public void setJsicCd(String jsicCd) {
    this.jsicCd = jsicCd;
  }

  public String getSubIndustryCd() {
    return subIndustryCd;
  }

  public void setSubIndustryCd(String subIndustryCd) {
    this.subIndustryCd = subIndustryCd;
  }

  public String getIsuCd() {
    return isuCd;
  }

  public void setIsuCd(String isuCd) {
    this.isuCd = isuCd;
  }

  public String getIsicCd() {
    return isicCd;
  }

  public void setIsicCd(String isicCd) {
    this.isicCd = isicCd;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof JpJsicCodeMapPK)) {
      return false;
    }
    JpJsicCodeMapPK o = (JpJsicCodeMapPK) other;
    return this.isicCd.equals(o.isicCd) && this.isuCd.equals(o.isuCd) && this.jsicCd.equals(o.jsicCd) && this.subIndustryCd.equals(o.subIndustryCd);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;

    hash = hash * prime + (this.isicCd != null ? this.isicCd.hashCode() : 0);
    hash = hash * prime + (this.isuCd != null ? this.isuCd.hashCode() : 0);
    hash = hash * prime + (this.jsicCd != null ? this.jsicCd.hashCode() : 0);
    hash = hash * prime + (this.subIndustryCd != null ? this.subIndustryCd.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.isicCd) && !StringUtils.isEmpty(this.isuCd) && !StringUtils.isEmpty(this.jsicCd)
        && !StringUtils.isEmpty(this.subIndustryCd);

  }
}