/*
This file was automatically generated by the EntityCreator engine on Thu Jul 05 17:24:11 CST 2018.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the JP_JSIC_CODE_MAP database table.
 * 
 * @author XiangBinLiu
 */
@Entity
@Table(name = "JP_JSIC_CODE_MAP", schema = "CREQCMR")
public class JpJsicCodeMap extends BaseEntity<JpJsicCodeMapPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private JpJsicCodeMapPK id;

  public JpJsicCodeMapPK getId() {
    return id;
  }

  public void setId(JpJsicCodeMapPK id) {
    this.id = id;
  }
  
  @Column(name = "ISSUING_CNTRY")
  private String issuingCntry;

  @Column(name = "SECTOR_CD")
  private String sectorCd;

  @Column(name = "SUB_INDUSTRY_CD")
  private String subIndustryCd;

  @Column(name = "JSIC_CD")
  private String jsicCd;

  @Column(name = "ISIC_CD")
  private String isicCd;

  @Column(name = "ISU_CD")
  private String isuCd;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(name = "CREATE_BY")
  private String createBy;

  @Column(name = "UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updtTs;

  @Column(name = "UPDT_BY")
  private String updtBy;

  public String getIssuingCntry(){
    return this.issuingCntry;
  }

  public void setIssuingCntry(String issuingCntry){
    this.issuingCntry = issuingCntry;
  }


  public String getSectorCd(){
    return this.sectorCd;
  }

  public void setSectorCd(String sectorCd){
    this.sectorCd = sectorCd;
  }


  public String getSubIndustryCd(){
    return this.subIndustryCd;
  }

  public void setSubIndustryCd(String subIndustryCd){
    this.subIndustryCd = subIndustryCd;
  }


  public String getJsicCd(){
    return this.jsicCd;
  }

  public void setJsicCd(String jsicCd){
    this.jsicCd = jsicCd;
  }


  public String getIsicCd(){
    return this.isicCd;
  }

  public void setIsicCd(String isicCd){
    this.isicCd = isicCd;
  }


  public String getIsuCd(){
    return this.isuCd;
  }

  public void setIsuCd(String isuCd){
    this.isuCd = isuCd;
  }


  public Date getCreateTs(){
    return this.createTs;
  }

  public void setCreateTs(Date createTs){
    this.createTs = createTs;
  }


  public String getCreateBy(){
    return this.createBy;
  }

  public void setCreateBy(String createBy){
    this.createBy = createBy;
  }


  public Date getUpdtTs(){
    return this.updtTs;
  }

  public void setUpdtTs(Date updtTs){
    this.updtTs = updtTs;
  }


  public String getUpdtBy(){
    return this.updtBy;
  }

  public void setUpdtBy(String updtBy){
    this.updtBy = updtBy;
  }




}