/*
This file was automatically generated by the EntityCreator engine on Thu Jul 05 17:24:11 CST 2018.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the JP_JSIC_CODE_MAP database table.
 * 
 * @author XiangBinLiu
 */
@Entity
@Table(name = "JP_JSIC_CODE_MAP", schema = "CREQCMR")
public class JpJsicCodeMap extends BaseEntity<JpJsicCodeMapPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private JpJsicCodeMapPK id;

  @Override
  public JpJsicCodeMapPK getId() {
    return id;
  }

  @Override
  public void setId(JpJsicCodeMapPK id) {
    this.id = id;
  }

  @Column(name = "SECTOR_CD")
  private String sectorCd;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(name = "CREATE_BY")
  private String createBy;

  @Column(name = "UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateTs;

  @Column(name = "UPDT_BY")
  private String updateBy;

  public String getSectorCd() {
    return this.sectorCd;
  }

  public void setSectorCd(String sectorCd) {
    this.sectorCd = sectorCd;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getUpdateTs() {
    return this.updateTs;
  }

  public void setUpdateTs(Date updateTs) {
    this.updateTs = updateTs;
  }

  public String getUpdateBy() {
    return this.updateBy;
  }

  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

}