/*
This file was automatically generated by the EntityCreator engine on Thu Oct 06 14:23:13 SGT 2016.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Embeddable;

/**
 * The primary key class for the KNA1 database table.
 * 
 * @author 136771
 */
@Embeddable
public class Kna1PK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  private String mandt;

  private String kunnr;

  public String getMandt() {
    return this.mandt;
  }

  public void setMandt(String mandt) {
    this.mandt = mandt;
  }

  public String getKunnr() {
    return this.kunnr;
  }

  public void setKunnr(String kunnr) {
    this.kunnr = kunnr;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof Kna1PK)) {
      return false;
    }
    Kna1PK o = (Kna1PK) other;
    return this.mandt.equals(o.mandt) && this.kunnr.equals(o.kunnr);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.mandt != null ? this.mandt.hashCode() : 0);
    hash = hash * prime + (this.kunnr != null ? this.kunnr.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    // TODO Auto-generated method stub
    return false;
  }
}