/*
This file was automatically generated by the EntityCreator engine on Mon May 10 20:45:04 SGT 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the KNA1_ADDL_BILLING database table.
 * 
 * @author clint
 */
@Entity
@Table(
    name = "KNA1_ADDL_BILLING",
    schema = "SAPR3")
public class Kna1AddlBilling extends BaseEntity<Kna1AddlBillingPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private Kna1AddlBillingPK id;

  @Override
  public Kna1AddlBillingPK getId() {
    return id;
  }

  @Override
  public void setId(Kna1AddlBillingPK id) {
    this.id = id;
  }

  /**
   * Number of Invoices
   */
  @Column(
      name = "NO_OF_INVOICES")
  private String noOfInvoices;

  /**
   * Customer Bank Account Number
   */
  @Column(
      name = "BANK_ACCOUNT_NO")
  private String bankAccountNo;

  /**
   * Customer Bank Branch Number
   */
  @Column(
      name = "BANK_BRANCH_NO")
  private String bankBranchNo;

  /**
   * Quebec Sales Tax (QST) Number
   */
  @Column(
      name = "CA_QST_ID")
  private String caQstId;

  @Column(
      name = "CA_PST_ID")
  private String caPstId;

  /**
   * Leasing Company Indicator
   */
  @Column(
      name = "LEASING_INDC")
  private String leasingIndc;

  /**
   * Establishment Function Code
   */
  @Column(
      name = "ESTAB_FUNC_CD")
  private String estabFuncCd;

  /**
   * Purchase Order Number
   */
  @Column(
      name = "PURCH_ORDR_NO")
  private String purchOrdrNo;

  /**
   * Logical Delete Flag
   */
  private String loevm;

  /**
   * Created By
   */
  @Column(
      name = "CREATED_BY")
  private String createdBy;

  /**
   * Create Date
   */
  @Column(
      name = "CREATE_DT")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createDt;

  /**
   * Updated By
   */
  @Column(
      name = "UPDATED_BY")
  private String updatedBy;

  /**
   * Update Date
   */
  @Column(
      name = "UPDATE_DT")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateDt;

  /**
   * Update Type
   */
  @Column(
      name = "UPDATE_TYPE")
  private String updateType;

  @Column(
      name = "CODCOND")
  private String codCondition;

  @Column(
      name = "CODREAS")
  private String codReason;

  public String getNoOfInvoices() {
    return this.noOfInvoices;
  }

  public void setNoOfInvoices(String noOfInvoices) {
    this.noOfInvoices = noOfInvoices;
  }

  public String getBankAccountNo() {
    return this.bankAccountNo;
  }

  public void setBankAccountNo(String bankAccountNo) {
    this.bankAccountNo = bankAccountNo;
  }

  public String getBankBranchNo() {
    return this.bankBranchNo;
  }

  public void setBankBranchNo(String bankBranchNo) {
    this.bankBranchNo = bankBranchNo;
  }

  public String getCaQstId() {
    return this.caQstId;
  }

  public void setCaQstId(String caQstId) {
    this.caQstId = caQstId;
  }

  public String getCaPstId() {
    return this.caPstId;
  }

  public void setCaPstId(String caPstId) {
    this.caPstId = caPstId;
  }

  public String getLeasingIndc() {
    return this.leasingIndc;
  }

  public void setLeasingIndc(String leasingIndc) {
    this.leasingIndc = leasingIndc;
  }

  public String getEstabFuncCd() {
    return this.estabFuncCd;
  }

  public void setEstabFuncCd(String estabFuncCd) {
    this.estabFuncCd = estabFuncCd;
  }

  public String getPurchOrdrNo() {
    return this.purchOrdrNo;
  }

  public void setPurchOrdrNo(String purchOrdrNo) {
    this.purchOrdrNo = purchOrdrNo;
  }

  public String getLoevm() {
    return this.loevm;
  }

  public void setLoevm(String loevm) {
    this.loevm = loevm;
  }

  public String getCreatedBy() {
    return this.createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public Date getCreateDt() {
    return this.createDt;
  }

  public void setCreateDt(Date createDt) {
    this.createDt = createDt;
  }

  public String getUpdatedBy() {
    return this.updatedBy;
  }

  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }

  public Date getUpdateDt() {
    return this.updateDt;
  }

  public void setUpdateDt(Date updateDt) {
    this.updateDt = updateDt;
  }

  public String getUpdateType() {
    return this.updateType;
  }

  public void setUpdateType(String updateType) {
    this.updateType = updateType;
  }

  public String getCodCondition() {
    return codCondition;
  }

  public void setCodCondition(String codCondition) {
    this.codCondition = codCondition;
  }

  public String getCodReason() {
    return codReason;
  }

  public void setCodReason(String codReason) {
    this.codReason = codReason;
  }
}