/*
This file was automatically generated by the EntityCreator engine on Thu Oct 06 14:23:12 SGT 2016.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.ibm.cio.cmr.request.entity.listeners.ChangeLogListener;
import com.ibm.cio.cmr.request.entity.listeners.TrimListener;

/**
 * The persistent class for the KNA1 database table.
 * 
 * @author Dhananjay Yadav
 */
@Entity
@Table(name = "KNA1", schema = "SAPR3")
@EntityListeners({ TrimListener.class, ChangeLogListener.class })
public class Kna1 extends BaseEntity<Kna1PK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private Kna1PK id;

  public Kna1PK getId() {
    return id;
  }

  public void setId(Kna1PK id) {
    this.id = id;
  }

  private String adrnr;

  private String anred;

  private String aufsd;

  private String bahne;

  private String bahns;

  private String bbbnr;

  private String bbsnr;

  private String begru;

  private String brsch;

  private String bubkz;

  private String datlt;

  private String erdat;

  // @Transient
  private String ernam;

  private String exabl;

  private String faksd;

  private String fiskn;

  private String knazk;

  private String knrza;

  private String konzs;

  // @Transient
  private String ktokd;

  private String kukla;

  private String land1;

  private String lifnr;

  private String lifsd;

  private String locco;

  private String loevm;

  private String name1;

  private String name2;

  private String name3;

  private String name4;

  private String niels;

  private String ort01;

  private String ort02;

  private String pfach;

  private String pstl2;

  private String pstlz;

  private String regio;

  private String counc;

  private String cityc;

  private String rpmkr;

  private String sortl;

  private String sperr;

  private String spras;

  private String stcd1;

  private String stcd2;

  private String stkza;

  private String stkzu;

  private String stras;

  private String telbx;

  private String telf1;

  private String telf2;

  private String telfx;

  private String teltx;

  private String telx1;

  private String lzone;

  private String xcpdk;

  private String xzemp;

  private String vbund;

  private String stceg;

  private String dear1;

  private String dear2;

  private String dear3;

  private String dear4;

  private String dear5;

  private String gform;

  private String bran1;

  private String bran2;

  private String bran3;

  private String bran4;

  private String bran5;

  private String ekont;

  private double umsat = 0.00;

  private String umjah;

  private String uwaer;

  private String jmzah;

  private String jmjah;

  private String katr1;

  private String katr2;

  private String katr3;

  private String katr4;

  private String katr5;

  private String katr6;

  private String katr7;

  private String katr8;

  private String katr9;

  private String katr10;

  private String stkzn;

  private double umsa1 = 0.00;

  private String txjcd;

  private String mcod1;

  private String mcod2;

  private String mcod3;

  private String periv;

  private String abrvw;

  private String inspbydebi;

  private String inspatdebi;

  private String ktocd;

  private String pfort;

  private String werks;

  private String dtams;

  private String dtaws;

  private String duefl;

  private String hzuor;

  private String sperz;

  private String etikg;

  private String civve;

  private String milve;

  private String kdkg1;

  private String kdkg2;

  private String kdkg3;

  private String kdkg4;

  private String kdkg5;

  @Column(
      name = "ZZKV_LOTID")
  private String zzkvLotid;

  @Column(
      name = "ZZKV_SIC")
  private String zzkvSic;

  @Column(
      name = "ZZKV_LIC")
  private String zzkvLic;

  @Column(
      name = "ZZKV_CUSNO")
  private String zzkvCusno;

  @Column(
      name = "ZZKV_SEQNO")
  private String zzkvSeqno;

  @Column(
      name = "ZZKV_DEPT")
  private String zzkvDept;

  @Column(
      name = "ZZKV_INAC")
  private String zzkvInac;

  @Column(
      name = "ZZKV_INACT")
  private String zzkvInact;

  @Column(
      name = "ZZKV_DUNS")
  private String zzkvDuns;

  @Column(
      name = "ZZKV_NODE1")
  private String zzkvNode1;

  @Column(
      name = "ZZKV_NODE2")
  private String zzkvNode2;

  @Column(name = "SHAD_UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date shadUpdateTs;

  @Column(
      name = "SHAD_UPDATE_IND")
  private String shadUpdateInd;

  @Column(name = "SAP_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date sapTs;

  @Column(
      name = "ZZKV_ESTAB")
  private String zzkvEstab;

  @Column(
      name = "ZZKV_INTLOC")
  private String zzkvIntloc;

  @Column(
      name = "ZZKV_INTUSER")
  private String zzkvIntuser;

  @Column(
      name = "ZZKV_INTFUNC")
  private String zzkvIntfunc;

  @Column(
      name = "ZZKV_UC_STRT_ADDR")
  private String zzkvUcStrtAddr;

  @Column(
      name = "ZZKV_SNDX_NAME1")
  private String zzkvSndxName1;

  @Column(
      name = "ZZKV_ORG_FLG")
  private String zzkvOrgFlg;

  @Column(
      name = "RESTRICT_CD")
  private String restrictCd;

  @Column(
      name = "CREATE_OPT_NUM")
  private String createOptNum;

  @Column(
      name = "ZZKV_PARTYID")
  private String zzkvPartyid;

  @Transient
  private String userId;

  @Transient
  private boolean processed;

  @Transient
  private String legacyUse;

  public String getAdrnr() {
    return this.adrnr;
  }

  public void setAdrnr(String adrnr) {
    this.adrnr = adrnr;
  }

  public String getAnred() {
    return this.anred;
  }

  public void setAnred(String anred) {
    this.anred = anred;
  }

  public String getAufsd() {
    return this.aufsd;
  }

  public void setAufsd(String aufsd) {
    this.aufsd = aufsd;
  }

  public String getBahne() {
    return this.bahne;
  }

  public void setBahne(String bahne) {
    this.bahne = bahne;
  }

  public String getBahns() {
    return this.bahns;
  }

  public void setBahns(String bahns) {
    this.bahns = bahns;
  }

  public String getBbbnr() {
    return this.bbbnr;
  }

  public void setBbbnr(String bbbnr) {
    this.bbbnr = bbbnr;
  }

  public String getBbsnr() {
    return this.bbsnr;
  }

  public void setBbsnr(String bbsnr) {
    this.bbsnr = bbsnr;
  }

  public String getBegru() {
    return this.begru;
  }

  public void setBegru(String begru) {
    this.begru = begru;
  }

  public String getBrsch() {
    return this.brsch;
  }

  public void setBrsch(String brsch) {
    this.brsch = brsch;
  }

  public String getBubkz() {
    return this.bubkz;
  }

  public void setBubkz(String bubkz) {
    this.bubkz = bubkz;
  }

  public String getDatlt() {
    return this.datlt;
  }

  public void setDatlt(String datlt) {
    this.datlt = datlt;
  }

  public String getErdat() {
    return this.erdat;
  }

  public void setErdat(String erdat) {
    this.erdat = erdat;
  }

  public String getErnam() {
    return this.ernam;
  }

  public void setErnam(String ernam) {
    this.ernam = ernam;
  }

  public String getExabl() {
    return this.exabl;
  }

  public void setExabl(String exabl) {
    this.exabl = exabl;
  }

  public String getFaksd() {
    return this.faksd;
  }

  public void setFaksd(String faksd) {
    this.faksd = faksd;
  }

  public String getFiskn() {
    return this.fiskn;
  }

  public void setFiskn(String fiskn) {
    this.fiskn = fiskn;
  }

  public String getKnazk() {
    return this.knazk;
  }

  public void setKnazk(String knazk) {
    this.knazk = knazk;
  }

  public String getKnrza() {
    return this.knrza;
  }

  public void setKnrza(String knrza) {
    this.knrza = knrza;
  }

  public String getKonzs() {
    return this.konzs;
  }

  public void setKonzs(String konzs) {
    this.konzs = konzs;
  }

  public String getKtokd() {
    return this.ktokd;
  }

  public void setKtokd(String ktokd) {
    this.ktokd = ktokd;
  }

  public String getKukla() {
    return this.kukla;
  }

  public void setKukla(String kukla) {
    this.kukla = kukla;
  }

  public String getLand1() {
    return this.land1;
  }

  public void setLand1(String land1) {
    this.land1 = land1;
  }

  public String getLifnr() {
    return this.lifnr;
  }

  public void setLifnr(String lifnr) {
    this.lifnr = lifnr;
  }

  public String getLifsd() {
    return this.lifsd;
  }

  public void setLifsd(String lifsd) {
    this.lifsd = lifsd;
  }

  public String getLocco() {
    return this.locco;
  }

  public void setLocco(String locco) {
    this.locco = locco;
  }

  public String getLoevm() {
    return this.loevm;
  }

  public void setLoevm(String loevm) {
    this.loevm = loevm;
  }

  public String getName1() {
    return this.name1;
  }

  public void setName1(String name1) {
    this.name1 = name1;
  }

  public String getName2() {
    return this.name2;
  }

  public void setName2(String name2) {
    this.name2 = name2;
  }

  public String getName3() {
    return this.name3;
  }

  public void setName3(String name3) {
    this.name3 = name3;
  }

  public String getName4() {
    return this.name4;
  }

  public void setName4(String name4) {
    this.name4 = name4;
  }

  public String getNiels() {
    return this.niels;
  }

  public void setNiels(String niels) {
    this.niels = niels;
  }

  public String getOrt01() {
    return this.ort01;
  }

  public void setOrt01(String ort01) {
    this.ort01 = ort01;
  }

  public String getOrt02() {
    return this.ort02;
  }

  public void setOrt02(String ort02) {
    this.ort02 = ort02;
  }

  public String getPfach() {
    return this.pfach;
  }

  public void setPfach(String pfach) {
    this.pfach = pfach;
  }

  public String getPstl2() {
    return this.pstl2;
  }

  public void setPstl2(String pstl2) {
    this.pstl2 = pstl2;
  }

  public String getPstlz() {
    return this.pstlz;
  }

  public void setPstlz(String pstlz) {
    this.pstlz = pstlz;
  }

  public String getRegio() {
    return this.regio;
  }

  public void setRegio(String regio) {
    this.regio = regio;
  }

  public String getCounc() {
    return this.counc;
  }

  public void setCounc(String counc) {
    this.counc = counc;
  }

  public String getCityc() {
    return this.cityc;
  }

  public void setCityc(String cityc) {
    this.cityc = cityc;
  }

  public String getRpmkr() {
    return this.rpmkr;
  }

  public void setRpmkr(String rpmkr) {
    this.rpmkr = rpmkr;
  }

  public String getSortl() {
    return this.sortl;
  }

  public void setSortl(String sortl) {
    this.sortl = sortl;
  }

  public String getSperr() {
    return this.sperr;
  }

  public void setSperr(String sperr) {
    this.sperr = sperr;
  }

  public String getSpras() {
    return this.spras;
  }

  public void setSpras(String spras) {
    this.spras = spras;
  }

  public String getStcd1() {
    return this.stcd1;
  }

  public void setStcd1(String stcd1) {
    this.stcd1 = stcd1;
  }

  public String getStcd2() {
    return this.stcd2;
  }

  public void setStcd2(String stcd2) {
    this.stcd2 = stcd2;
  }

  public String getStkza() {
    return this.stkza;
  }

  public void setStkza(String stkza) {
    this.stkza = stkza;
  }

  public String getStkzu() {
    return this.stkzu;
  }

  public void setStkzu(String stkzu) {
    this.stkzu = stkzu;
  }

  public String getStras() {
    return this.stras;
  }

  public void setStras(String stras) {
    this.stras = stras;
  }

  public String getTelbx() {
    return this.telbx;
  }

  public void setTelbx(String telbx) {
    this.telbx = telbx;
  }

  public String getTelf1() {
    return this.telf1;
  }

  public void setTelf1(String telf1) {
    this.telf1 = telf1;
  }

  public String getTelf2() {
    return this.telf2;
  }

  public void setTelf2(String telf2) {
    this.telf2 = telf2;
  }

  public String getTelfx() {
    return this.telfx;
  }

  public void setTelfx(String telfx) {
    this.telfx = telfx;
  }

  public String getTeltx() {
    return this.teltx;
  }

  public void setTeltx(String teltx) {
    this.teltx = teltx;
  }

  public String getTelx1() {
    return this.telx1;
  }

  public void setTelx1(String telx1) {
    this.telx1 = telx1;
  }

  public String getLzone() {
    return this.lzone;
  }

  public void setLzone(String lzone) {
    this.lzone = lzone;
  }

  public String getXcpdk() {
    return this.xcpdk;
  }

  public void setXcpdk(String xcpdk) {
    this.xcpdk = xcpdk;
  }

  public String getXzemp() {
    return this.xzemp;
  }

  public void setXzemp(String xzemp) {
    this.xzemp = xzemp;
  }

  public String getVbund() {
    return this.vbund;
  }

  public void setVbund(String vbund) {
    this.vbund = vbund;
  }

  public String getStceg() {
    return this.stceg;
  }

  public void setStceg(String stceg) {
    this.stceg = stceg;
  }

  public String getDear1() {
    return this.dear1;
  }

  public void setDear1(String dear1) {
    this.dear1 = dear1;
  }

  public String getDear2() {
    return this.dear2;
  }

  public void setDear2(String dear2) {
    this.dear2 = dear2;
  }

  public String getDear3() {
    return this.dear3;
  }

  public void setDear3(String dear3) {
    this.dear3 = dear3;
  }

  public String getDear4() {
    return this.dear4;
  }

  public void setDear4(String dear4) {
    this.dear4 = dear4;
  }

  public String getDear5() {
    return this.dear5;
  }

  public void setDear5(String dear5) {
    this.dear5 = dear5;
  }

  public String getGform() {
    return this.gform;
  }

  public void setGform(String gform) {
    this.gform = gform;
  }

  public String getBran1() {
    return this.bran1;
  }

  public void setBran1(String bran1) {
    this.bran1 = bran1;
  }

  public String getBran2() {
    return this.bran2;
  }

  public void setBran2(String bran2) {
    this.bran2 = bran2;
  }

  public String getBran3() {
    return this.bran3;
  }

  public void setBran3(String bran3) {
    this.bran3 = bran3;
  }

  public String getBran4() {
    return this.bran4;
  }

  public void setBran4(String bran4) {
    this.bran4 = bran4;
  }

  public String getBran5() {
    return this.bran5;
  }

  public void setBran5(String bran5) {
    this.bran5 = bran5;
  }

  public String getEkont() {
    return this.ekont;
  }

  public void setEkont(String ekont) {
    this.ekont = ekont;
  }

  public String getUmjah() {
    return this.umjah;
  }

  public void setUmjah(String umjah) {
    this.umjah = umjah;
  }

  public String getUwaer() {
    return this.uwaer;
  }

  public void setUwaer(String uwaer) {
    this.uwaer = uwaer;
  }

  public String getJmzah() {
    return this.jmzah;
  }

  public void setJmzah(String jmzah) {
    this.jmzah = jmzah;
  }

  public String getJmjah() {
    return this.jmjah;
  }

  public void setJmjah(String jmjah) {
    this.jmjah = jmjah;
  }

  public String getKatr1() {
    return this.katr1;
  }

  public void setKatr1(String katr1) {
    this.katr1 = katr1;
  }

  public String getKatr2() {
    return this.katr2;
  }

  public void setKatr2(String katr2) {
    this.katr2 = katr2;
  }

  public String getKatr3() {
    return this.katr3;
  }

  public void setKatr3(String katr3) {
    this.katr3 = katr3;
  }

  public String getKatr4() {
    return this.katr4;
  }

  public void setKatr4(String katr4) {
    this.katr4 = katr4;
  }

  public String getKatr5() {
    return this.katr5;
  }

  public void setKatr5(String katr5) {
    this.katr5 = katr5;
  }

  public String getKatr6() {
    return this.katr6;
  }

  public void setKatr6(String katr6) {
    this.katr6 = katr6;
  }

  public String getKatr7() {
    return this.katr7;
  }

  public void setKatr7(String katr7) {
    this.katr7 = katr7;
  }

  public String getKatr8() {
    return this.katr8;
  }

  public void setKatr8(String katr8) {
    this.katr8 = katr8;
  }

  public String getKatr9() {
    return this.katr9;
  }

  public void setKatr9(String katr9) {
    this.katr9 = katr9;
  }

  public String getKatr10() {
    return this.katr10;
  }

  public void setKatr10(String katr10) {
    this.katr10 = katr10;
  }

  public String getStkzn() {
    return this.stkzn;
  }

  public void setStkzn(String stkzn) {
    this.stkzn = stkzn;
  }

  public String getTxjcd() {
    return this.txjcd;
  }

  public void setTxjcd(String txjcd) {
    this.txjcd = txjcd;
  }

  public String getMcod1() {
    return this.mcod1;
  }

  public void setMcod1(String mcod1) {
    this.mcod1 = mcod1;
  }

  public String getMcod2() {
    return this.mcod2;
  }

  public void setMcod2(String mcod2) {
    this.mcod2 = mcod2;
  }

  public String getMcod3() {
    return this.mcod3;
  }

  public void setMcod3(String mcod3) {
    this.mcod3 = mcod3;
  }

  public String getPeriv() {
    return this.periv;
  }

  public void setPeriv(String periv) {
    this.periv = periv;
  }

  public String getAbrvw() {
    return this.abrvw;
  }

  public void setAbrvw(String abrvw) {
    this.abrvw = abrvw;
  }

  public String getInspbydebi() {
    return this.inspbydebi;
  }

  public void setInspbydebi(String inspbydebi) {
    this.inspbydebi = inspbydebi;
  }

  public String getInspatdebi() {
    return this.inspatdebi;
  }

  public void setInspatdebi(String inspatdebi) {
    this.inspatdebi = inspatdebi;
  }

  public String getKtocd() {
    return this.ktocd;
  }

  public void setKtocd(String ktocd) {
    this.ktocd = ktocd;
  }

  public String getPfort() {
    return this.pfort;
  }

  public void setPfort(String pfort) {
    this.pfort = pfort;
  }

  public String getWerks() {
    return this.werks;
  }

  public void setWerks(String werks) {
    this.werks = werks;
  }

  public String getDtams() {
    return this.dtams;
  }

  public void setDtams(String dtams) {
    this.dtams = dtams;
  }

  public String getDtaws() {
    return this.dtaws;
  }

  public void setDtaws(String dtaws) {
    this.dtaws = dtaws;
  }

  public String getDuefl() {
    return this.duefl;
  }

  public void setDuefl(String duefl) {
    this.duefl = duefl;
  }

  public String getHzuor() {
    return this.hzuor;
  }

  public void setHzuor(String hzuor) {
    this.hzuor = hzuor;
  }

  public String getSperz() {
    return this.sperz;
  }

  public void setSperz(String sperz) {
    this.sperz = sperz;
  }

  public String getEtikg() {
    return this.etikg;
  }

  public void setEtikg(String etikg) {
    this.etikg = etikg;
  }

  public String getCivve() {
    return this.civve;
  }

  public void setCivve(String civve) {
    this.civve = civve;
  }

  public String getMilve() {
    return this.milve;
  }

  public void setMilve(String milve) {
    this.milve = milve;
  }

  public String getKdkg1() {
    return this.kdkg1;
  }

  public void setKdkg1(String kdkg1) {
    this.kdkg1 = kdkg1;
  }

  public String getKdkg2() {
    return this.kdkg2;
  }

  public void setKdkg2(String kdkg2) {
    this.kdkg2 = kdkg2;
  }

  public String getKdkg3() {
    return this.kdkg3;
  }

  public void setKdkg3(String kdkg3) {
    this.kdkg3 = kdkg3;
  }

  public String getKdkg4() {
    return this.kdkg4;
  }

  public void setKdkg4(String kdkg4) {
    this.kdkg4 = kdkg4;
  }

  public String getKdkg5() {
    return this.kdkg5;
  }

  public void setKdkg5(String kdkg5) {
    this.kdkg5 = kdkg5;
  }

  public String getZzkvLotid() {
    return this.zzkvLotid;
  }

  public void setZzkvLotid(String zzkvLotid) {
    this.zzkvLotid = zzkvLotid;
  }

  public String getZzkvSic() {
    return this.zzkvSic;
  }

  public void setZzkvSic(String zzkvSic) {
    this.zzkvSic = zzkvSic;
  }

  public String getZzkvLic() {
    return this.zzkvLic;
  }

  public void setZzkvLic(String zzkvLic) {
    this.zzkvLic = zzkvLic;
  }

  public String getZzkvCusno() {
    return this.zzkvCusno;
  }

  public void setZzkvCusno(String zzkvCusno) {
    this.zzkvCusno = zzkvCusno;
  }

  public String getZzkvSeqno() {
    return this.zzkvSeqno;
  }

  public void setZzkvSeqno(String zzkvSeqno) {
    this.zzkvSeqno = zzkvSeqno;
  }

  public String getZzkvDept() {
    return this.zzkvDept;
  }

  public void setZzkvDept(String zzkvDept) {
    this.zzkvDept = zzkvDept;
  }

  public String getZzkvInac() {
    return this.zzkvInac;
  }

  public void setZzkvInac(String zzkvInac) {
    this.zzkvInac = zzkvInac;
  }

  public String getZzkvInact() {
    return this.zzkvInact;
  }

  public void setZzkvInact(String zzkvInact) {
    this.zzkvInact = zzkvInact;
  }

  public String getZzkvDuns() {
    return this.zzkvDuns;
  }

  public void setZzkvDuns(String zzkvDuns) {
    this.zzkvDuns = zzkvDuns;
  }

  public String getZzkvNode1() {
    return this.zzkvNode1;
  }

  public void setZzkvNode1(String zzkvNode1) {
    this.zzkvNode1 = zzkvNode1;
  }

  public String getZzkvNode2() {
    return this.zzkvNode2;
  }

  public void setZzkvNode2(String zzkvNode2) {
    this.zzkvNode2 = zzkvNode2;
  }

  public Date getShadUpdateTs() {
    return this.shadUpdateTs;
  }

  public void setShadUpdateTs(Date shadUpdateTs) {
    this.shadUpdateTs = shadUpdateTs;
  }

  public String getShadUpdateInd() {
    return this.shadUpdateInd;
  }

  public void setShadUpdateInd(String shadUpdateInd) {
    this.shadUpdateInd = shadUpdateInd;
  }

  public Date getSapTs() {
    return this.sapTs;
  }

  public void setSapTs(Date sapTs) {
    this.sapTs = sapTs;
  }

  public String getZzkvEstab() {
    return this.zzkvEstab;
  }

  public void setZzkvEstab(String zzkvEstab) {
    this.zzkvEstab = zzkvEstab;
  }

  public String getZzkvIntloc() {
    return this.zzkvIntloc;
  }

  public void setZzkvIntloc(String zzkvIntloc) {
    this.zzkvIntloc = zzkvIntloc;
  }

  public String getZzkvIntuser() {
    return this.zzkvIntuser;
  }

  public void setZzkvIntuser(String zzkvIntuser) {
    this.zzkvIntuser = zzkvIntuser;
  }

  public String getZzkvIntfunc() {
    return this.zzkvIntfunc;
  }

  public void setZzkvIntfunc(String zzkvIntfunc) {
    this.zzkvIntfunc = zzkvIntfunc;
  }

  public String getZzkvUcStrtAddr() {
    return this.zzkvUcStrtAddr;
  }

  public void setZzkvUcStrtAddr(String zzkvUcStrtAddr) {
    this.zzkvUcStrtAddr = zzkvUcStrtAddr;
  }

  public String getZzkvSndxName1() {
    return this.zzkvSndxName1;
  }

  public void setZzkvSndxName1(String zzkvSndxName1) {
    this.zzkvSndxName1 = zzkvSndxName1;
  }

  public String getZzkvOrgFlg() {
    return this.zzkvOrgFlg;
  }

  public void setZzkvOrgFlg(String zzkvOrgFlg) {
    this.zzkvOrgFlg = zzkvOrgFlg;
  }

  public String getRestrictCd() {
    return this.restrictCd;
  }

  public void setRestrictCd(String restrictCd) {
    this.restrictCd = restrictCd;
  }

  public String getCreateOptNum() {
    return this.createOptNum;
  }

  public void setCreateOptNum(String createOptNum) {
    this.createOptNum = createOptNum;
  }

  public String getZzkvPartyid() {
    return this.zzkvPartyid;
  }

  public void setZzkvPartyid(String zzkvPartyid) {
    this.zzkvPartyid = zzkvPartyid;
  }

  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public boolean isProcessed() {
    return processed;
  }

  public void setProcessed(boolean processed) {
    this.processed = processed;
  }

  public double getUmsat() {
    return umsat;
  }

  public void setUmsat(double umsat) {
    this.umsat = umsat;
  }

  public double getUmsa1() {
    return umsa1;
  }

  public void setUmsa1(double umsa1) {
    this.umsa1 = umsa1;
  }

  public String getLegacyUse() {
    return legacyUse;
  }

  public void setLegacyUse(String legacyUse) {
    this.legacyUse = legacyUse;
  }

}