/*
This file was automatically generated by the EntityCreator engine on Tue Feb 02 17:15:58 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang3.StringUtils;

/**
 * The primary key class for the KNEX database table.
 * 
 * @author PriyRanjan
 */
@Embeddable
public class KnexPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  /** 
   * SAP instance
   */ 
  private String mandt;

  /** 
   * SAP Customer number
   */ 
  private String kunnr;

  private String lndex;

  public String getMandt(){
    return this.mandt;
  }

  public void setMandt(String mandt){
    this.mandt = mandt;
  }


  public String getKunnr(){
    return this.kunnr;
  }

  public void setKunnr(String kunnr){
    this.kunnr = kunnr;
  }


  public String getLndex(){
    return this.lndex;
  }

  public void setLndex(String lndex){
    this.lndex = lndex;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof KnexPK)) {
      return false;
    }
    KnexPK o = (KnexPK) other;
    return this.mandt.equals(o.mandt) && this.kunnr.equals(o.kunnr) && this.lndex.equals(o.lndex);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.mandt != null ? this.mandt.hashCode() : 0);
    hash = hash * prime + (this.kunnr != null ? this.kunnr.hashCode() : 0);
    hash = hash * prime + (this.lndex != null ? this.lndex.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.mandt) && !StringUtils.isEmpty(this.kunnr) && !StringUtils.isEmpty(this.lndex);

  }
}