/*
This file was automatically generated by the EntityCreator engine on Tue Feb 02 17:15:58 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the KNEX database table.
 * 
 * @author PriyRanjan
 */
@Entity
@Table(name = "KNEX", schema = "SAPR3")
public class Knex extends BaseEntity<KnexPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private KnexPK id;

  public KnexPK getId() {
    return id;
  }

  public void setId(KnexPK id) {
    this.id = id;
  }
  
  private String tdoco;

  private String tdoda;

  private String sdnco;

  private String sdnda;

  private String dhrco;

  private String dhrda;

  private String bl1co;

  private String bl1da;

  private String bl2co;

  private String bl2da;

  /** 
   * Last updated date
   */ 
  @Column(name = "SHAD_UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date shadUpdateTs;

  /** 
   * Update Type
   */ 
  @Column(name = "SHAD_UPDATE_IND")
  private String shadUpdateInd;

  /** 
   * Last updated date
   */ 
  @Column(name = "SAP_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date sapTs;

  public String getTdoco(){
    return this.tdoco;
  }

  public void setTdoco(String tdoco){
    this.tdoco = tdoco;
  }


  public String getTdoda(){
    return this.tdoda;
  }

  public void setTdoda(String tdoda){
    this.tdoda = tdoda;
  }


  public String getSdnco(){
    return this.sdnco;
  }

  public void setSdnco(String sdnco){
    this.sdnco = sdnco;
  }


  public String getSdnda(){
    return this.sdnda;
  }

  public void setSdnda(String sdnda){
    this.sdnda = sdnda;
  }


  public String getDhrco(){
    return this.dhrco;
  }

  public void setDhrco(String dhrco){
    this.dhrco = dhrco;
  }


  public String getDhrda(){
    return this.dhrda;
  }

  public void setDhrda(String dhrda){
    this.dhrda = dhrda;
  }


  public String getBl1co(){
    return this.bl1co;
  }

  public void setBl1co(String bl1co){
    this.bl1co = bl1co;
  }


  public String getBl1da(){
    return this.bl1da;
  }

  public void setBl1da(String bl1da){
    this.bl1da = bl1da;
  }


  public String getBl2co(){
    return this.bl2co;
  }

  public void setBl2co(String bl2co){
    this.bl2co = bl2co;
  }


  public String getBl2da(){
    return this.bl2da;
  }

  public void setBl2da(String bl2da){
    this.bl2da = bl2da;
  }


  public Date getShadUpdateTs(){
    return this.shadUpdateTs;
  }

  public void setShadUpdateTs(Date shadUpdateTs){
    this.shadUpdateTs = shadUpdateTs;
  }


  public String getShadUpdateInd(){
    return this.shadUpdateInd;
  }

  public void setShadUpdateInd(String shadUpdateInd){
    this.shadUpdateInd = shadUpdateInd;
  }


  public Date getSapTs(){
    return this.sapTs;
  }

  public void setSapTs(Date sapTs){
    this.sapTs = sapTs;
  }




}