/*
This file was automatically generated by the EntityCreator engine on Tue Feb 02 17:14:27 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang3.StringUtils;

/**
 * The primary key class for the KNVI database table.
 * 
 * @author PriyRanjan
 */
@Embeddable
public class KnviPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  /** 
   * SAP instance
   */ 
  private String mandt;

  /** 
   * SAP Customer number
   */ 
  private String kunnr;

  /** 
   * Departure Country
   */ 
  private String aland;

  /** 
   * Tax Category
   */ 
  private String tatyp;

  public String getMandt(){
    return this.mandt;
  }

  public void setMandt(String mandt){
    this.mandt = mandt;
  }


  public String getKunnr(){
    return this.kunnr;
  }

  public void setKunnr(String kunnr){
    this.kunnr = kunnr;
  }


  public String getAland(){
    return this.aland;
  }

  public void setAland(String aland){
    this.aland = aland;
  }


  public String getTatyp(){
    return this.tatyp;
  }

  public void setTatyp(String tatyp){
    this.tatyp = tatyp;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof KnviPK)) {
      return false;
    }
    KnviPK o = (KnviPK) other;
    return this.mandt.equals(o.mandt) && this.kunnr.equals(o.kunnr) && this.aland.equals(o.aland) && this.tatyp.equals(o.tatyp);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.mandt != null ? this.mandt.hashCode() : 0);
    hash = hash * prime + (this.kunnr != null ? this.kunnr.hashCode() : 0);
    hash = hash * prime + (this.aland != null ? this.aland.hashCode() : 0);
    hash = hash * prime + (this.tatyp != null ? this.tatyp.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.mandt) && !StringUtils.isEmpty(this.kunnr) && !StringUtils.isEmpty(this.aland) && !StringUtils.isEmpty(this.tatyp);

  }
}