/*
This file was automatically generated by the EntityCreator engine on Tue Feb 02 17:14:59 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the KNVK database table.
 * 
 * @author PriyRanjan
 */
@Entity
@Table(name = "KNVK", schema = "SAPR3")
public class Knvk extends BaseEntity<KnvkPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private KnvkPK id;

  public KnvkPK getId() {
    return id;
  }

  public void setId(KnvkPK id) {
    this.id = id;
  }
  
  /** 
   * SAP Customer number
   */ 
  private String kunnr;

  private String namev;

  /** 
   * Customer Name
   */ 
  private String name1;

  /** 
   * City
   */ 
  private String ort01;

  private String adrnd;

  private String adrnp;

  private String abtpa;

  /** 
   * Contact person department
   */ 
  private String abtnr;

  private String uepar;

  private String telf1;

  private String anred;

  private String pafkt;

  private String parvo;

  private String pavip;

  private String parge;

  private String parla;

  private String gbdat;

  private String vrtnr;

  private String bryth;

  private String akver;

  private String nmail;

  /** 
   * Notes about contact person
   */ 
  private String parau;

  private String parh1;

  private String parh2;

  private String parh3;

  private String parh4;

  private String parh5;

  private String moab1;

  private String mobi1;

  private String moab2;

  private String mobi2;

  private String diab1;

  private String dibi1;

  private String diab2;

  private String dibi2;

  private String miab1;

  private String mibi1;

  private String miab2;

  private String mibi2;

  private String doab1;

  private String dobi1;

  private String doab2;

  private String dobi2;

  private String frab1;

  private String frbi1;

  private String frab2;

  private String frbi2;

  private String saab1;

  private String sabi1;

  private String saab2;

  private String sabi2;

  private String soab1;

  private String sobi1;

  private String soab2;

  private String sobi2;

  private String pakn1;

  private String pakn2;

  private String pakn3;

  private String pakn4;

  private String pakn5;

  /** 
   * Customer search text
   */ 
  private String sortl;

  /** 
   * Marital status key
   */ 
  private String famst;

  private String spnam;

  @Column(name = "TITEL_AP")
  private String titelAp;

  /** 
   * Created date
   */ 
  private String erdat;

  /** 
   * Created by user
   */ 
  private String ernam;

  private String duefl;

  private String lifnr;

  /** 
   * Last updated date
   */ 
  @Column(name = "SHAD_UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date shadUpdateTs;

  /** 
   * Update Type
   */ 
  @Column(name = "SHAD_UPDATE_IND")
  private String shadUpdateInd;

  /** 
   * Last updated date
   */ 
  @Column(name = "SAP_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date sapTs;

  private String titel;

  public String getKunnr(){
    return this.kunnr;
  }

  public void setKunnr(String kunnr){
    this.kunnr = kunnr;
  }


  public String getNamev(){
    return this.namev;
  }

  public void setNamev(String namev){
    this.namev = namev;
  }


  public String getName1(){
    return this.name1;
  }

  public void setName1(String name1){
    this.name1 = name1;
  }


  public String getOrt01(){
    return this.ort01;
  }

  public void setOrt01(String ort01){
    this.ort01 = ort01;
  }


  public String getAdrnd(){
    return this.adrnd;
  }

  public void setAdrnd(String adrnd){
    this.adrnd = adrnd;
  }


  public String getAdrnp(){
    return this.adrnp;
  }

  public void setAdrnp(String adrnp){
    this.adrnp = adrnp;
  }


  public String getAbtpa(){
    return this.abtpa;
  }

  public void setAbtpa(String abtpa){
    this.abtpa = abtpa;
  }


  public String getAbtnr(){
    return this.abtnr;
  }

  public void setAbtnr(String abtnr){
    this.abtnr = abtnr;
  }


  public String getUepar(){
    return this.uepar;
  }

  public void setUepar(String uepar){
    this.uepar = uepar;
  }


  public String getTelf1(){
    return this.telf1;
  }

  public void setTelf1(String telf1){
    this.telf1 = telf1;
  }


  public String getAnred(){
    return this.anred;
  }

  public void setAnred(String anred){
    this.anred = anred;
  }


  public String getPafkt(){
    return this.pafkt;
  }

  public void setPafkt(String pafkt){
    this.pafkt = pafkt;
  }


  public String getParvo(){
    return this.parvo;
  }

  public void setParvo(String parvo){
    this.parvo = parvo;
  }


  public String getPavip(){
    return this.pavip;
  }

  public void setPavip(String pavip){
    this.pavip = pavip;
  }


  public String getParge(){
    return this.parge;
  }

  public void setParge(String parge){
    this.parge = parge;
  }


  public String getParla(){
    return this.parla;
  }

  public void setParla(String parla){
    this.parla = parla;
  }


  public String getGbdat(){
    return this.gbdat;
  }

  public void setGbdat(String gbdat){
    this.gbdat = gbdat;
  }


  public String getVrtnr(){
    return this.vrtnr;
  }

  public void setVrtnr(String vrtnr){
    this.vrtnr = vrtnr;
  }


  public String getBryth(){
    return this.bryth;
  }

  public void setBryth(String bryth){
    this.bryth = bryth;
  }


  public String getAkver(){
    return this.akver;
  }

  public void setAkver(String akver){
    this.akver = akver;
  }


  public String getNmail(){
    return this.nmail;
  }

  public void setNmail(String nmail){
    this.nmail = nmail;
  }


  public String getParau(){
    return this.parau;
  }

  public void setParau(String parau){
    this.parau = parau;
  }


  public String getParh1(){
    return this.parh1;
  }

  public void setParh1(String parh1){
    this.parh1 = parh1;
  }


  public String getParh2(){
    return this.parh2;
  }

  public void setParh2(String parh2){
    this.parh2 = parh2;
  }


  public String getParh3(){
    return this.parh3;
  }

  public void setParh3(String parh3){
    this.parh3 = parh3;
  }


  public String getParh4(){
    return this.parh4;
  }

  public void setParh4(String parh4){
    this.parh4 = parh4;
  }


  public String getParh5(){
    return this.parh5;
  }

  public void setParh5(String parh5){
    this.parh5 = parh5;
  }


  public String getMoab1(){
    return this.moab1;
  }

  public void setMoab1(String moab1){
    this.moab1 = moab1;
  }


  public String getMobi1(){
    return this.mobi1;
  }

  public void setMobi1(String mobi1){
    this.mobi1 = mobi1;
  }


  public String getMoab2(){
    return this.moab2;
  }

  public void setMoab2(String moab2){
    this.moab2 = moab2;
  }


  public String getMobi2(){
    return this.mobi2;
  }

  public void setMobi2(String mobi2){
    this.mobi2 = mobi2;
  }


  public String getDiab1(){
    return this.diab1;
  }

  public void setDiab1(String diab1){
    this.diab1 = diab1;
  }


  public String getDibi1(){
    return this.dibi1;
  }

  public void setDibi1(String dibi1){
    this.dibi1 = dibi1;
  }


  public String getDiab2(){
    return this.diab2;
  }

  public void setDiab2(String diab2){
    this.diab2 = diab2;
  }


  public String getDibi2(){
    return this.dibi2;
  }

  public void setDibi2(String dibi2){
    this.dibi2 = dibi2;
  }


  public String getMiab1(){
    return this.miab1;
  }

  public void setMiab1(String miab1){
    this.miab1 = miab1;
  }


  public String getMibi1(){
    return this.mibi1;
  }

  public void setMibi1(String mibi1){
    this.mibi1 = mibi1;
  }


  public String getMiab2(){
    return this.miab2;
  }

  public void setMiab2(String miab2){
    this.miab2 = miab2;
  }


  public String getMibi2(){
    return this.mibi2;
  }

  public void setMibi2(String mibi2){
    this.mibi2 = mibi2;
  }


  public String getDoab1(){
    return this.doab1;
  }

  public void setDoab1(String doab1){
    this.doab1 = doab1;
  }


  public String getDobi1(){
    return this.dobi1;
  }

  public void setDobi1(String dobi1){
    this.dobi1 = dobi1;
  }


  public String getDoab2(){
    return this.doab2;
  }

  public void setDoab2(String doab2){
    this.doab2 = doab2;
  }


  public String getDobi2(){
    return this.dobi2;
  }

  public void setDobi2(String dobi2){
    this.dobi2 = dobi2;
  }


  public String getFrab1(){
    return this.frab1;
  }

  public void setFrab1(String frab1){
    this.frab1 = frab1;
  }


  public String getFrbi1(){
    return this.frbi1;
  }

  public void setFrbi1(String frbi1){
    this.frbi1 = frbi1;
  }


  public String getFrab2(){
    return this.frab2;
  }

  public void setFrab2(String frab2){
    this.frab2 = frab2;
  }


  public String getFrbi2(){
    return this.frbi2;
  }

  public void setFrbi2(String frbi2){
    this.frbi2 = frbi2;
  }


  public String getSaab1(){
    return this.saab1;
  }

  public void setSaab1(String saab1){
    this.saab1 = saab1;
  }


  public String getSabi1(){
    return this.sabi1;
  }

  public void setSabi1(String sabi1){
    this.sabi1 = sabi1;
  }


  public String getSaab2(){
    return this.saab2;
  }

  public void setSaab2(String saab2){
    this.saab2 = saab2;
  }


  public String getSabi2(){
    return this.sabi2;
  }

  public void setSabi2(String sabi2){
    this.sabi2 = sabi2;
  }


  public String getSoab1(){
    return this.soab1;
  }

  public void setSoab1(String soab1){
    this.soab1 = soab1;
  }


  public String getSobi1(){
    return this.sobi1;
  }

  public void setSobi1(String sobi1){
    this.sobi1 = sobi1;
  }


  public String getSoab2(){
    return this.soab2;
  }

  public void setSoab2(String soab2){
    this.soab2 = soab2;
  }


  public String getSobi2(){
    return this.sobi2;
  }

  public void setSobi2(String sobi2){
    this.sobi2 = sobi2;
  }


  public String getPakn1(){
    return this.pakn1;
  }

  public void setPakn1(String pakn1){
    this.pakn1 = pakn1;
  }


  public String getPakn2(){
    return this.pakn2;
  }

  public void setPakn2(String pakn2){
    this.pakn2 = pakn2;
  }


  public String getPakn3(){
    return this.pakn3;
  }

  public void setPakn3(String pakn3){
    this.pakn3 = pakn3;
  }


  public String getPakn4(){
    return this.pakn4;
  }

  public void setPakn4(String pakn4){
    this.pakn4 = pakn4;
  }


  public String getPakn5(){
    return this.pakn5;
  }

  public void setPakn5(String pakn5){
    this.pakn5 = pakn5;
  }


  public String getSortl(){
    return this.sortl;
  }

  public void setSortl(String sortl){
    this.sortl = sortl;
  }


  public String getFamst(){
    return this.famst;
  }

  public void setFamst(String famst){
    this.famst = famst;
  }


  public String getSpnam(){
    return this.spnam;
  }

  public void setSpnam(String spnam){
    this.spnam = spnam;
  }


  public String getTitelAp(){
    return this.titelAp;
  }

  public void setTitelAp(String titelAp){
    this.titelAp = titelAp;
  }


  public String getErdat(){
    return this.erdat;
  }

  public void setErdat(String erdat){
    this.erdat = erdat;
  }


  public String getErnam(){
    return this.ernam;
  }

  public void setErnam(String ernam){
    this.ernam = ernam;
  }


  public String getDuefl(){
    return this.duefl;
  }

  public void setDuefl(String duefl){
    this.duefl = duefl;
  }


  public String getLifnr(){
    return this.lifnr;
  }

  public void setLifnr(String lifnr){
    this.lifnr = lifnr;
  }


  public Date getShadUpdateTs(){
    return this.shadUpdateTs;
  }

  public void setShadUpdateTs(Date shadUpdateTs){
    this.shadUpdateTs = shadUpdateTs;
  }


  public String getShadUpdateInd(){
    return this.shadUpdateInd;
  }

  public void setShadUpdateInd(String shadUpdateInd){
    this.shadUpdateInd = shadUpdateInd;
  }


  public Date getSapTs(){
    return this.sapTs;
  }

  public void setSapTs(Date sapTs){
    this.sapTs = sapTs;
  }


  public String getTitel(){
    return this.titel;
  }

  public void setTitel(String titel){
    this.titel = titel;
  }




}