/*
This file was automatically generated by the EntityCreator engine on Wed Apr 28 14:31:04 SGT 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the KNVL database table.
 * 
 * @author clint
 */
@Entity
@Table(
    name = "KNVL",
    schema = "SAPR3")
public class Knvl extends BaseEntity<KnvlPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private KnvlPK id;

  @Override
  public KnvlPK getId() {
    return id;
  }

  @Override
  public void setId(KnvlPK id) {
    this.id = id;
  }

  /**
   * Date From
   */
  private String datab;

  /**
   * Date To
   */
  private String datbi;

  /**
   * Tax Exemption Confirmation
   */
  private String belic;

  /**
   * Last updated date
   */
  @Column(
      name = "SHAD_UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date shadUpdateTs;

  /**
   * Update Type
   */
  @Column(
      name = "SHAD_UPDATE_IND")
  private String shadUpdateInd;

  /**
   * Last updated date
   */
  @Column(
      name = "SAP_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date sapTs;

  public String getDatab() {
    return this.datab;
  }

  public void setDatab(String datab) {
    this.datab = datab;
  }

  public String getDatbi() {
    return this.datbi;
  }

  public void setDatbi(String datbi) {
    this.datbi = datbi;
  }

  public String getBelic() {
    return this.belic;
  }

  public void setBelic(String belic) {
    this.belic = belic;
  }

  public Date getShadUpdateTs() {
    return this.shadUpdateTs;
  }

  public void setShadUpdateTs(Date shadUpdateTs) {
    this.shadUpdateTs = shadUpdateTs;
  }

  public String getShadUpdateInd() {
    return this.shadUpdateInd;
  }

  public void setShadUpdateInd(String shadUpdateInd) {
    this.shadUpdateInd = shadUpdateInd;
  }

  public Date getSapTs() {
    return this.sapTs;
  }

  public void setSapTs(Date sapTs) {
    this.sapTs = sapTs;
  }

}