/*
This file was automatically generated by the EntityCreator engine on Tue Feb 02 17:15:29 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the KNVP database table.
 * 
 * @author PriyRanjan
 */
@Entity
@Table(name = "KNVP", schema = "SAPR3")
public class Knvp extends BaseEntity<KnvpPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private KnvpPK id;

  public KnvpPK getId() {
    return id;
  }

  public void setId(KnvpPK id) {
    this.id = id;
  }
  
  private String kunn2;

  private String lifnr;

  private String pernr;

  private String parnr;

  private String knref;

  private String defpa;

  /** 
   * Last updated date
   */ 
  @Column(name = "SHAD_UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date shadUpdateTs;

  /** 
   * Update Type
   */ 
  @Column(name = "SHAD_UPDATE_IND")
  private String shadUpdateInd;

  /** 
   * Last updated date
   */ 
  @Column(name = "SAP_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date sapTs;

  public String getKunn2(){
    return this.kunn2;
  }

  public void setKunn2(String kunn2){
    this.kunn2 = kunn2;
  }


  public String getLifnr(){
    return this.lifnr;
  }

  public void setLifnr(String lifnr){
    this.lifnr = lifnr;
  }


  public String getPernr(){
    return this.pernr;
  }

  public void setPernr(String pernr){
    this.pernr = pernr;
  }


  public String getParnr(){
    return this.parnr;
  }

  public void setParnr(String parnr){
    this.parnr = parnr;
  }


  public String getKnref(){
    return this.knref;
  }

  public void setKnref(String knref){
    this.knref = knref;
  }


  public String getDefpa(){
    return this.defpa;
  }

  public void setDefpa(String defpa){
    this.defpa = defpa;
  }


  public Date getShadUpdateTs(){
    return this.shadUpdateTs;
  }

  public void setShadUpdateTs(Date shadUpdateTs){
    this.shadUpdateTs = shadUpdateTs;
  }


  public String getShadUpdateInd(){
    return this.shadUpdateInd;
  }

  public void setShadUpdateInd(String shadUpdateInd){
    this.shadUpdateInd = shadUpdateInd;
  }


  public Date getSapTs(){
    return this.sapTs;
  }

  public void setSapTs(Date sapTs){
    this.sapTs = sapTs;
  }




}