/*
This file was automatically generated by the EntityCreator engine on Tue Feb 02 17:13:56 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the KNVV database table.
 * 
 * @author PriyRanjan
 */
@Entity
@Table(name = "KNVV", schema = "SAPR3")
public class Knvv extends BaseEntity<KnvvPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private KnvvPK id;

  public KnvvPK getId() {
    return id;
  }

  public void setId(KnvvPK id) {
    this.id = id;
  }
  
  /** 
   * Created by user
   */ 
  private String ernam;

  /** 
   * Created date
   */ 
  private String erdat;

  /** 
   * Authorization Group
   */ 
  private String begru;

  /** 
   * Logical Delete Flag
   */ 
  private String loevm;

  /** 
   * Customer Statistics Group
   */ 
  private String versg;

  /** 
   * Central Order Block
   */ 
  private String aufsd;

  /** 
   * Pricing Procedure
   */ 
  private String kalks;

  /** 
   * Customer Group
   */ 
  private String kdgrp;

  /** 
   * Sales District
   */ 
  private String bzirk;

  /** 
   * Price Group
   */ 
  private String konda;

  /** 
   * Price List Type
   */ 
  private String pltyp;

  /** 
   * Order Probability of the Item
   */ 
  private String awahr;

  private String inco1;

  private String inco2;

  /** 
   * Central Delivery Block
   */ 
  private String lifsd;

  /** 
   * Complete Delivery
   */ 
  private String autlf;

  /** 
   * Maximum Partial Deliveries
   */ 
  private int antlf;

  /** 
   * Partial Delivery Item
   */ 
  private String kztlf;

  /** 
   * Order Combination
   */ 
  private String kzazu;

  /** 
   * Batch Split
   */ 
  private String chspl;

  /** 
   * Delivery Priority
   */ 
  private String lprio;

  private String eikto;

  /** 
   * Shipping Conditions
   */ 
  private String vsbed;

  /** 
   * Central Billing Block
   */ 
  private String faksd;

  /** 
   * Manual Invoice Maintenance
   */ 
  private String mrnkz;

  /** 
   * Billing Schedule
   */ 
  private String perfk;

  /** 
   * Invoice List Schedule
   */ 
  private String perrl;

  /** 
   * Cost Estimate Indicator
   */ 
  private String kvakz;

  /** 
   * Value Limit for Cost Estimate
   */ 
  private int kvawt;

  /** 
   * Customer Currency
   */ 
  private String waers;

  private String klabc;

  /** 
   * Account Assignment Group
   */ 
  private String ktgrd;

  /** 
   * Payment Terms
   */ 
  private String zterm;

  /** 
   * Delivery plant
   */ 
  private String vwerk;

  /** 
   * Sales Group
   */ 
  private String vkgrp;

  /** 
   * Sales Office
   */ 
  private String vkbur;

  /** 
   * Item Proposal
   */ 
  private String vsort;

  /** 
   * Invoice Split Merge
   */ 
  private String kvgr1;

  /** 
   * Supply Program
   */ 
  private String kvgr2;

  /** 
   * Administrative Organization
   */ 
  private String kvgr3;

  /** 
   * Country Use Code 1
   */ 
  private String kvgr4;

  /** 
   * Country Use Code 2
   */ 
  private String kvgr5;

  /** 
   * Rebate Indicator
   */ 
  private String bokre;

  /** 
   * Validity Period Start
   */ 
  private String boidt;

  /** 
   * Exchange Rate Type
   */ 
  private String kurst;

  private String prfre;

  /** 
   * ID for Product Attribute 1
   */ 
  private String prat1;

  /** 
   * ID for Product Attribute 2
   */ 
  private String prat2;

  /** 
   * ID for Product Attribute 3
   */ 
  private String prat3;

  /** 
   * ID for Product Attribute 4
   */ 
  private String prat4;

  /** 
   * ID for Product Attribute 5
   */ 
  private String prat5;

  /** 
   * ID for Product Attribute 6
   */ 
  private String prat6;

  /** 
   * ID for Product Attribute 7
   */ 
  private String prat7;

  /** 
   * ID for Product Attribute 8
   */ 
  private String prat8;

  /** 
   * ID for Product Attribute 9
   */ 
  private String prat9;

  /** 
   * ID for Product Attribute 10
   */ 
  private String prata;

  /** 
   * Billing Plan Type
   */ 
  private String fpart;

  /** 
   * Last updated date
   */ 
  @Column(name = "SHAD_UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date shadUpdateTs;

  /** 
   * Update Type
   */ 
  @Column(name = "SHAD_UPDATE_IND")
  private String shadUpdateInd;

  /** 
   * Last updated date
   */ 
  @Column(name = "SAP_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date sapTs;

  public String getErnam(){
    return this.ernam;
  }

  public void setErnam(String ernam){
    this.ernam = ernam;
  }


  public String getErdat(){
    return this.erdat;
  }

  public void setErdat(String erdat){
    this.erdat = erdat;
  }


  public String getBegru(){
    return this.begru;
  }

  public void setBegru(String begru){
    this.begru = begru;
  }


  public String getLoevm(){
    return this.loevm;
  }

  public void setLoevm(String loevm){
    this.loevm = loevm;
  }


  public String getVersg(){
    return this.versg;
  }

  public void setVersg(String versg){
    this.versg = versg;
  }


  public String getAufsd(){
    return this.aufsd;
  }

  public void setAufsd(String aufsd){
    this.aufsd = aufsd;
  }


  public String getKalks(){
    return this.kalks;
  }

  public void setKalks(String kalks){
    this.kalks = kalks;
  }


  public String getKdgrp(){
    return this.kdgrp;
  }

  public void setKdgrp(String kdgrp){
    this.kdgrp = kdgrp;
  }


  public String getBzirk(){
    return this.bzirk;
  }

  public void setBzirk(String bzirk){
    this.bzirk = bzirk;
  }


  public String getKonda(){
    return this.konda;
  }

  public void setKonda(String konda){
    this.konda = konda;
  }


  public String getPltyp(){
    return this.pltyp;
  }

  public void setPltyp(String pltyp){
    this.pltyp = pltyp;
  }


  public String getAwahr(){
    return this.awahr;
  }

  public void setAwahr(String awahr){
    this.awahr = awahr;
  }


  public String getInco1(){
    return this.inco1;
  }

  public void setInco1(String inco1){
    this.inco1 = inco1;
  }


  public String getInco2(){
    return this.inco2;
  }

  public void setInco2(String inco2){
    this.inco2 = inco2;
  }


  public String getLifsd(){
    return this.lifsd;
  }

  public void setLifsd(String lifsd){
    this.lifsd = lifsd;
  }


  public String getAutlf(){
    return this.autlf;
  }

  public void setAutlf(String autlf){
    this.autlf = autlf;
  }


  public int getAntlf(){
    return this.antlf;
  }

  public void setAntlf(int antlf){
    this.antlf = antlf;
  }


  public String getKztlf(){
    return this.kztlf;
  }

  public void setKztlf(String kztlf){
    this.kztlf = kztlf;
  }


  public String getKzazu(){
    return this.kzazu;
  }

  public void setKzazu(String kzazu){
    this.kzazu = kzazu;
  }


  public String getChspl(){
    return this.chspl;
  }

  public void setChspl(String chspl){
    this.chspl = chspl;
  }


  public String getLprio(){
    return this.lprio;
  }

  public void setLprio(String lprio){
    this.lprio = lprio;
  }


  public String getEikto(){
    return this.eikto;
  }

  public void setEikto(String eikto){
    this.eikto = eikto;
  }


  public String getVsbed(){
    return this.vsbed;
  }

  public void setVsbed(String vsbed){
    this.vsbed = vsbed;
  }


  public String getFaksd(){
    return this.faksd;
  }

  public void setFaksd(String faksd){
    this.faksd = faksd;
  }


  public String getMrnkz(){
    return this.mrnkz;
  }

  public void setMrnkz(String mrnkz){
    this.mrnkz = mrnkz;
  }


  public String getPerfk(){
    return this.perfk;
  }

  public void setPerfk(String perfk){
    this.perfk = perfk;
  }


  public String getPerrl(){
    return this.perrl;
  }

  public void setPerrl(String perrl){
    this.perrl = perrl;
  }


  public String getKvakz(){
    return this.kvakz;
  }

  public void setKvakz(String kvakz){
    this.kvakz = kvakz;
  }


  public int getKvawt(){
    return this.kvawt;
  }

  public void setKvawt(int kvawt){
    this.kvawt = kvawt;
  }


  public String getWaers(){
    return this.waers;
  }

  public void setWaers(String waers){
    this.waers = waers;
  }


  public String getKlabc(){
    return this.klabc;
  }

  public void setKlabc(String klabc){
    this.klabc = klabc;
  }


  public String getKtgrd(){
    return this.ktgrd;
  }

  public void setKtgrd(String ktgrd){
    this.ktgrd = ktgrd;
  }


  public String getZterm(){
    return this.zterm;
  }

  public void setZterm(String zterm){
    this.zterm = zterm;
  }


  public String getVwerk(){
    return this.vwerk;
  }

  public void setVwerk(String vwerk){
    this.vwerk = vwerk;
  }


  public String getVkgrp(){
    return this.vkgrp;
  }

  public void setVkgrp(String vkgrp){
    this.vkgrp = vkgrp;
  }


  public String getVkbur(){
    return this.vkbur;
  }

  public void setVkbur(String vkbur){
    this.vkbur = vkbur;
  }


  public String getVsort(){
    return this.vsort;
  }

  public void setVsort(String vsort){
    this.vsort = vsort;
  }


  public String getKvgr1(){
    return this.kvgr1;
  }

  public void setKvgr1(String kvgr1){
    this.kvgr1 = kvgr1;
  }


  public String getKvgr2(){
    return this.kvgr2;
  }

  public void setKvgr2(String kvgr2){
    this.kvgr2 = kvgr2;
  }


  public String getKvgr3(){
    return this.kvgr3;
  }

  public void setKvgr3(String kvgr3){
    this.kvgr3 = kvgr3;
  }


  public String getKvgr4(){
    return this.kvgr4;
  }

  public void setKvgr4(String kvgr4){
    this.kvgr4 = kvgr4;
  }


  public String getKvgr5(){
    return this.kvgr5;
  }

  public void setKvgr5(String kvgr5){
    this.kvgr5 = kvgr5;
  }


  public String getBokre(){
    return this.bokre;
  }

  public void setBokre(String bokre){
    this.bokre = bokre;
  }


  public String getBoidt(){
    return this.boidt;
  }

  public void setBoidt(String boidt){
    this.boidt = boidt;
  }


  public String getKurst(){
    return this.kurst;
  }

  public void setKurst(String kurst){
    this.kurst = kurst;
  }


  public String getPrfre(){
    return this.prfre;
  }

  public void setPrfre(String prfre){
    this.prfre = prfre;
  }


  public String getPrat1(){
    return this.prat1;
  }

  public void setPrat1(String prat1){
    this.prat1 = prat1;
  }


  public String getPrat2(){
    return this.prat2;
  }

  public void setPrat2(String prat2){
    this.prat2 = prat2;
  }


  public String getPrat3(){
    return this.prat3;
  }

  public void setPrat3(String prat3){
    this.prat3 = prat3;
  }


  public String getPrat4(){
    return this.prat4;
  }

  public void setPrat4(String prat4){
    this.prat4 = prat4;
  }


  public String getPrat5(){
    return this.prat5;
  }

  public void setPrat5(String prat5){
    this.prat5 = prat5;
  }


  public String getPrat6(){
    return this.prat6;
  }

  public void setPrat6(String prat6){
    this.prat6 = prat6;
  }


  public String getPrat7(){
    return this.prat7;
  }

  public void setPrat7(String prat7){
    this.prat7 = prat7;
  }


  public String getPrat8(){
    return this.prat8;
  }

  public void setPrat8(String prat8){
    this.prat8 = prat8;
  }


  public String getPrat9(){
    return this.prat9;
  }

  public void setPrat9(String prat9){
    this.prat9 = prat9;
  }


  public String getPrata(){
    return this.prata;
  }

  public void setPrata(String prata){
    this.prata = prata;
  }


  public String getFpart(){
    return this.fpart;
  }

  public void setFpart(String fpart){
    this.fpart = fpart;
  }


  public Date getShadUpdateTs(){
    return this.shadUpdateTs;
  }

  public void setShadUpdateTs(Date shadUpdateTs){
    this.shadUpdateTs = shadUpdateTs;
  }


  public String getShadUpdateInd(){
    return this.shadUpdateInd;
  }

  public void setShadUpdateInd(String shadUpdateInd){
    this.shadUpdateInd = shadUpdateInd;
  }


  public Date getSapTs(){
    return this.sapTs;
  }

  public void setSapTs(Date sapTs){
    this.sapTs = sapTs;
  }




}