/*
This file was automatically generated by the EntityCreator engine on Fri Dec 28 18:07:44 SGT 2018.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the KUNNR_EXT database table.
 * 
 * @author DennisNATAD
 */
@Entity
@Table(name = "KUNNR_EXT", schema = "SAPR3")
public class KunnrExt extends BaseEntity<KunnrExtPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private KunnrExtPK id;

  @Override
  public KunnrExtPK getId() {
    return id;
  }

  @Override
  public void setId(KunnrExtPK id) {
    this.id = id;
  }

  @Column(name = "VAT_IND")
  private String vatInd; 

  @Column(name = "GOE_IND")
  private String goeInd;

  @Column(name = "GOE_SRC_CD")
  private String goeSrcCd;

  @Column(name = "GOE_RSN_CD")
  private String goeRsnCd;

  @Column(name = "PRIVACY_IND")
  private String privacyInd;

  @Column(name = "IBM_AML_CD")
  private String ibmAmlCd;

  @Column(name = "CAP_IND")
  private String capInd;

  @Column(name = "GEO_LOC_CD")
  private String geoLocCd;

  @Column(name = "BUILDING")
  private String building;

  @Column(name = "FLOOR")
  private String floor;

  @Column(name = "FRONT")
  private String front;

  @Column(name = "HANGAR")
  private String hangar;

  @Column(name = "LOBBY")
  private String lobby;

  @Column(name = "LOT")
  private String lot;

  @Column(name = "LOWER")
  private String lower;

  @Column(name = "OFFICE")
  private String office;

  @Column(name = "PENTHOUSE")
  private String penthouse;

  @Column(name = "PIER")
  private String pier;

  @Column(name = "REAR")
  private String rear;

  @Column(name = "ROOM")
  private String room;

  @Column(name = "SUITE")
  private String suite;

  @Column(name = "BILL_TEXT1")
  private String billText1;

  @Column(name = "BILL_TEXT2")
  private String billText2;

  @Column(name = "UPDATE_IND")
  private String updateInd;

  /**
   * Create Timestamp
   */
  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  /**
   * Change Timestamp
   */
  @Column(name = "UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateTs;

  @Column(name = "CREATE_USER")
  private String createUser;

  @Column(name = "UPDATE_USER")
  private String updateUser;

  @Column(name = "CMR_ADDR_REC_NO")
  private String cmrAddrRecNo;

  @Column(name = "CMR_ADDR_REC_TYPE")
  private String cmrAddrRecType;

  /**
   * Department Name
   */
  private String department;

  /**
   * Business Partner Level Type
   */
  @Column(name = "BP_MBR_LVL_TYPE")
  private String bpMbrLvlType;

  @Column(name = "GOE_EXP_DATE")
  @Temporal(TemporalType.DATE)
  private Date goeExpDate;

  @Column(name = "ACTION_TXT")
  private String actionTxt;

  @Column(name = "SC_ACCOUNT_ID")
  private String scAccountId;

  @Column(name = "BUS_CMR_NAME")
  private String busCmrName;

  @Column(name = "SADR_BUS_CMR_NAME")
  private String sadrBusCmrName;

  @Column(name = "LANG_CD")
  private String langCd;

  private String comments;

  @Column(name = "SADR_LANG_CD")
  private String sadrLangCd;

  @Column(name = "COV_ELG_IND")
  private String covElgInd;

  @Column(name = "HW_INSTL_MSTR_FLG")
  private String hwInstlMstrFlg;

  public String getGoeInd() {
    return this.goeInd;
  }

  public void setGoeInd(String goeInd) {
    this.goeInd = goeInd;
  }

  public String getGoeSrcCd() {
    return this.goeSrcCd;
  }

  public void setGoeSrcCd(String goeSrcCd) {
    this.goeSrcCd = goeSrcCd;
  }

  public String getGoeRsnCd() {
    return this.goeRsnCd;
  }

  public void setGoeRsnCd(String goeRsnCd) {
    this.goeRsnCd = goeRsnCd;
  }

  public String getPrivacyInd() {
    return this.privacyInd;
  }

  public void setPrivacyInd(String privacyInd) {
    this.privacyInd = privacyInd;
  }

  public String getIbmAmlCd() {
    return this.ibmAmlCd;
  }

  public void setIbmAmlCd(String ibmAmlCd) {
    this.ibmAmlCd = ibmAmlCd;
  }

  public String getCapInd() {
    return this.capInd;
  }

  public void setCapInd(String capInd) {
    this.capInd = capInd;
  }

  public String getGeoLocCd() {
    return this.geoLocCd;
  }

  public void setGeoLocCd(String geoLocCd) {
    this.geoLocCd = geoLocCd;
  }

  public String getBuilding() {
    return this.building;
  }

  public void setBuilding(String building) {
    this.building = building;
  }

  public String getFloor() {
    return this.floor;
  }

  public void setFloor(String floor) {
    this.floor = floor;
  }

  public String getFront() {
    return this.front;
  }

  public void setFront(String front) {
    this.front = front;
  }

  public String getHangar() {
    return this.hangar;
  }

  public void setHangar(String hangar) {
    this.hangar = hangar;
  }

  public String getLobby() {
    return this.lobby;
  }

  public void setLobby(String lobby) {
    this.lobby = lobby;
  }

  public String getLot() {
    return this.lot;
  }

  public void setLot(String lot) {
    this.lot = lot;
  }

  public String getLower() {
    return this.lower;
  }

  public void setLower(String lower) {
    this.lower = lower;
  }

  public String getOffice() {
    return this.office;
  }

  public void setOffice(String office) {
    this.office = office;
  }

  public String getPenthouse() {
    return this.penthouse;
  }

  public void setPenthouse(String penthouse) {
    this.penthouse = penthouse;
  }

  public String getPier() {
    return this.pier;
  }

  public void setPier(String pier) {
    this.pier = pier;
  }

  public String getRear() {
    return this.rear;
  }

  public void setRear(String rear) {
    this.rear = rear;
  }

  public String getRoom() {
    return this.room;
  }

  public void setRoom(String room) {
    this.room = room;
  }

  public String getSuite() {
    return this.suite;
  }

  public void setSuite(String suite) {
    this.suite = suite;
  }

  public String getBillText1() {
    return this.billText1;
  }

  public void setBillText1(String billText1) {
    this.billText1 = billText1;
  }

  public String getBillText2() {
    return this.billText2;
  }

  public void setBillText2(String billText2) {
    this.billText2 = billText2;
  }

  public String getUpdateInd() {
    return this.updateInd;
  }

  public void setUpdateInd(String updateInd) {
    this.updateInd = updateInd;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public Date getUpdateTs() {
    return this.updateTs;
  }

  public void setUpdateTs(Date updateTs) {
    this.updateTs = updateTs;
  }

  public String getCreateUser() {
    return this.createUser;
  }

  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  public String getUpdateUser() {
    return this.updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  public String getCmrAddrRecNo() {
    return this.cmrAddrRecNo;
  }

  public void setCmrAddrRecNo(String cmrAddrRecNo) {
    this.cmrAddrRecNo = cmrAddrRecNo;
  }

  public String getCmrAddrRecType() {
    return this.cmrAddrRecType;
  }

  public void setCmrAddrRecType(String cmrAddrRecType) {
    this.cmrAddrRecType = cmrAddrRecType;
  }

  public String getDepartment() {
    return this.department;
  }

  public void setDepartment(String department) {
    this.department = department;
  }

  public String getBpMbrLvlType() {
    return this.bpMbrLvlType;
  }

  public void setBpMbrLvlType(String bpMbrLvlType) {
    this.bpMbrLvlType = bpMbrLvlType;
  }

  public Date getGoeExpDate() {
    return this.goeExpDate;
  }

  public void setGoeExpDate(Date goeExpDate) {
    this.goeExpDate = goeExpDate;
  }

  public String getActionTxt() {
    return this.actionTxt;
  }

  public void setActionTxt(String actionTxt) {
    this.actionTxt = actionTxt;
  }

  public String getScAccountId() {
    return this.scAccountId;
  }

  public void setScAccountId(String scAccountId) {
    this.scAccountId = scAccountId;
  }

  public String getBusCmrName() {
    return this.busCmrName;
  }

  public void setBusCmrName(String busCmrName) {
    this.busCmrName = busCmrName;
  }

  public String getSadrBusCmrName() {
    return this.sadrBusCmrName;
  }

  public void setSadrBusCmrName(String sadrBusCmrName) {
    this.sadrBusCmrName = sadrBusCmrName;
  }

  public String getLangCd() {
    return this.langCd;
  }

  public void setLangCd(String langCd) {
    this.langCd = langCd;
  }

  public String getComments() {
    return this.comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public String getSadrLangCd() {
    return this.sadrLangCd;
  }

  public void setSadrLangCd(String sadrLangCd) {
    this.sadrLangCd = sadrLangCd;
  }

  public String getCovElgInd() {
    return this.covElgInd;
  }

  public void setCovElgInd(String covElgInd) {
    this.covElgInd = covElgInd;
  }

  public String getHwInstlMstrFlg() {
    return hwInstlMstrFlg;
  }

  public void setHwInstlMstrFlg(String hwInstlMstrFlg) {
    this.hwInstlMstrFlg = hwInstlMstrFlg;
  }

  public String getVatInd() {
    return vatInd;
  }

  public void setVatInd(String vatInd) {
    this.vatInd = vatInd;
  }
}