/*
This file was automatically generated by the EntityCreator engine on Mon Apr 24 12:51:11 SGT 2023.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.StringUtils;

/**
 * The primary key class for the LICENSES database table.
 * 
 * @author P100JGPH1
 */
@Embeddable
public class LicensesPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  /**
   * Request Identifier
   */
  @Column(
      name = "REQ_ID")
  private long reqId;

  /**
   * Software License Number
   */
  @Column(
      name = "LICENSE_NUM")
  private String licenseNum;

  public long getReqId() {
    return this.reqId;
  }

  public void setReqId(long reqId) {
    this.reqId = reqId;
  }

  public String getLicenseNum() {
    return this.licenseNum;
  }

  public void setLicenseNum(String licenseNum) {
    this.licenseNum = licenseNum;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof LicensesPK)) {
      return false;
    }
    LicensesPK o = (LicensesPK) other;
    return this.reqId == o.reqId && this.licenseNum.equals(o.licenseNum);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.reqId > 0 ? new java.lang.Long(this.reqId).hashCode() : 0);
    hash = hash * prime + (this.licenseNum != null ? this.licenseNum.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.reqId > 0 && !StringUtils.isEmpty(this.licenseNum);
  }
}