/*
This file was automatically generated by the EntityCreator engine on Thu Aug 20 16:18:14 IST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the LOV database table.
 * 
 * @author Rama mohan
 */
@Entity
@Table(name = "LOV", schema = "CREQCMR")
public class Lov extends BaseEntity<LovPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private LovPK id;

  @Override
  public LovPK getId() {
    return id;
  }

  @Override
  public void setId(LovPK id) {
    this.id = id;
  }

  @Column(name = "DEFAULT_IND")
  private String defaultInd;

  @Column(name = "DISP_ORDER")
  private int dispOrder;

  private String txt;

  @Column(name = "DISP_TYPE")
  private String dispType;

  private String cmt;

  public String getDefaultInd() {
    return this.defaultInd;
  }

  public void setDefaultInd(String defaultInd) {
    this.defaultInd = defaultInd;
  }

  public int getDispOrder() {
    return this.dispOrder;
  }

  public void setDispOrder(int dispOrder) {
    this.dispOrder = dispOrder;
  }

  public String getTxt() {
    return this.txt;
  }

  public void setTxt(String txt) {
    this.txt = txt;
  }

  public String getDispType() {
    return this.dispType;
  }

  public void setDispType(String dispType) {
    this.dispType = dispType;
  }

  public String getCmt() {
    return this.cmt;
  }

  public void setCmt(String cmt) {
    this.cmt = cmt;
  }

}