/*
This file was automatically generated by the EntityCreator engine on Thu May 24 11:56:16 IST 2018.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.cio.cmr.request.entity.listeners.ChangeLogDetails;
import com.ibm.cio.cmr.request.entity.listeners.ChangeLogListener;
import com.ibm.cio.cmr.request.entity.listeners.TrimListener;

/**
 * The persistent class for the MACHINES_TO_INSTALL database table.
 * 
 * @author ibm_admin
 */
@Entity
@Table(
    name = "MACHINES_TO_INSTALL",
    schema = "CREQCMR")
@EntityListeners({ TrimListener.class, ChangeLogListener.class })
@ChangeLogDetails(
    childTable = true,
    addressTable = true,
    reqId = "id.reqId",
    addressSeq = "id.addrSeq",
    addressType = "id.addrType",
    insertFieldName = "id.machineTyp,id.machineSerialNo",
    deleteFieldName = "id.machineTyp,id.machineSerialNo")
public class MachinesToInstall extends BaseEntity<MachinesToInstallPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private MachinesToInstallPK id;

  @Override
  public MachinesToInstallPK getId() {
    return id;
  }

  @Override
  public void setId(MachinesToInstallPK id) {
    this.id = id;
  }

  @Column(
      name = "CURRENT_INDC")
  private String currentIndc;

  @Column(
      name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(
      name = "CREATE_BY")
  private String createBy;

  @Column(
      name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date lastUpdtTs;

  @Column(
      name = "LAST_UPDT_BY")
  private String lastUpdtBy;

  public String getCurrentIndc() {
    return this.currentIndc;
  }

  public void setCurrentIndc(String currentIndc) {
    this.currentIndc = currentIndc;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getLastUpdtTs() {
    return this.lastUpdtTs;
  }

  public void setLastUpdtTs(Date lastUpdtTs) {
    this.lastUpdtTs = lastUpdtTs;
  }

  public String getLastUpdtBy() {
    return this.lastUpdtBy;
  }

  public void setLastUpdtBy(String lastUpdtBy) {
    this.lastUpdtBy = lastUpdtBy;
  }

}