/*
This file was automatically generated by the EntityCreator engine on Thu May 24 11:56:16 IST 2018.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the MACHINES_TO_INSTALL database table.
 * 
 * @author ibm_admin
 */
@Embeddable
public class MachinesToInstallPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "REQ_ID")
  private long reqId;

  @Column(name = "ADDR_TYPE")
  private String addrType;

  @Column(name = "ADDR_SEQ")
  private String addrSeq;

  @Column(name = "MACHINE_SERIAL_NO")
  private String machineSerialNo;

  @Column(name = "MACHINE_TYP")
  private String machineTyp;

  public long getReqId(){
    return this.reqId;
  }

  public void setReqId(long reqId){
    this.reqId = reqId;
  }


  public String getAddrType(){
    return this.addrType;
  }

  public void setAddrType(String addrType){
    this.addrType = addrType;
  }


  public String getAddrSeq(){
    return this.addrSeq;
  }

  public void setAddrSeq(String addrSeq){
    this.addrSeq = addrSeq;
  }


  public String getMachineSerialNo(){
    return this.machineSerialNo;
  }

  public void setMachineSerialNo(String machineSerialNo){
    this.machineSerialNo = machineSerialNo;
  }


  public String getMachineTyp(){
    return this.machineTyp;
  }

  public void setMachineTyp(String machineTyp){
    this.machineTyp = machineTyp;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof MachinesToInstallPK)) {
      return false;
    }
    MachinesToInstallPK o = (MachinesToInstallPK) other;
    return this.reqId == o.reqId && this.addrType.equals(o.addrType) && this.addrSeq.equals(o.addrSeq) && this.machineSerialNo.equals(o.machineSerialNo) && this.machineTyp.equals(o.machineTyp);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.reqId > 0 ? new java.lang.Long(this.reqId).hashCode() : 0);
    hash = hash * prime + (this.addrType != null ? this.addrType.hashCode() : 0);
    hash = hash * prime + (this.addrSeq != null ? this.addrSeq.hashCode() : 0);
    hash = hash * prime + (this.machineSerialNo != null ? this.machineSerialNo.hashCode() : 0);
    hash = hash * prime + (this.machineTyp != null ? this.machineTyp.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.reqId > 0 && !StringUtils.isEmpty(this.addrType) && !StringUtils.isEmpty(this.addrSeq) && !StringUtils.isEmpty(this.machineSerialNo) && !StringUtils.isEmpty(this.machineTyp);

  }
}