/*
This file was automatically generated by the EntityCreator engine on Tue Mar 28 16:36:16 SGT 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityResult;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;

/**
 * The persistent class for the MASS_CREATE database table.
 * 
 * @author Eduard Bernardo
 */
@Entity
@Table(name = "MASS_CREATE", schema = "CREQCMR")
@SqlResultSetMappings({ @SqlResultSetMapping(name = MassCreate.MASS_CREATE_META_MAPPING, entities = { @EntityResult(entityClass = MassCreate.class) }, columns = { @ColumnResult(name = "FILE_NAME") }) })
public class MassCreate extends BaseEntity<MassCreatePK> implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String MASS_CREATE_META_MAPPING = "MassCreateMeta";
  @EmbeddedId
  private MassCreatePK id;

  @Override
  public MassCreatePK getId() {
    return id;
  }

  @Override
  public void setId(MassCreatePK id) {
    this.id = id;
  }

  @Column(name = "AUTO_UPDT")
  private String autoUpdt;

  @Column(name = "ERROR_TXT")
  private String errorTxt;

  @Column(name = "ROW_STATUS_CD")
  private String rowStatusCd;

  @Column(name = "CMR_NO")
  private String cmrNo;

  public String getAutoUpdt() {
    return this.autoUpdt;
  }

  public void setAutoUpdt(String autoUpdt) {
    this.autoUpdt = autoUpdt;
  }

  public String getErrorTxt() {
    return this.errorTxt;
  }

  public void setErrorTxt(String errorTxt) {
    this.errorTxt = errorTxt;
  }

  public String getRowStatusCd() {
    return this.rowStatusCd;
  }

  public void setRowStatusCd(String rowStatusCd) {
    this.rowStatusCd = rowStatusCd;
  }

  public String getCmrNo() {
    return this.cmrNo;
  }

  public void setCmrNo(String cmrNo) {
    this.cmrNo = cmrNo;
  }

}