/*
This file was automatically generated by the EntityCreator engine on Tue Mar 28 16:36:17 SGT 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the MASS_CREATE_DATA database table.
 * 
 * @author Eduard Bernardo
 */
@Entity
@Table(name = "MASS_CREATE_DATA", schema = "CREQCMR")
public class MassCreateData extends BaseEntity<MassCreateDataPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private MassCreateDataPK id;

  @Override
  public MassCreateDataPK getId() {
    return id;
  }

  @Override
  public void setId(MassCreateDataPK id) {
    this.id = id;
  }

  @Column(name = "CUST_NM1")
  private String custNm1;

  @Column(name = "CUST_NM2")
  private String custNm2;

  @Column(name = "ABBREV_NM")
  private String abbrevNm;

  private String affiliate;

  @Column(name = "BP_REL_TYPE")
  private String bpRelType;

  @Column(name = "CAP_IND")
  private String capInd;

  @Column(name = "CLIENT_TIER")
  private String clientTier;

  @Column(name = "CMR_ISSUING_CNTRY")
  private String cmrIssuingCntry;

  @Column(name = "CMR_NO")
  private String cmrNo;

  @Column(name = "CMR_OWNER")
  private String cmrOwner;

  private String company;

  @Column(name = "CUST_CLASS")
  private String custClass;

  private String enterprise;

  @Column(name = "CUST_PREF_LANG")
  private String custPrefLang;

  @Column(name = "INAC_CD")
  private String inacCd;

  @Column(name = "INAC_TYPE")
  private String inacType;

  @Column(name = "ISU_CD")
  private String isuCd;

  @Column(name = "TAX_CD1")
  private String taxCd1;

  @Column(name = "TAX_CD2")
  private String taxCd2;

  @Column(name = "TAX_CD3")
  private String taxCd3;

  @Column(name = "SEARCH_TERM")
  private String searchTerm;

  @Column(name = "MEM_LVL")
  private String memLvl;

  @Column(name = "SENSITIVE_FLAG")
  private String sensitiveFlag;

  @Column(name = "ISIC_CD")
  private String isicCd;

  @Column(name = "SITE_PARTY_ID")
  private String sitePartyId;

  @Column(name = "SUB_INDUSTRY_CD")
  private String subIndustryCd;

  private String vat;

  @Column(name = "COV_ID")
  private String covId;

  @Column(name = "BG_ID")
  private String bgId;

  @Column(name = "GEO_LOC_CD")
  private String geoLocCd;

  @Column(name = "DUNS_NO")
  private String dunsNo;

  @Column(name = "CUST_GRP")
  private String custGrp;

  @Column(name = "CUST_SUB_GRP")
  private String custSubGrp;

  @Column(name = "CUST_TYP")
  private String custTyp;

  @Column(name = "RESTRICT_IND")
  private String restrictInd;

  @Column(name = "RESTRICT_TO")
  private String restrictTo;

  @Column(name = "OEM_IND")
  private String oemInd;

  @Column(name = "BP_ACCT_TYP")
  private String bpAcctTyp;

  @Column(name = "MKTG_DEPT")
  private String mktgDept;

  @Column(name = "MTKG_AR_DEPT")
  private String mtkgArDept;

  @Column(name = "PCC_MKTG_DEPT")
  private String pccMktgDept;

  @Column(name = "PCC_AR_DEPT")
  private String pccArDept;

  @Column(name = "SVC_AR_OFFICE")
  private String svcArOffice;

  @Column(name = "OUT_CITY_LIMIT")
  private String outCityLimit;

  @Column(name = "CSO_SITE")
  private String csoSite;

  @Column(name = "FED_SITE_IND")
  private String fedSiteInd;

  @Column(name = "SIZE_CD")
  private String sizeCd;

  @Column(name = "SVC_TERRITORY_ZONE")
  private String svcTerritoryZone;

  @Column(name = "MISC_BILL_CD")
  private String miscBillCd;

  @Column(name = "BP_NAME")
  private String bpName;

  @Column(name = "ICC_TAX_CLASS")
  private String iccTaxClass;

  @Column(name = "ICC_TAX_EXEMPT_STATUS")
  private String iccTaxExemptStatus;

  @Column(name = "NON_IBM_COMPANY_IND")
  private String nonIbmCompanyInd;

  private String div;

  private String dept;

  private String func;

  private String user;

  private String loc;

  @Column(name = "ORD_BLK")
  private String ordBlk;

  @Column(name = "BG_RULE_ID")
  private String bgRuleId;

  @Column(name = "COV_DESC")
  private String covDesc;

  @Column(name = "BG_DESC")
  private String bgDesc;

  @Column(name = "GEO_LOC_DESC")
  private String geoLocDesc;

  @Column(name = "GBG_ID")
  private String gbgId;

  @Column(name = "GBG_DESC")
  private String gbgDesc;

  @Column(name = "MODEL_CMR_NO")
  private String modelCmrNo;

  public String getCustNm1() {
    return this.custNm1;
  }

  public void setCustNm1(String custNm1) {
    this.custNm1 = custNm1;
  }

  public String getCustNm2() {
    return this.custNm2;
  }

  public void setCustNm2(String custNm2) {
    this.custNm2 = custNm2;
  }

  public String getAbbrevNm() {
    return this.abbrevNm;
  }

  public void setAbbrevNm(String abbrevNm) {
    this.abbrevNm = abbrevNm;
  }

  public String getAffiliate() {
    return this.affiliate;
  }

  public void setAffiliate(String affiliate) {
    this.affiliate = affiliate;
  }

  public String getBpRelType() {
    return this.bpRelType;
  }

  public void setBpRelType(String bpRelType) {
    this.bpRelType = bpRelType;
  }

  public String getCapInd() {
    return this.capInd;
  }

  public void setCapInd(String capInd) {
    this.capInd = capInd;
  }

  public String getClientTier() {
    return this.clientTier;
  }

  public void setClientTier(String clientTier) {
    this.clientTier = clientTier;
  }

  public String getCmrIssuingCntry() {
    return this.cmrIssuingCntry;
  }

  public void setCmrIssuingCntry(String cmrIssuingCntry) {
    this.cmrIssuingCntry = cmrIssuingCntry;
  }

  public String getCmrNo() {
    return this.cmrNo;
  }

  public void setCmrNo(String cmrNo) {
    this.cmrNo = cmrNo;
  }

  public String getCmrOwner() {
    return this.cmrOwner;
  }

  public void setCmrOwner(String cmrOwner) {
    this.cmrOwner = cmrOwner;
  }

  public String getCompany() {
    return this.company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public String getCustClass() {
    return this.custClass;
  }

  public void setCustClass(String custClass) {
    this.custClass = custClass;
  }

  public String getEnterprise() {
    return this.enterprise;
  }

  public void setEnterprise(String enterprise) {
    this.enterprise = enterprise;
  }

  public String getCustPrefLang() {
    return this.custPrefLang;
  }

  public void setCustPrefLang(String custPrefLang) {
    this.custPrefLang = custPrefLang;
  }

  public String getInacCd() {
    return this.inacCd;
  }

  public void setInacCd(String inacCd) {
    this.inacCd = inacCd;
  }

  public String getInacType() {
    return this.inacType;
  }

  public void setInacType(String inacType) {
    this.inacType = inacType;
  }

  public String getIsuCd() {
    return this.isuCd;
  }

  public void setIsuCd(String isuCd) {
    this.isuCd = isuCd;
  }

  public String getTaxCd1() {
    return this.taxCd1;
  }

  public void setTaxCd1(String taxCd1) {
    this.taxCd1 = taxCd1;
  }

  public String getTaxCd2() {
    return this.taxCd2;
  }

  public void setTaxCd2(String taxCd2) {
    this.taxCd2 = taxCd2;
  }

  public String getTaxCd3() {
    return this.taxCd3;
  }

  public void setTaxCd3(String taxCd3) {
    this.taxCd3 = taxCd3;
  }

  public String getSearchTerm() {
    return this.searchTerm;
  }

  public void setSearchTerm(String searchTerm) {
    this.searchTerm = searchTerm;
  }

  public String getMemLvl() {
    return this.memLvl;
  }

  public void setMemLvl(String memLvl) {
    this.memLvl = memLvl;
  }

  public String getSensitiveFlag() {
    return this.sensitiveFlag;
  }

  public void setSensitiveFlag(String sensitiveFlag) {
    this.sensitiveFlag = sensitiveFlag;
  }

  public String getIsicCd() {
    return this.isicCd;
  }

  public void setIsicCd(String isicCd) {
    this.isicCd = isicCd;
  }

  public String getSitePartyId() {
    return this.sitePartyId;
  }

  public void setSitePartyId(String sitePartyId) {
    this.sitePartyId = sitePartyId;
  }

  public String getSubIndustryCd() {
    return this.subIndustryCd;
  }

  public void setSubIndustryCd(String subIndustryCd) {
    this.subIndustryCd = subIndustryCd;
  }

  public String getVat() {
    return this.vat;
  }

  public void setVat(String vat) {
    this.vat = vat;
  }

  public String getCovId() {
    return this.covId;
  }

  public void setCovId(String covId) {
    this.covId = covId;
  }

  public String getBgId() {
    return this.bgId;
  }

  public void setBgId(String bgId) {
    this.bgId = bgId;
  }

  public String getGeoLocCd() {
    return this.geoLocCd;
  }

  public void setGeoLocCd(String geoLocCd) {
    this.geoLocCd = geoLocCd;
  }

  public String getDunsNo() {
    return this.dunsNo;
  }

  public void setDunsNo(String dunsNo) {
    this.dunsNo = dunsNo;
  }

  public String getCustGrp() {
    return this.custGrp;
  }

  public void setCustGrp(String custGrp) {
    this.custGrp = custGrp;
  }

  public String getCustSubGrp() {
    return this.custSubGrp;
  }

  public void setCustSubGrp(String custSubGrp) {
    this.custSubGrp = custSubGrp;
  }

  public String getCustTyp() {
    return this.custTyp;
  }

  public void setCustTyp(String custTyp) {
    this.custTyp = custTyp;
  }

  public String getRestrictInd() {
    return this.restrictInd;
  }

  public void setRestrictInd(String restrictInd) {
    this.restrictInd = restrictInd;
  }

  public String getRestrictTo() {
    return this.restrictTo;
  }

  public void setRestrictTo(String restrictTo) {
    this.restrictTo = restrictTo;
  }

  public String getOemInd() {
    return this.oemInd;
  }

  public void setOemInd(String oemInd) {
    this.oemInd = oemInd;
  }

  public String getBpAcctTyp() {
    return this.bpAcctTyp;
  }

  public void setBpAcctTyp(String bpAcctTyp) {
    this.bpAcctTyp = bpAcctTyp;
  }

  public String getMktgDept() {
    return this.mktgDept;
  }

  public void setMktgDept(String mktgDept) {
    this.mktgDept = mktgDept;
  }

  public String getMtkgArDept() {
    return this.mtkgArDept;
  }

  public void setMtkgArDept(String mtkgArDept) {
    this.mtkgArDept = mtkgArDept;
  }

  public String getPccMktgDept() {
    return this.pccMktgDept;
  }

  public void setPccMktgDept(String pccMktgDept) {
    this.pccMktgDept = pccMktgDept;
  }

  public String getPccArDept() {
    return this.pccArDept;
  }

  public void setPccArDept(String pccArDept) {
    this.pccArDept = pccArDept;
  }

  public String getSvcArOffice() {
    return this.svcArOffice;
  }

  public void setSvcArOffice(String svcArOffice) {
    this.svcArOffice = svcArOffice;
  }

  public String getOutCityLimit() {
    return this.outCityLimit;
  }

  public void setOutCityLimit(String outCityLimit) {
    this.outCityLimit = outCityLimit;
  }

  public String getCsoSite() {
    return this.csoSite;
  }

  public void setCsoSite(String csoSite) {
    this.csoSite = csoSite;
  }

  public String getFedSiteInd() {
    return this.fedSiteInd;
  }

  public void setFedSiteInd(String fedSiteInd) {
    this.fedSiteInd = fedSiteInd;
  }

  public String getSizeCd() {
    return this.sizeCd;
  }

  public void setSizeCd(String sizeCd) {
    this.sizeCd = sizeCd;
  }

  public String getSvcTerritoryZone() {
    return this.svcTerritoryZone;
  }

  public void setSvcTerritoryZone(String svcTerritoryZone) {
    this.svcTerritoryZone = svcTerritoryZone;
  }

  public String getMiscBillCd() {
    return this.miscBillCd;
  }

  public void setMiscBillCd(String miscBillCd) {
    this.miscBillCd = miscBillCd;
  }

  public String getBpName() {
    return this.bpName;
  }

  public void setBpName(String bpName) {
    this.bpName = bpName;
  }

  public String getIccTaxClass() {
    return this.iccTaxClass;
  }

  public void setIccTaxClass(String iccTaxClass) {
    this.iccTaxClass = iccTaxClass;
  }

  public String getIccTaxExemptStatus() {
    return this.iccTaxExemptStatus;
  }

  public void setIccTaxExemptStatus(String iccTaxExemptStatus) {
    this.iccTaxExemptStatus = iccTaxExemptStatus;
  }

  public String getNonIbmCompanyInd() {
    return this.nonIbmCompanyInd;
  }

  public void setNonIbmCompanyInd(String nonIbmCompanyInd) {
    this.nonIbmCompanyInd = nonIbmCompanyInd;
  }

  public String getDiv() {
    return this.div;
  }

  public void setDiv(String div) {
    this.div = div;
  }

  public String getDept() {
    return this.dept;
  }

  public void setDept(String dept) {
    this.dept = dept;
  }

  public String getFunc() {
    return this.func;
  }

  public void setFunc(String func) {
    this.func = func;
  }

  public String getUser() {
    return this.user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public String getLoc() {
    return this.loc;
  }

  public void setLoc(String loc) {
    this.loc = loc;
  }

  public String getOrdBlk() {
    return this.ordBlk;
  }

  public void setOrdBlk(String ordBlk) {
    this.ordBlk = ordBlk;
  }

  public String getBgRuleId() {
    return this.bgRuleId;
  }

  public void setBgRuleId(String bgRuleId) {
    this.bgRuleId = bgRuleId;
  }

  public String getCovDesc() {
    return this.covDesc;
  }

  public void setCovDesc(String covDesc) {
    this.covDesc = covDesc;
  }

  public String getBgDesc() {
    return this.bgDesc;
  }

  public void setBgDesc(String bgDesc) {
    this.bgDesc = bgDesc;
  }

  public String getGeoLocDesc() {
    return this.geoLocDesc;
  }

  public void setGeoLocDesc(String geoLocDesc) {
    this.geoLocDesc = geoLocDesc;
  }

  public String getGbgId() {
    return this.gbgId;
  }

  public void setGbgId(String gbgId) {
    this.gbgId = gbgId;
  }

  public String getGbgDesc() {
    return this.gbgDesc;
  }

  public void setGbgDesc(String gbgDesc) {
    this.gbgDesc = gbgDesc;
  }

  public String getModelCmrNo() {
    return this.modelCmrNo;
  }

  public void setModelCmrNo(String modelCmrNo) {
    this.modelCmrNo = modelCmrNo;
  }

}