/*
This file was automatically generated by the EntityCreator engine on Tue Mar 28 16:36:17 SGT 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * The persistent class for the MASS_CREATE_ADDR database table.
 * 
 * @author Eduard Bernardo
 */
@Entity
@Table(name = "MASS_CREATE_ADDR", schema = "CREQCMR")
public class MassCreateAddr extends BaseEntity<MassCreateAddrPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private MassCreateAddrPK id;

  @Override
  public MassCreateAddrPK getId() {
    return id;
  }

  @Override
  public void setId(MassCreateAddrPK id) {
    this.id = id;
  }

  @Column(name = "LAND_CNTRY")
  private String landCntry;

  @Column(name = "STATE_PROV")
  private String stateProv;

  @Column(name = "ADDR_TXT")
  private String addrTxt;

  @Column(name = "ADDR_TXT2")
  private String addrTxt2;

  private String city1;

  @Column(name = "POST_CD")
  private String postCd;

  private String county;

  private String divn;

  private String dept;

  @Transient
  private boolean virtual;

  @Column(name = "SAP_NO")
  private String sapNo;

  public String getLandCntry() {
    return this.landCntry;
  }

  public void setLandCntry(String landCntry) {
    this.landCntry = landCntry;
  }

  public String getStateProv() {
    return this.stateProv;
  }

  public void setStateProv(String stateProv) {
    this.stateProv = stateProv;
  }

  public String getAddrTxt() {
    return this.addrTxt;
  }

  public void setAddrTxt(String addrTxt) {
    this.addrTxt = addrTxt;
  }

  public String getAddrTxt2() {
    return this.addrTxt2;
  }

  public void setAddrTxt2(String addrTxt2) {
    this.addrTxt2 = addrTxt2;
  }

  public String getCity1() {
    return this.city1;
  }

  public void setCity1(String city1) {
    this.city1 = city1;
  }

  public String getPostCd() {
    return this.postCd;
  }

  public void setPostCd(String postCd) {
    this.postCd = postCd;
  }

  public String getCounty() {
    return this.county;
  }

  public void setCounty(String county) {
    this.county = county;
  }

  public String getDivn() {
    return this.divn;
  }

  public void setDivn(String divn) {
    this.divn = divn;
  }

  public String getDept() {
    return this.dept;
  }

  public void setDept(String dept) {
    this.dept = dept;
  }

  public String getSapNo() {
    return this.sapNo;
  }

  public void setSapNo(String sapNo) {
    this.sapNo = sapNo;
  }

  public boolean isVirtual() {
    return virtual;
  }

  public void setVirtual(boolean virtual) {
    this.virtual = virtual;
  }

}