/*
This file was automatically generated by the EntityCreator engine on Wed Nov 09 18:12:15 CST 2016.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;

import com.ibm.cio.cmr.request.entity.listeners.ChangeLogDetails;
import com.ibm.cio.cmr.request.entity.listeners.ChangeLogListener;
import com.ibm.cio.cmr.request.entity.listeners.NoLog;

/**
 * The persistent class for the MASS_UPDT database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(name = "MASS_UPDT", schema = "CREQCMR")
@EntityListeners(ChangeLogListener.class)
@ChangeLogDetails(childTable = true, reqId = "id.parReqId", logUpdates = false, logForRequestType = { "R", "D" }, insertFieldName = "cmrNo", deleteFieldName = "cmrNo")
public class MassUpdt extends BaseEntity<MassUpdtPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  @NoLog
  private MassUpdtPK id;

  @Override
  public MassUpdtPK getId() {
    return id;
  }

  @Override
  public void setId(MassUpdtPK id) {
    this.id = id;
  }

  @Column(name = "ERROR_TXT")
  private String errorTxt;

  @Column(name = "ROW_STATUS_CD")
  private String rowStatusCd;

  @Column(name = "CMR_NO")
  private String cmrNo;

  public String getErrorTxt() {
    return this.errorTxt;
  }

  public void setErrorTxt(String errorTxt) {
    this.errorTxt = errorTxt;
  }

  public String getRowStatusCd() {
    return this.rowStatusCd;
  }

  public void setRowStatusCd(String rowStatusCd) {
    this.rowStatusCd = rowStatusCd;
  }

  public String getCmrNo() {
    return this.cmrNo;
  }

  public void setCmrNo(String cmrNo) {
    this.cmrNo = cmrNo;
  }

}