/*
This file was automatically generated by the EntityCreator engine on Wed Nov 09 18:12:17 CST 2016.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the MASS_UPDT_ADDR database table.
 * 
 * @author Jeffrey Zamora
 */
@Embeddable
public class MassUpdtAddrPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "PAR_REQ_ID")
  private long parReqId;

  @Column(name = "SEQ_NO")
  private int seqNo;

  @Column(name = "ITERATION_ID")
  private int iterationId;

  @Column(name = "ADDR_TYPE")
  private String addrType;

  public long getParReqId(){
    return this.parReqId;
  }

  public void setParReqId(long parReqId){
    this.parReqId = parReqId;
  }


  public int getSeqNo(){
    return this.seqNo;
  }

  public void setSeqNo(int seqNo){
    this.seqNo = seqNo;
  }


  public int getIterationId(){
    return this.iterationId;
  }

  public void setIterationId(int iterationId){
    this.iterationId = iterationId;
  }


  public String getAddrType(){
    return this.addrType;
  }

  public void setAddrType(String addrType){
    this.addrType = addrType;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof MassUpdtAddrPK)) {
      return false;
    }
    MassUpdtAddrPK o = (MassUpdtAddrPK) other;
    return this.parReqId == o.parReqId && this.seqNo == o.seqNo && this.iterationId == o.iterationId && this.addrType.equals(o.addrType);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.parReqId > 0 ? new java.lang.Long(this.parReqId).hashCode() : 0);
    hash = hash * prime + this.seqNo;
    hash = hash * prime + this.iterationId;
    hash = hash * prime + (this.addrType != null ? this.addrType.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.parReqId > 0 && this.seqNo > 0 && this.iterationId > 0 && !StringUtils.isEmpty(this.addrType);

  }
}