/*
This file was automatically generated by the EntityCreator engine on Mon Apr 17 13:48:58 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;

import com.ibm.cio.cmr.request.entity.listeners.ChangeLogDetails;
import com.ibm.cio.cmr.request.entity.listeners.ChangeLogListener;
import com.ibm.cio.cmr.request.entity.listeners.NoLog;

/**
 * The persistent class for the MASS_UPDT_DATA database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(name = "MASS_UPDT_DATA", schema = "CREQCMR")
@EntityListeners(ChangeLogListener.class)
@ChangeLogDetails(childTable = true, reqId = "id.parReqId", logForRequestType = { "E" }, logInserts = true, logDeletes = false)
public class MassUpdtData extends BaseEntity<MassUpdtDataPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  @NoLog
  private MassUpdtDataPK id;

  @Override
  public MassUpdtDataPK getId() {
    return id;
  }

  @Override
  public void setId(MassUpdtDataPK id) {
    this.id = id;
  }

  @Column(name = "ABBREV_NM")
  private String abbrevNm;

  @Column(name = "ISIC_CD")
  private String isicCd;

  @Column(name = "OUT_CITY_LIMIT")
  private String outCityLimit;

  @Column(name = "PCC_AR_DEPT")
  private String pccArDept;

  @Column(name = "RESTRICT_IND")
  private String restrictInd;

  @Column(name = "SVC_AR_OFFICE")
  private String svcArOffice;

  @Column(name = "AFFILIATE")
  private String affiliate;

  @Column(name = "CSO_SITE")
  private String csoSite;

  @Column(name = "MKTG_DEPT")
  private String mktgDept;

  @Column(name = "MISC_BILL_CD")
  private String miscBillCd;

  @Column(name = "ICC_TAX_CLASS")
  private String iccTaxClass;

  @Column(name = "ICC_TAX_EXEMPT_STATUS")
  private String iccTaxExemptStatus;

  @Column(name = "TAX_CD1")
  private String taxCd1;

  @Column(name = "TAX_CD2")
  private String taxCd2;

  @Column(name = "TAX_CD3")
  private String taxCd3;

  @Column(name = "ISU_CD")
  private String isuCd;

  @Column(name = "INAC_CD")
  private String inacCd;

  @Column(name = "CLIENT_TIER")
  private String clientTier;

  @Column(name = "MKTG_AR_DEPT")
  private String mktgArDept;

  @Column(name = "CUST_NM1")
  private String custNm1;

  @Column(name = "CUST_NM2")
  private String custNm2;

  @Column(name = "RESTRICT_TO")
  private String restrictTo;

  @Column(name = "ENTERPRISE")
  private String enterprise;

  @Column(name = "NEW_ENTP")
  private String newEntp;

  @Column(name = "NEW_ENTP_NAME1")
  private String newEntpName1;

  @Column(name = "NEW_ENTP_NAME2")
  private String newEntpName2;

  @Column(name = "ENTP_UPDT_TYP")
  private String entpUpdtTyp;

  @Column(name = "COMPANY")
  private String company;

  @Column(name = "VAT")
  private String vat;

  @Column(name = "ORD_BLK")
  private String ordBlk;

  @Column(name = "REP_TEAM_MEMBER_NO")
  private String repTeamMemberNo;

  @Column(name = "SALES_BO_CD")
  private String salesBoCd;

  @Column(name = "INSTALL_BRANCH_OFF")
  private String installBranchOff;

  @Column(name = "MODE_OF_PAYMENT")
  private String modeOfPayment;

  @Column(name = "SPECIAL_TAX_CD")
  private String specialTaxCd;

  @Column(name = "ENGINEERING_BO")
  private String engineeringBo;

  @Column(name = "COLLECTION_CD")
  private String collectionCd;

  @Column(name = "ABBREV_LOCN")
  private String abbrevLocn;

  @Column(name = "SUB_INDUSTRY_CD")
  private String subIndustryCd;

  @Column(name = "CUST_CLASS")
  private String custClass;

  @Column(name = "CURRENCY_CD")
  private String currencyCd;

  @Column(name = "SEARCH_TERM")
  private String searchTerm;

  @Column(name = "EMAIL1")
  private String email1;

  @Column(name = "EMAIL2")
  private String email2;

  @Column(name = "EMAIL3")
  private String email3;

  public String getAbbrevNm() {
    return this.abbrevNm;
  }

  public void setAbbrevNm(String abbrevNm) {
    this.abbrevNm = abbrevNm;
  }

  public String getIsicCd() {
    return this.isicCd;
  }

  public void setIsicCd(String isicCd) {
    this.isicCd = isicCd;
  }

  public String getOutCityLimit() {
    return this.outCityLimit;
  }

  public void setOutCityLimit(String outCityLimit) {
    this.outCityLimit = outCityLimit;
  }

  public String getPccArDept() {
    return this.pccArDept;
  }

  public void setPccArDept(String pccArDept) {
    this.pccArDept = pccArDept;
  }

  public String getRestrictInd() {
    return this.restrictInd;
  }

  public void setRestrictInd(String restrictInd) {
    this.restrictInd = restrictInd;
  }

  public String getSvcArOffice() {
    return this.svcArOffice;
  }

  public void setSvcArOffice(String svcArOffice) {
    this.svcArOffice = svcArOffice;
  }

  public String getAffiliate() {
    return this.affiliate;
  }

  public void setAffiliate(String affiliate) {
    this.affiliate = affiliate;
  }

  public String getCsoSite() {
    return this.csoSite;
  }

  public void setCsoSite(String csoSite) {
    this.csoSite = csoSite;
  }

  public String getMktgDept() {
    return this.mktgDept;
  }

  public void setMktgDept(String mktgDept) {
    this.mktgDept = mktgDept;
  }

  public String getMiscBillCd() {
    return this.miscBillCd;
  }

  public void setMiscBillCd(String miscBillCd) {
    this.miscBillCd = miscBillCd;
  }

  public String getIccTaxClass() {
    return this.iccTaxClass;
  }

  public void setIccTaxClass(String iccTaxClass) {
    this.iccTaxClass = iccTaxClass;
  }

  public String getIccTaxExemptStatus() {
    return this.iccTaxExemptStatus;
  }

  public void setIccTaxExemptStatus(String iccTaxExemptStatus) {
    this.iccTaxExemptStatus = iccTaxExemptStatus;
  }

  public String getTaxCd1() {
    return this.taxCd1;
  }

  public void setTaxCd1(String taxCd1) {
    this.taxCd1 = taxCd1;
  }

  public String getTaxCd2() {
    return this.taxCd2;
  }

  public void setTaxCd2(String taxCd2) {
    this.taxCd2 = taxCd2;
  }

  public String getTaxCd3() {
    return this.taxCd3;
  }

  public void setTaxCd3(String taxCd3) {
    this.taxCd3 = taxCd3;
  }

  public String getIsuCd() {
    return this.isuCd;
  }

  public void setIsuCd(String isuCd) {
    this.isuCd = isuCd;
  }

  public String getInacCd() {
    return this.inacCd;
  }

  public void setInacCd(String inacCd) {
    this.inacCd = inacCd;
  }

  public String getClientTier() {
    return this.clientTier;
  }

  public void setClientTier(String clientTier) {
    this.clientTier = clientTier;
  }

  public String getMktgArDept() {
    return this.mktgArDept;
  }

  public void setMktgArDept(String mktgArDept) {
    this.mktgArDept = mktgArDept;
  }

  public String getCustNm1() {
    return this.custNm1;
  }

  public void setCustNm1(String custNm1) {
    this.custNm1 = custNm1;
  }

  public String getCustNm2() {
    return this.custNm2;
  }

  public void setCustNm2(String custNm2) {
    this.custNm2 = custNm2;
  }

  public String getRestrictTo() {
    return this.restrictTo;
  }

  public void setRestrictTo(String restrictTo) {
    this.restrictTo = restrictTo;
  }

  public String getEnterprise() {
    return this.enterprise;
  }

  public void setEnterprise(String enterprise) {
    this.enterprise = enterprise;
  }

  public String getNewEntp() {
    return this.newEntp;
  }

  public void setNewEntp(String newEntp) {
    this.newEntp = newEntp;
  }

  public String getNewEntpName1() {
    return this.newEntpName1;
  }

  public void setNewEntpName1(String newEntpName1) {
    this.newEntpName1 = newEntpName1;
  }

  public String getNewEntpName2() {
    return this.newEntpName2;
  }

  public void setNewEntpName2(String newEntpName2) {
    this.newEntpName2 = newEntpName2;
  }

  public String getEntpUpdtTyp() {
    return this.entpUpdtTyp;
  }

  public void setEntpUpdtTyp(String entpUpdtTyp) {
    this.entpUpdtTyp = entpUpdtTyp;
  }

  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public String getVat() {
    return vat;
  }

  public void setVat(String vat) {
    this.vat = vat;
  }

  public String getOrdBlk() {
    return ordBlk;
  }

  public void setOrdBlk(String ordBlk) {
    this.ordBlk = ordBlk;
  }

  public String getRepTeamMemberNo() {
    return repTeamMemberNo;
  }

  public void setRepTeamMemberNo(String repTeamMemberNo) {
    this.repTeamMemberNo = repTeamMemberNo;
  }

  public String getSalesBoCd() {
    return salesBoCd;
  }

  public void setSalesBoCd(String salesBoCd) {
    this.salesBoCd = salesBoCd;
  }

  public String getInstallBranchOff() {
    return installBranchOff;
  }

  public void setInstallBranchOff(String installBranchOff) {
    this.installBranchOff = installBranchOff;
  }

  public String getModeOfPayment() {
    return modeOfPayment;
  }

  public void setModeOfPayment(String modeOfPayment) {
    this.modeOfPayment = modeOfPayment;
  }

  public String getSpecialTaxCd() {
    return specialTaxCd;
  }

  public void setSpecialTaxCd(String specialTaxCd) {
    this.specialTaxCd = specialTaxCd;
  }

  public String getEngineeringBo() {
    return engineeringBo;
  }

  public void setEngineeringBo(String engineeringBo) {
    this.engineeringBo = engineeringBo;
  }

  public String getCollectionCd() {
    return collectionCd;
  }

  public void setCollectionCd(String collectionCd) {
    this.collectionCd = collectionCd;
  }

  public String getAbbrevLocn() {
    return abbrevLocn;
  }

  public void setAbbrevLocn(String abbrevLocn) {
    this.abbrevLocn = abbrevLocn;
  }

  public String getSubIndustryCd() {
    return subIndustryCd;
  }

  public void setSubIndustryCd(String subIndustryCd) {
    this.subIndustryCd = subIndustryCd;
  }

  public String getCustClass() {
    return custClass;
  }

  public void setCustClass(String custClass) {
    this.custClass = custClass;
  }

  public String getCurrencyCd() {
    return currencyCd;
  }

  public void setCurrencyCd(String currencyCd) {
    this.currencyCd = currencyCd;
  }

  public String getSearchTerm() {
    return searchTerm;
  }

  public void setSearchTerm(String searchTerm) {
    this.searchTerm = searchTerm;
  }

  public String getEmail1() {
    return email1;
  }

  public void setEmail1(String email1) {
    this.email1 = email1;
  }

  public String getEmail2() {
    return email2;
  }

  public void setEmail2(String email2) {
    this.email2 = email2;
  }

  public String getEmail3() {
    return email3;
  }

  public void setEmail3(String email3) {
    this.email3 = email3;
  }

}