/*
This file was automatically generated by the EntityCreator engine on Mon May 21 19:42:55 SGT 2018.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the MQ_INTF_REQ_DATA database table.
 * 
 * @author JeffZAMORA
 */
@Embeddable
public class MqIntfReqDataPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "QUERY_REQ_ID")
  private long queryReqId;

  @Column(name = "FILE_NAME")
  private String fileName;

  public long getQueryReqId(){
    return this.queryReqId;
  }

  public void setQueryReqId(long queryReqId){
    this.queryReqId = queryReqId;
  }


  public String getFileName(){
    return this.fileName;
  }

  public void setFileName(String fileName){
    this.fileName = fileName;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof MqIntfReqDataPK)) {
      return false;
    }
    MqIntfReqDataPK o = (MqIntfReqDataPK) other;
    return this.queryReqId == o.queryReqId && this.fileName.equals(o.fileName);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.queryReqId > 0 ? new java.lang.Long(this.queryReqId).hashCode() : 0);
    hash = hash * prime + (this.fileName != null ? this.fileName.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.queryReqId > 0 && !StringUtils.isEmpty(this.fileName);

  }
}