/*
This file was automatically generated by the EntityCreator engine on Wed Jul 12 16:16:59 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * The primary key class for the MQ_INTF_REQ_QUEUE database table.
 * 
 * @author lvguofeng
 */
@Embeddable
public class MqIntfReqQueuePK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "QUERY_REQ_ID")
  private long queryReqId;

  public long getQueryReqId() {
    return this.queryReqId;
  }

  public void setQueryReqId(long queryReqId) {
    this.queryReqId = queryReqId;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof MqIntfReqQueuePK)) {
      return false;
    }
    MqIntfReqQueuePK o = (MqIntfReqQueuePK) other;
    return this.queryReqId == o.queryReqId;

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.queryReqId > 0 ? new java.lang.Long(this.queryReqId).hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.queryReqId > 0;

  }
}