/*
This file was automatically generated by the EntityCreator engine on Mon May 21 19:42:55 SGT 2018.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the MQ_INTF_REQ_DATA database table.
 * 
 * @author JeffZAMORA
 */
@Entity
@Table(name = "MQ_INTF_REQ_DATA", schema = "CREQCMR")
public class MqIntfReqData extends BaseEntity<MqIntfReqDataPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private MqIntfReqDataPK id;

  public MqIntfReqDataPK getId() {
    return id;
  }

  public void setId(MqIntfReqDataPK id) {
    this.id = id;
  }
  
  private String contents;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  public String getContents(){
    return this.contents;
  }

  public void setContents(String contents){
    this.contents = contents;
  }


  public Date getCreateTs(){
    return this.createTs;
  }

  public void setCreateTs(Date createTs){
    this.createTs = createTs;
  }




}