/*
This file was automatically generated by the EntityCreator engine on Wed Jul 12 16:16:59 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityResult;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the MQ_INTF_REQ_QUEUE database table.
 * 
 * @author lvguofeng
 */
@Entity
@Table(
    name = "MQ_INTF_REQ_QUEUE",
    schema = "CREQCMR")
@SqlResultSetMappings({ @SqlResultSetMapping(
    name = "MQStatusMapping",
    entities = { @EntityResult(
        entityClass = MqIntfReqQueue.class) },
    columns = { @ColumnResult(
        name = "ADMIN_STATUS"), @ColumnResult(
        name = "ADMIN_STATUS_DESC"), @ColumnResult(
        name = "HAS_DATA") }) })
public class MqIntfReqQueue extends BaseEntity<MqIntfReqQueuePK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private MqIntfReqQueuePK id;

  @Override
  public MqIntfReqQueuePK getId() {
    return id;
  }

  @Override
  public void setId(MqIntfReqQueuePK id) {
    this.id = id;
  }

  @Column(
      name = "REQ_ID")
  private long reqId;

  @Column(
      name = "REQ_TYPE")
  private String reqType;

  @Column(
      name = "CMR_NO")
  private String cmrNo;

  @Column(
      name = "CMR_ISSUING_CNTRY")
  private String cmrIssuingCntry;

  @Column(
      name = "REQ_STATUS")
  private String reqStatus;

  @Column(
      name = "ERROR_CD")
  private String errorCd;

  @Column(
      name = "EXECP_MESSAGE")
  private String execpMessage;

  @Column(
      name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(
      name = "CREATE_BY")
  private String createBy;

  @Column(
      name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date lastUpdtTs;

  @Column(
      name = "LAST_UPDT_BY")
  private String lastUpdtBy;

  @Column(
      name = "TARGET_SYS")
  private String targetSys;

  @Column(
      name = "CORRELATION_ID")
  private String correlationId;

  @Column(
      name = "MQ_IND")
  private String mqInd;

  @Column(
      name = "DOCM_REFN_NO")
  private String docmRefnNo;

  @Column(
      name = "REFN_SOURCE_CD")
  private String refnSourceCd;

  public long getReqId() {
    return this.reqId;
  }

  public void setReqId(long reqId) {
    this.reqId = reqId;
  }

  public String getReqType() {
    return this.reqType;
  }

  public void setReqType(String reqType) {
    this.reqType = reqType;
  }

  public String getCmrNo() {
    return this.cmrNo;
  }

  public void setCmrNo(String cmrNo) {
    this.cmrNo = cmrNo;
  }

  public String getCmrIssuingCntry() {
    return this.cmrIssuingCntry;
  }

  public void setCmrIssuingCntry(String cmrIssuingCntry) {
    this.cmrIssuingCntry = cmrIssuingCntry;
  }

  public String getReqStatus() {
    return this.reqStatus;
  }

  public void setReqStatus(String reqStatus) {
    this.reqStatus = reqStatus;
  }

  public String getErrorCd() {
    return this.errorCd;
  }

  public void setErrorCd(String errorCd) {
    this.errorCd = errorCd;
  }

  public String getExecpMessage() {
    return this.execpMessage;
  }

  public void setExecpMessage(String execpMessage) {
    this.execpMessage = execpMessage;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getLastUpdtTs() {
    return this.lastUpdtTs;
  }

  public void setLastUpdtTs(Date lastUpdtTs) {
    this.lastUpdtTs = lastUpdtTs;
  }

  public String getLastUpdtBy() {
    return this.lastUpdtBy;
  }

  public void setLastUpdtBy(String lastUpdtBy) {
    this.lastUpdtBy = lastUpdtBy;
  }

  public String getTargetSys() {
    return this.targetSys;
  }

  public void setTargetSys(String targetSys) {
    this.targetSys = targetSys;
  }

  public String getCorrelationId() {
    return this.correlationId;
  }

  public void setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
  }

  public String getMqInd() {
    return this.mqInd;
  }

  public void setMqInd(String mqInd) {
    this.mqInd = mqInd;
  }

  public String getDocmRefnNo() {
    return docmRefnNo;
  }

  public void setDocmRefnNo(String docmRefnNo) {
    this.docmRefnNo = docmRefnNo;
  }

  public String getRefnSourceCd() {
    return refnSourceCd;
  }

  public void setRefnSourceCd(String refnSourceCd) {
    this.refnSourceCd = refnSourceCd;
  }

}