/*
This file was automatically generated by the EntityCreator engine on Mon May 08 18:26:05 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the MRC_ISU database table.
 * 
 * @author Neil Sherwin Espolong
 */
@Embeddable
public class MrcIsuPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "ISSUING_CNTRY")
  private String issuingCntry;

  @Column(name = "MRC_CD")
  private String mrcCd;

  private String isu;

  public String getIssuingCntry() {
    return this.issuingCntry;
  }

  public void setIssuingCntry(String issuingCntry) {
    this.issuingCntry = issuingCntry;
  }

  public String getMrcCd() {
    return this.mrcCd;
  }

  public void setMrcCd(String mrcCd) {
    this.mrcCd = mrcCd;
  }

  public String getIsu() {
    return this.isu;
  }

  public void setIsu(String isu) {
    this.isu = isu;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof MrcIsuPK)) {
      return false;
    }
    MrcIsuPK o = (MrcIsuPK) other;
    return this.issuingCntry.equals(o.issuingCntry) && this.mrcCd.equals(o.mrcCd) && this.isu.equals(o.isu);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.issuingCntry != null ? this.issuingCntry.hashCode() : 0);
    hash = hash * prime + (this.mrcCd != null ? this.mrcCd.hashCode() : 0);
    hash = hash * prime + (this.isu != null ? this.isu.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.issuingCntry) && !StringUtils.isEmpty(this.mrcCd) && !StringUtils.isEmpty(this.isu);

  }
}