/*
This file was automatically generated by the EntityCreator engine on Thu Aug 20 16:18:54 IST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the NOTIF_LIST database table.
 * 
 * @author Rama mohan
 */
@Embeddable
public class NotifListPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "REQ_ID")
  private long reqId;

  @Column(name = "NOTIF_ID")
  private String notifId;

  public long getReqId() {
    return this.reqId;
  }

  public void setReqId(long reqId) {
    this.reqId = reqId;
  }

  public String getNotifId() {
    return this.notifId;
  }

  public void setNotifId(String notifId) {
    this.notifId = notifId;
  }

  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof NotifListPK)) {
      return false;
    }
    NotifListPK o = (NotifListPK) other;
    return this.reqId == o.reqId && this.notifId.equals(o.notifId);

  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.reqId > 0 ? new java.lang.Long(this.reqId).hashCode() : 0);
    hash = hash * prime + (this.notifId != null ? this.notifId.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.reqId > 0 && !StringUtils.isEmpty(this.notifId);

  }
}