/*
This file was automatically generated by the EntityCreator engine on Thu Aug 20 16:18:54 IST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.EntityResult;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;

import com.ibm.cio.cmr.request.entity.listeners.ChangeLogDetails;
import com.ibm.cio.cmr.request.entity.listeners.ChangeLogListener;
import com.ibm.cio.cmr.request.entity.listeners.NoLog;

/**
 * The persistent class for the NOTIF_LIST database table.
 * 
 * @author Rama mohan
 */
@Entity
@Table(name = "NOTIF_LIST", schema = "CREQCMR")
@SqlResultSetMapping(name = "NotifyListMapping", entities = { @EntityResult(entityClass = NotifList.class) }, columns = {
    @ColumnResult(name = "RECEIVE_MAIL_IND"), @ColumnResult(name = "REMOVABLE") })
@EntityListeners(ChangeLogListener.class)
@ChangeLogDetails(childTable = true, reqId = "id.reqId", logUpdates = false, insertFieldName = "id.notifId", deleteFieldName = "id.notifId")
public class NotifList extends BaseEntity<NotifListPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String NOTIF_LIST_MAPPING = "NotifyListMapping";

  @EmbeddedId
  @NoLog
  private NotifListPK id;

  @Override
  public NotifListPK getId() {
    return id;
  }

  @Override
  public void setId(NotifListPK id) {
    this.id = id;
  }

  @Column(name = "NOTIF_NM")
  private String notifNm;

  public String getNotifNm() {
    return this.notifNm;
  }

  public void setNotifNm(String notifNm) {
    this.notifNm = notifNm;
  }

}