/*
This file was automatically generated by the EntityCreator engine on Wed Feb 24 18:05:08 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang3.StringUtils;

/**
 * The primary key class for the PARTNER_EXCEPTIONS database table.
 * 
 * @author GarimaNarang
 */
@Embeddable
public class PartnerExceptionsPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  /** 
   * Service Identifier
   */ 
  @Column(name = "SERVICE_ID")
  private String serviceId;

  /** 
   * CMR Issuing Country
   */ 
  @Column(name = "CMR_ISSUING_CNTRY")
  private String cmrIssuingCntry;

  public String getServiceId(){
    return this.serviceId;
  }

  public void setServiceId(String serviceId){
    this.serviceId = serviceId;
  }


  public String getCmrIssuingCntry(){
    return this.cmrIssuingCntry;
  }

  public void setCmrIssuingCntry(String cmrIssuingCntry){
    this.cmrIssuingCntry = cmrIssuingCntry;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof PartnerExceptionsPK)) {
      return false;
    }
    PartnerExceptionsPK o = (PartnerExceptionsPK) other;
    return this.serviceId.equals(o.serviceId) && this.cmrIssuingCntry.equals(o.cmrIssuingCntry);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.serviceId != null ? this.serviceId.hashCode() : 0);
    hash = hash * prime + (this.cmrIssuingCntry != null ? this.cmrIssuingCntry.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.serviceId) && !StringUtils.isEmpty(this.cmrIssuingCntry);

  }
}