/*
This file was automatically generated by the EntityCreator engine on Mon Oct 23 12:46:19 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.cio.cmr.request.entity.listeners.ChangeLogDetails;
import com.ibm.cio.cmr.request.entity.listeners.ChangeLogListener;
import com.ibm.cio.cmr.request.entity.listeners.NoLog;
import com.ibm.cio.cmr.request.entity.listeners.TrimListener;

/**
 * The persistent class for the PROLIF_CHECKLIST database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(name = "PROLIF_CHECKLIST", schema = "CREQCMR")
@EntityListeners({ TrimListener.class, ChangeLogListener.class })
@ChangeLogDetails(childTable = true, reqId = "id.reqId")
public class ProlifChecklist extends BaseEntity<ProlifChecklistPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private ProlifChecklistPK id;

  @Override
  public ProlifChecklistPK getId() {
    return id;
  }

  @Override
  public void setId(ProlifChecklistPK id) {
    this.id = id;
  }

  @Column(name = "US_DPL_SANCTIONED")
  private String usDplSanctioned;

  @Column(name = "POTENTIAL_MATCH")
  private String potentialMatch;

  @Column(name = "LOCAL_CUST_NM")
  private String localCustNm;

  @Column(name = "LOCAL_ADDR")
  private String localAddr;

  @Column(name = "TAX_CD")
  private String taxCd;

  @Column(name = "SECTION_A1")
  private String sectionA1;

  @Column(name = "SECTION_A2")
  private String sectionA2;

  @Column(name = "SECTION_A3")
  private String sectionA3;

  @Column(name = "SECTION_A4")
  private String sectionA4;

  @Column(name = "SECTION_A5")
  private String sectionA5;

  @Column(name = "SECTION_A6")
  private String sectionA6;

  @Column(name = "SECTION_A7")
  private String sectionA7;

  @Column(name = "SECTION_A8")
  private String sectionA8;

  @Column(name = "SECTION_A9")
  private String sectionA9;

  @Column(name = "SECTION_A10")
  private String sectionA10;

  @Column(name = "SECTION_B1")
  private String sectionB1;

  @Column(name = "SECTION_B2")
  private String sectionB2;

  @Column(name = "SECTION_B3")
  private String sectionB3;

  @Column(name = "SECTION_B4")
  private String sectionB4;

  @Column(name = "SECTION_B5")
  private String sectionB5;

  @Column(name = "SECTION_B6")
  private String sectionB6;

  @Column(name = "SECTION_B7")
  private String sectionB7;

  @Column(name = "SECTION_B8")
  private String sectionB8;

  @Column(name = "SECTION_B9")
  private String sectionB9;

  @Column(name = "SECTION_B10")
  private String sectionB10;

  @Column(name = "SECTION_C1")
  private String sectionC1;

  @Column(name = "SECTION_C2")
  private String sectionC2;

  @Column(name = "SECTION_C3")
  private String sectionC3;

  @Column(name = "SECTION_C4")
  private String sectionC4;

  @Column(name = "SECTION_C5")
  private String sectionC5;

  @Column(name = "SECTION_C6")
  private String sectionC6;

  @Column(name = "SECTION_C7")
  private String sectionC7;

  @Column(name = "SECTION_C8")
  private String sectionC8;

  @Column(name = "SECTION_C9")
  private String sectionC9;

  @Column(name = "SECTION_C10")
  private String sectionC10;

  @Column(name = "SECTION_D1")
  private String sectionD1;

  @Column(name = "SECTION_D2")
  private String sectionD2;

  @Column(name = "SECTION_D3")
  private String sectionD3;

  @Column(name = "SECTION_D4")
  private String sectionD4;

  @Column(name = "SECTION_D5")
  private String sectionD5;

  @Column(name = "SECTION_D6")
  private String sectionD6;

  @Column(name = "SECTION_D7")
  private String sectionD7;

  @Column(name = "SECTION_D8")
  private String sectionD8;

  @Column(name = "SECTION_D9")
  private String sectionD9;

  @Column(name = "SECTION_D10")
  private String sectionD10;

  @Column(name = "SECTION_E1")
  private String sectionE1;

  @Column(name = "SECTION_E2")
  private String sectionE2;

  @Column(name = "SECTION_E3")
  private String sectionE3;

  @Column(name = "SECTION_E4")
  private String sectionE4;

  @Column(name = "SECTION_E5")
  private String sectionE5;

  @Column(name = "SECTION_E6")
  private String sectionE6;

  @Column(name = "SECTION_E7")
  private String sectionE7;

  @Column(name = "SECTION_E8")
  private String sectionE8;

  @Column(name = "SECTION_E9")
  private String sectionE9;

  @Column(name = "SECTION_E10")
  private String sectionE10;

  @Column(name = "SALES_MGR_ID")
  private String salesMgrId;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  @NoLog
  private Date createTs;

  @Column(name = "CREATE_BY")
  private String createBy;

  @Column(name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  @NoLog
  private Date lastUpdtTs;

  @Column(name = "LAST_UPDT_BY")
  private String lastUpdtBy;

  @Column(name = "FREE_TXT_FIELD_1")
  private String freeTxtField1;

  @Column(name = "FREE_TXT_FIELD_2")
  private String freeTxtField2;

  @Column(name = "FREE_TXT_FIELD_3")
  private String freeTxtField3;

  @Column(name = "FREE_TXT_FIELD_4")
  private String freeTxtField4;

  @Column(name = "FREE_TXT_FIELD_5")
  private String freeTxtField5;

  public String getUsDplSanctioned() {
    return this.usDplSanctioned;
  }

  public void setUsDplSanctioned(String usDplSactioned) {
    this.usDplSanctioned = usDplSactioned;
  }

  public String getPotentialMatch() {
    return this.potentialMatch;
  }

  public void setPotentialMatch(String potentialMatch) {
    this.potentialMatch = potentialMatch;
  }

  public String getLocalCustNm() {
    return this.localCustNm;
  }

  public void setLocalCustNm(String localCustNm) {
    this.localCustNm = localCustNm;
  }

  public String getLocalAddr() {
    return this.localAddr;
  }

  public void setLocalAddr(String localAddr) {
    this.localAddr = localAddr;
  }

  public String getTaxCd() {
    return this.taxCd;
  }

  public void setTaxCd(String taxCd) {
    this.taxCd = taxCd;
  }

  public String getSectionA1() {
    return this.sectionA1;
  }

  public void setSectionA1(String sectionA1) {
    this.sectionA1 = sectionA1;
  }

  public String getSectionA2() {
    return this.sectionA2;
  }

  public void setSectionA2(String sectionA2) {
    this.sectionA2 = sectionA2;
  }

  public String getSectionA3() {
    return this.sectionA3;
  }

  public void setSectionA3(String sectionA3) {
    this.sectionA3 = sectionA3;
  }

  public String getSectionA4() {
    return this.sectionA4;
  }

  public void setSectionA4(String sectionA4) {
    this.sectionA4 = sectionA4;
  }

  public String getSectionA5() {
    return this.sectionA5;
  }

  public void setSectionA5(String sectionA5) {
    this.sectionA5 = sectionA5;
  }

  public String getSectionA6() {
    return this.sectionA6;
  }

  public void setSectionA6(String sectionA6) {
    this.sectionA6 = sectionA6;
  }

  public String getSectionA7() {
    return this.sectionA7;
  }

  public void setSectionA7(String sectionA7) {
    this.sectionA7 = sectionA7;
  }

  public String getSectionA8() {
    return this.sectionA8;
  }

  public void setSectionA8(String sectionA8) {
    this.sectionA8 = sectionA8;
  }

  public String getSectionA9() {
    return this.sectionA9;
  }

  public void setSectionA9(String sectionA9) {
    this.sectionA9 = sectionA9;
  }

  public String getSectionA10() {
    return this.sectionA10;
  }

  public void setSectionA10(String sectionA10) {
    this.sectionA10 = sectionA10;
  }

  public String getSectionB1() {
    return this.sectionB1;
  }

  public void setSectionB1(String sectionB1) {
    this.sectionB1 = sectionB1;
  }

  public String getSectionB2() {
    return this.sectionB2;
  }

  public void setSectionB2(String sectionB2) {
    this.sectionB2 = sectionB2;
  }

  public String getSectionB3() {
    return this.sectionB3;
  }

  public void setSectionB3(String sectionB3) {
    this.sectionB3 = sectionB3;
  }

  public String getSectionB4() {
    return this.sectionB4;
  }

  public void setSectionB4(String sectionB4) {
    this.sectionB4 = sectionB4;
  }

  public String getSectionB5() {
    return this.sectionB5;
  }

  public void setSectionB5(String sectionB5) {
    this.sectionB5 = sectionB5;
  }

  public String getSectionB6() {
    return this.sectionB6;
  }

  public void setSectionB6(String sectionB6) {
    this.sectionB6 = sectionB6;
  }

  public String getSectionB7() {
    return this.sectionB7;
  }

  public void setSectionB7(String sectionB7) {
    this.sectionB7 = sectionB7;
  }

  public String getSectionB8() {
    return this.sectionB8;
  }

  public void setSectionB8(String sectionB8) {
    this.sectionB8 = sectionB8;
  }

  public String getSectionB9() {
    return this.sectionB9;
  }

  public void setSectionB9(String sectionB9) {
    this.sectionB9 = sectionB9;
  }

  public String getSectionB10() {
    return this.sectionB10;
  }

  public void setSectionB10(String sectionB10) {
    this.sectionB10 = sectionB10;
  }

  public String getSectionC1() {
    return this.sectionC1;
  }

  public void setSectionC1(String sectionC1) {
    this.sectionC1 = sectionC1;
  }

  public String getSectionC2() {
    return this.sectionC2;
  }

  public void setSectionC2(String sectionC2) {
    this.sectionC2 = sectionC2;
  }

  public String getSectionC3() {
    return this.sectionC3;
  }

  public void setSectionC3(String sectionC3) {
    this.sectionC3 = sectionC3;
  }

  public String getSectionC4() {
    return this.sectionC4;
  }

  public void setSectionC4(String sectionC4) {
    this.sectionC4 = sectionC4;
  }

  public String getSectionC5() {
    return this.sectionC5;
  }

  public void setSectionC5(String sectionC5) {
    this.sectionC5 = sectionC5;
  }

  public String getSectionC6() {
    return this.sectionC6;
  }

  public void setSectionC6(String sectionC6) {
    this.sectionC6 = sectionC6;
  }

  public String getSectionC7() {
    return this.sectionC7;
  }

  public void setSectionC7(String sectionC7) {
    this.sectionC7 = sectionC7;
  }

  public String getSectionC8() {
    return this.sectionC8;
  }

  public void setSectionC8(String sectionC8) {
    this.sectionC8 = sectionC8;
  }

  public String getSectionC9() {
    return this.sectionC9;
  }

  public void setSectionC9(String sectionC9) {
    this.sectionC9 = sectionC9;
  }

  public String getSectionC10() {
    return this.sectionC10;
  }

  public void setSectionC10(String sectionC10) {
    this.sectionC10 = sectionC10;
  }

  public String getSectionD1() {
    return this.sectionD1;
  }

  public void setSectionD1(String sectionD1) {
    this.sectionD1 = sectionD1;
  }

  public String getSectionD2() {
    return this.sectionD2;
  }

  public void setSectionD2(String sectionD2) {
    this.sectionD2 = sectionD2;
  }

  public String getSectionD3() {
    return this.sectionD3;
  }

  public void setSectionD3(String sectionD3) {
    this.sectionD3 = sectionD3;
  }

  public String getSectionD4() {
    return this.sectionD4;
  }

  public void setSectionD4(String sectionD4) {
    this.sectionD4 = sectionD4;
  }

  public String getSectionD5() {
    return this.sectionD5;
  }

  public void setSectionD5(String sectionD5) {
    this.sectionD5 = sectionD5;
  }

  public String getSectionD6() {
    return this.sectionD6;
  }

  public void setSectionD6(String sectionD6) {
    this.sectionD6 = sectionD6;
  }

  public String getSectionD7() {
    return this.sectionD7;
  }

  public void setSectionD7(String sectionD7) {
    this.sectionD7 = sectionD7;
  }

  public String getSectionD8() {
    return this.sectionD8;
  }

  public void setSectionD8(String sectionD8) {
    this.sectionD8 = sectionD8;
  }

  public String getSectionD9() {
    return this.sectionD9;
  }

  public void setSectionD9(String sectionD9) {
    this.sectionD9 = sectionD9;
  }

  public String getSectionD10() {
    return this.sectionD10;
  }

  public void setSectionD10(String sectionD10) {
    this.sectionD10 = sectionD10;
  }

  public String getSectionE1() {
    return sectionE1;
  }

  public void setSectionE1(String sectionE1) {
    this.sectionE1 = sectionE1;
  }

  public String getSectionE2() {
    return sectionE2;
  }

  public void setSectionE2(String sectionE2) {
    this.sectionE2 = sectionE2;
  }

  public String getSectionE3() {
    return sectionE3;
  }

  public void setSectionE3(String sectionE3) {
    this.sectionE3 = sectionE3;
  }

  public String getSectionE4() {
    return sectionE4;
  }

  public void setSectionE4(String sectionE4) {
    this.sectionE4 = sectionE4;
  }

  public String getSectionE5() {
    return sectionE5;
  }

  public void setSectionE5(String sectionE5) {
    this.sectionE5 = sectionE5;
  }

  public String getSectionE6() {
    return sectionE6;
  }

  public void setSectionE6(String sectionE6) {
    this.sectionE6 = sectionE6;
  }

  public String getSectionE7() {
    return sectionE7;
  }

  public void setSectionE7(String sectionE7) {
    this.sectionE7 = sectionE7;
  }

  public String getSectionE8() {
    return sectionE8;
  }

  public void setSectionE8(String sectionE8) {
    this.sectionE8 = sectionE8;
  }

  public String getSectionE9() {
    return sectionE9;
  }

  public void setSectionE9(String sectionE9) {
    this.sectionE9 = sectionE9;
  }

  public String getSectionE10() {
    return sectionE10;
  }

  public void setSectionE10(String sectionE10) {
    this.sectionE10 = sectionE10;
  }

  public String getSalesMgrId() {
    return this.salesMgrId;
  }

  public void setSalesMgrId(String salesMgrId) {
    this.salesMgrId = salesMgrId;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getLastUpdtTs() {
    return this.lastUpdtTs;
  }

  public void setLastUpdtTs(Date lastUpdtTs) {
    this.lastUpdtTs = lastUpdtTs;
  }

  public String getLastUpdtBy() {
    return this.lastUpdtBy;
  }

  public void setLastUpdtBy(String lastUpdtBy) {
    this.lastUpdtBy = lastUpdtBy;
  }

  public String getFreeTxtField1() {
    return this.freeTxtField1;
  }

  public void setFreeTxtField1(String freeTxtField1) {
    this.freeTxtField1 = freeTxtField1;
  }

  public String getFreeTxtField2() {
    return this.freeTxtField2;
  }

  public void setFreeTxtField2(String freeTxtField2) {
    this.freeTxtField2 = freeTxtField2;
  }

  public String getFreeTxtField3() {
    return this.freeTxtField3;
  }

  public void setFreeTxtField3(String freeTxtField3) {
    this.freeTxtField3 = freeTxtField3;
  }

  public String getFreeTxtField4() {
    return this.freeTxtField4;
  }

  public void setFreeTxtField4(String freeTxtField4) {
    this.freeTxtField4 = freeTxtField4;
  }

  public String getFreeTxtField5() {
    return this.freeTxtField5;
  }

  public void setFreeTxtField5(String freeTxtField5) {
    this.freeTxtField5 = freeTxtField5;
  }

}