/*
This file was automatically generated by the EntityCreator engine on Mon Oct 23 12:46:19 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * The primary key class for the PROLIF_CHECKLIST database table.
 * 
 * @author Jeffrey Zamora
 */
@Embeddable
public class ProlifChecklistPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "REQ_ID")
  private long reqId;

  public long getReqId() {
    return this.reqId;
  }

  public void setReqId(long reqId) {
    this.reqId = reqId;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof ProlifChecklistPK)) {
      return false;
    }
    ProlifChecklistPK o = (ProlifChecklistPK) other;
    return this.reqId == o.reqId;

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.reqId > 0 ? new java.lang.Long(this.reqId).hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.reqId > 0;

  }
}