/*
This file was automatically generated by the EntityCreator engine on Tue Feb 11 15:37:07 SGT 2020.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * The primary key class for the REFT_UNSIC_W database table.
 * 
 * @author JeffZAMORA
 */
@Embeddable
public class ReftUnsicWPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "REFT_UNSIC_KEY")
  private int reftUnsicKey;

  public int getReftUnsicKey() {
    return this.reftUnsicKey;
  }

  public void setReftUnsicKey(int reftUnsicKey) {
    this.reftUnsicKey = reftUnsicKey;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof ReftUnsicWPK)) {
      return false;
    }
    ReftUnsicWPK o = (ReftUnsicWPK) other;
    return this.reftUnsicKey == o.reftUnsicKey;

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + this.reftUnsicKey;

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.reftUnsicKey > 0;

  }
}