/*
This file was automatically generated by the EntityCreator engine on Tue Feb 11 15:37:07 SGT 2020.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the REFT_UNSIC_W database table.
 * 
 * @author JeffZAMORA
 */
@Entity
@Table(name = "REFT_UNSIC_W", schema = "CMMA")
public class ReftUnsicW extends BaseEntity<ReftUnsicWPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private ReftUnsicWPK id;

  public ReftUnsicWPK getId() {
    return id;
  }

  public void setId(ReftUnsicWPK id) {
    this.id = id;
  }
  
  @Column(name = "REFT_INDCL_KEY")
  private int reftIndclKey;

  @Column(name = "REFT_UNSIC_CD")
  private String reftUnsicCd;

  @Column(name = "REFT_UNSIC_DESC")
  private String reftUnsicDesc;

  @Column(name = "REFT_UNSIC_ABBREV_DESC")
  private String reftUnsicAbbrevDesc;

  @Column(name = "ACTIVE_DATE")
  @Temporal(TemporalType.DATE)
  private Date activeDate;

  /** 
   * Comments - free form 
   */ 
  private String comments;

  @Column(name = "ROW_CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date rowCreateTs;

  @Column(name = "ROW_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date rowUpdtTs;

  @Column(name = "GEO_CD")
  private String geoCd;

  public int getReftIndclKey(){
    return this.reftIndclKey;
  }

  public void setReftIndclKey(int reftIndclKey){
    this.reftIndclKey = reftIndclKey;
  }


  public String getReftUnsicCd(){
    return this.reftUnsicCd;
  }

  public void setReftUnsicCd(String reftUnsicCd){
    this.reftUnsicCd = reftUnsicCd;
  }


  public String getReftUnsicDesc(){
    return this.reftUnsicDesc;
  }

  public void setReftUnsicDesc(String reftUnsicDesc){
    this.reftUnsicDesc = reftUnsicDesc;
  }


  public String getReftUnsicAbbrevDesc(){
    return this.reftUnsicAbbrevDesc;
  }

  public void setReftUnsicAbbrevDesc(String reftUnsicAbbrevDesc){
    this.reftUnsicAbbrevDesc = reftUnsicAbbrevDesc;
  }


  public Date getActiveDate(){
    return this.activeDate;
  }

  public void setActiveDate(Date activeDate){
    this.activeDate = activeDate;
  }


  public String getComments(){
    return this.comments;
  }

  public void setComments(String comments){
    this.comments = comments;
  }


  public Date getRowCreateTs(){
    return this.rowCreateTs;
  }

  public void setRowCreateTs(Date rowCreateTs){
    this.rowCreateTs = rowCreateTs;
  }


  public Date getRowUpdtTs(){
    return this.rowUpdtTs;
  }

  public void setRowUpdtTs(Date rowUpdtTs){
    this.rowUpdtTs = rowUpdtTs;
  }


  public String getGeoCd(){
    return this.geoCd;
  }

  public void setGeoCd(String geoCd){
    this.geoCd = geoCd;
  }




}