/*
This file was automatically generated by the EntityCreator engine on Fri Sep 20 23:54:26 IST 2019.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the REFT_BR_SBO_COLLECTOR database table.
 * 
 * @author RangoliSaxena
 */
@Entity
@Table(name = "REFT_BR_SBO_COLLECTOR", schema = "CMMA")
public class ReftBrSboCollector extends BaseEntity<ReftBrSboCollectorPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private ReftBrSboCollectorPK id;

  @Override
  public ReftBrSboCollectorPK getId() {
    return id;
  }

  @Override
  public void setId(ReftBrSboCollectorPK id) {
    this.id = id;
  }

  /**
   * State Name
   */
  @Column(name = "STATE_NAME")
  private String stateName;

  /**
   * Sales Branch Office
   */
  private String sbo;

  /**
   * Market Responsibilty Code
   */
  @Column(name = "MRC_CD")
  private String mrcCd;

  /**
   * Collector Number
   */
  @Column(name = "COLLECTOR_NO")
  private String collectorNo;

  /**
   * Created By
   */
  @Column(name = "CREATE_BY")
  private String createBy;

  /**
   * Create Timestamp
   */
  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  /**
   * Last Update By
   */
  @Column(name = "LAST_UPDT_BY")
  private String lastUpdtBy;

  /**
   * Last Update Timestamp
   */
  @Column(name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date lastUpdtTs;

  public String getStateName() {
    return this.stateName;
  }

  public void setStateName(String stateName) {
    this.stateName = stateName;
  }

  public String getSbo() {
    return this.sbo;
  }

  public void setSbo(String sbo) {
    this.sbo = sbo;
  }

  public String getMrcCd() {
    return this.mrcCd;
  }

  public void setMrcCd(String mrcCd) {
    this.mrcCd = mrcCd;
  }

  public String getCollectorNo() {
    return this.collectorNo;
  }

  public void setCollectorNo(String collectorNo) {
    this.collectorNo = collectorNo;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getLastUpdtBy() {
    return this.lastUpdtBy;
  }

  public void setLastUpdtBy(String lastUpdtBy) {
    this.lastUpdtBy = lastUpdtBy;
  }

  public Date getLastUpdtTs() {
    return this.lastUpdtTs;
  }

  public void setLastUpdtTs(Date lastUpdtTs) {
    this.lastUpdtTs = lastUpdtTs;
  }

}