/*
This file was automatically generated by the EntityCreator engine on Fri Sep 20 23:54:26 IST 2019.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the REFT_BR_SBO_COLLECTOR database table.
 * 
 * @author RangoliSaxena
 */
@Embeddable
public class ReftBrSboCollectorPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  /** 
   * Brazil State Code
   */ 
  @Column(name = "STATE_CD")
  private String stateCd;

  public String getStateCd(){
    return this.stateCd;
  }

  public void setStateCd(String stateCd){
    this.stateCd = stateCd;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof ReftBrSboCollectorPK)) {
      return false;
    }
    ReftBrSboCollectorPK o = (ReftBrSboCollectorPK) other;
    return this.stateCd.equals(o.stateCd);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.stateCd != null ? this.stateCd.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.stateCd);

  }
}