/*
This file was automatically generated by the EntityCreator engine on Mon Feb 03 16:37:08 IST 2020.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the REP_TEAM database table.
 * 
 * @author AnujaSrivastava
 */
@Entity
@Table(
    name = "REP_TEAM",
    schema = "CREQCMR")
public class RepTeam extends BaseEntity<RepTeamPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private RepTeamPK id;

  @Override
  public RepTeamPK getId() {
    return id;
  }

  @Override
  public void setId(RepTeamPK id) {
    this.id = id;
  }

  @Column(
      name = "REP_TEAM_MEMBER_NAME")
  private String repTeamMemberName;

  @Column(
      name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(
      name = "CREATE_BY_ID")
  private String createById;

  @Column(
      name = "UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updtTs;

  @Column(
      name = "UPDT_BY_ID")
  private String updtById;

  public String getRepTeamMemberName() {
    return this.repTeamMemberName;
  }

  public void setRepTeamMemberName(String repTeamMemberName) {
    this.repTeamMemberName = repTeamMemberName;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateById() {
    return this.createById;
  }

  public void setCreateById(String createById) {
    this.createById = createById;
  }

  public Date getUpdtTs() {
    return this.updtTs;
  }

  public void setUpdtTs(Date updtTs) {
    this.updtTs = updtTs;
  }

  public String getUpdtById() {
    return this.updtById;
  }

  public void setUpdtById(String updtById) {
    this.updtById = updtById;
  }

}