/*
This file was automatically generated by the EntityCreator engine on Tue Jan 19 14:49:41 IST 2016.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * The primary key class for the REQ_CMT_LOG database table.
 * 
 * @author sonali
 */
@Embeddable
public class ReqCmtLogPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "CMT_ID")
  private long cmtId;

  public long getCmtId() {
    return this.cmtId;
  }

  public void setCmtId(long cmtId) {
    this.cmtId = cmtId;
  }

  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof ReqCmtLogPK)) {
      return false;
    }
    ReqCmtLogPK o = (ReqCmtLogPK) other;
    return this.cmtId == o.cmtId;

  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.cmtId > 0 ? new java.lang.Long(this.cmtId).hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.cmtId > 0;

  }
}