/*
This file was automatically generated by the EntityCreator engine on Wed Jun 07 16:05:58 SGT 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the REQUEST_CHANGE_LOG database table.
 * 
 * @author Eduard Bernardo
 */
@Entity
@Table(name = "REQUEST_CHANGE_LOG", schema = "CREQCMR")
public class RequestChangeLog extends BaseEntity<RequestChangeLogPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private RequestChangeLogPK id;

  @Override
  public RequestChangeLogPK getId() {
    return id;
  }

  @Override
  public void setId(RequestChangeLogPK id) {
    this.id = id;
  }

  @Column(name = "ADDR_SEQUENCE")
  private String addrSequence;

  private String action;

  @Column(name = "REQUEST_STATUS")
  private String requestStatus;

  @Column(name = "OLD_VALUE")
  private String oldValue;

  @Column(name = "NEW_VALUE")
  private String newValue;

  @Column(name = "USER_ID")
  private String userId;

  public String getAddrSequence() {
    return this.addrSequence;
  }

  public void setAddrSequence(String addrSequence) {
    this.addrSequence = addrSequence;
  }

  public String getAction() {
    return this.action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public String getRequestStatus() {
    return this.requestStatus;
  }

  public void setRequestStatus(String requestStatus) {
    this.requestStatus = requestStatus;
  }

  public String getOldValue() {
    return this.oldValue;
  }

  public void setOldValue(String oldValue) {
    this.oldValue = oldValue;
  }

  public String getNewValue() {
    return this.newValue;
  }

  public void setNewValue(String newValue) {
    this.newValue = newValue;
  }

  public String getUserId() {
    return this.userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

}