/*
This file was automatically generated by the EntityCreator engine on Tue May 16 16:18:49 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the US_RESTRICT_CODES database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(name = "US_RESTRICT_CODES", schema = "SAPR3")
public class RestrictToCode extends BaseEntity<RestrictToCodePK> implements Serializable {
  private static final long serialVersionUID = 1L;

  public static long getSerialversionuid() {
    return serialVersionUID;
  }

  @EmbeddedId
  private RestrictToCodePK id;

  @Override
  public RestrictToCodePK getId() {
    return id;
  }

  @Override
  public void setId(RestrictToCodePK id) {
    this.id = id;
  }

  @Column(name = "RESTRICT_TO_ABBREV_NM")
  private String nRestrictToAbbrevNm;

  @Column(name = "RESTRICT_TO_NM")
  private String nRestrictToNm;

  @Column(name = "KATR10")
  private String nKatr10;

  @Column(name = "LOEVM")
  private String nLoevm;

  @Column(name = "CREATED_BY")
  private String createBy;

  @Column(name = "CREATE_DT")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createDate;

  @Column(name = "UPDATED_BY")
  private String updateBy;

  @Column(name = "UPDATE_DT")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateDate;

  @Column(name = "UPDATE_TYPE")
  private String updateType;

  public String getnRestrictToAbbrevNm() {
    return nRestrictToAbbrevNm;
  }

  public void setnRestrictToAbbrevNm(String nRestrictToAbbrevNm) {
    this.nRestrictToAbbrevNm = nRestrictToAbbrevNm;
  }

  public String getnRestrictToNm() {
    return nRestrictToNm;
  }

  public void setnRestrictToNm(String nRestrictToNm) {
    this.nRestrictToNm = nRestrictToNm;
  }

  public String getnKatr10() {
    return nKatr10;
  }

  public void setnKatr10(String nKatr10) {
    this.nKatr10 = nKatr10;
  }

  public String getnLoevm() {
    return nLoevm;
  }

  public void setnLoevm(String nLoevm) {
    this.nLoevm = nLoevm;
  }

  public String getCreateBy() {
    return createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  public String getUpdateBy() {
    return updateBy;
  }

  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  public Date getUpdateDate() {
    return updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }

  public String getUpdateType() {
    return updateType;
  }

  public void setUpdateType(String updateType) {
    this.updateType = updateType;
  }

}