/*
This file was automatically generated by the EntityCreator engine on Tue Jun 27 15:24:01 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the ROLES database table.
 * 
 * @author P01925
 */
@Entity
@Table(name = "ROLES", schema = "CMMA")
public class Roles extends BaseEntity<RolesPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private RolesPK id;

  @Override
  public RolesPK getId() {
    return id;
  }

  @Override
  public void setId(RolesPK id) {
    this.id = id;
  }

  @Column(name = "ROLE_NAME")
  private String roleName;

  @Column(name = "APPLICATION_CD")
  private String applicationCd;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(name = "CREATE_BY")
  private String createBy;

  @Column(name = "UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateTs;

  @Column(name = "UPDATE_BY")
  private String updateBy;

  @Column(name = "STATUS")
  private String status;

  @Column(name = "COMMENTS")
  private String comments;

  public String getRoleName() {
    return this.roleName;
  }

  public void setRoleName(String roleName) {
    this.roleName = roleName;
  }

  public String getApplicationCd() {
    return this.applicationCd;
  }

  public void setApplicationCd(String applicationCd) {
    this.applicationCd = applicationCd;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getUpdateTs() {
    return this.updateTs;
  }

  public void setUpdateTs(Date updateTs) {
    this.updateTs = updateTs;
  }

  public String getUpdateBy() {
    return this.updateBy;
  }

  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getComments() {
    return this.comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

}