/*
This file was automatically generated by the EntityCreator engine on Fri Apr 13 21:49:12 SGT 2018.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the SADR database table.
 * 
 * @author DennisNATAD
 */
@Entity
@Table(name = "SADR", schema = "SAPR3")
public class Sadr extends BaseEntity<SadrPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private SadrPK id;

  @Override
  public SadrPK getId() {
    return id;
  }

  @Override
  public void setId(SadrPK id) {
    this.id = id;
  }

  @Column(name = "ANRED")
  private String anred;

  @Column(name = "NAME1")
  private String name1;

  @Column(name = "NAME2")
  private String name2;

  @Column(name = "NAME3")
  private String name3;

  @Column(name = "NAME4")
  private String name4;

  @Column(name = "PSTLZ")
  private String pstlz;

  @Column(name = "ORT01")
  private String ort01;

  @Column(name = "ORT02")
  private String ort02;

  @Column(name = "PSTL2")
  private String pstl2;

  @Column(name = "PFACH")
  private String pfach;

  @Column(name = "STRAS")
  private String stras;

  @Column(name = "STRS2")
  private String strs2;

  @Column(name = "HAUSN")
  private String hausn;

  @Column(name = "STOCK")
  private String stock;

  @Column(name = "LAND1")
  private String land1;

  @Column(name = "SORTL")
  private String sortl;

  @Column(name = "SORT2")
  private String sort2;

  @Column(name = "SPRAS")
  private String spras;

  @Column(name = "LZONE")
  private String lzone;

  @Column(name = "REGIO")
  private String regio;

  @Column(name = "PSTBZ")
  private String pstbz;

  @Column(name = "TELF1")
  private String telf1;

  @Column(name = "FLAG")
  private String flag;

  @Column(name = "TELFX")
  private String telfx;

  @Column(name = "FLAG2")
  private String flag2;

  @Column(name = "TELTX")
  private String teltx;

  @Column(name = "FLAG3")
  private String flag3;

  @Column(name = "TELX1")
  private String telx1;

  @Column(name = "FLAG4")
  private String flag4;

  @Column(name = "MAIAD")
  private String maiad;

  @Column(name = "MAILN")
  private String mailn;

  @Column(name = "STDKO")
  private String stdko;

  @Column(name = "STDCOM")
  private String stdcom;

  @Column(name = "DBNAME")
  private String dbname;

  @Column(name = "KLASSE")
  private String klasse;

  @Column(name = "ANREK")
  private String anrek;

  @Column(name = "CRNAM")
  private String crnam;

  @Column(name = "CRDAT")
  private String crdat;

  @Column(name = "CRTIM")
  private String crtim;

  @Column(name = "CHNAM")
  private String chnam;

  @Column(name = "CHDAT")
  private String chdat;

  @Column(name = "CHTIM")
  private String chtim;

  @Column(name = "DUEFL")
  private String duefl;

  @Column(name = "TXJCD")
  private String txjcd;

  @Column(name = "PFORT")
  private String pfort;

  @Column(name = "TZONE")
  private String tzone;

  @Column(name = "BUILDING")
  private String building;

  @Column(name = "ROOMNUMBER")
  private String roomnumber;

  @Column(name = "SHAD_UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date shadUpdateTs;

  @Column(name = "SHAD_UPDATE_IND")
  private String shadUpdateInd;

  @Column(name = "SAP_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date sapTs;

  public String getAnred() {
    return this.anred;
  }

  public void setAnred(String anred) {
    this.anred = anred;
  }

  public String getName1() {
    return this.name1;
  }

  public void setName1(String name1) {
    this.name1 = name1;
  }

  public String getName2() {
    return this.name2;
  }

  public void setName2(String name2) {
    this.name2 = name2;
  }

  public String getName3() {
    return this.name3;
  }

  public void setName3(String name3) {
    this.name3 = name3;
  }

  public String getName4() {
    return this.name4;
  }

  public void setName4(String name4) {
    this.name4 = name4;
  }

  public String getPstlz() {
    return this.pstlz;
  }

  public void setPstlz(String pstlz) {
    this.pstlz = pstlz;
  }

  public String getOrt01() {
    return this.ort01;
  }

  public void setOrt01(String ort01) {
    this.ort01 = ort01;
  }

  public String getOrt02() {
    return this.ort02;
  }

  public void setOrt02(String ort02) {
    this.ort02 = ort02;
  }

  public String getPstl2() {
    return this.pstl2;
  }

  public void setPstl2(String pstl2) {
    this.pstl2 = pstl2;
  }

  public String getPfach() {
    return this.pfach;
  }

  public void setPfach(String pfach) {
    this.pfach = pfach;
  }

  public String getStras() {
    return this.stras;
  }

  public void setStras(String stras) {
    this.stras = stras;
  }

  public String getStrs2() {
    return this.strs2;
  }

  public void setStrs2(String strs2) {
    this.strs2 = strs2;
  }

  public String getHausn() {
    return this.hausn;
  }

  public void setHausn(String hausn) {
    this.hausn = hausn;
  }

  public String getStock() {
    return this.stock;
  }

  public void setStock(String stock) {
    this.stock = stock;
  }

  public String getLand1() {
    return this.land1;
  }

  public void setLand1(String land1) {
    this.land1 = land1;
  }

  public String getSortl() {
    return this.sortl;
  }

  public void setSortl(String sortl) {
    this.sortl = sortl;
  }

  public String getSort2() {
    return this.sort2;
  }

  public void setSort2(String sort2) {
    this.sort2 = sort2;
  }

  public String getSpras() {
    return this.spras;
  }

  public void setSpras(String spras) {
    this.spras = spras;
  }

  public String getLzone() {
    return this.lzone;
  }

  public void setLzone(String lzone) {
    this.lzone = lzone;
  }

  public String getRegio() {
    return this.regio;
  }

  public void setRegio(String regio) {
    this.regio = regio;
  }

  public String getPstbz() {
    return this.pstbz;
  }

  public void setPstbz(String pstbz) {
    this.pstbz = pstbz;
  }

  public String getTelf1() {
    return this.telf1;
  }

  public void setTelf1(String telf1) {
    this.telf1 = telf1;
  }

  public String getFlag() {
    return this.flag;
  }

  public void setFlag(String flag) {
    this.flag = flag;
  }

  public String getTelfx() {
    return this.telfx;
  }

  public void setTelfx(String telfx) {
    this.telfx = telfx;
  }

  public String getFlag2() {
    return this.flag2;
  }

  public void setFlag2(String flag2) {
    this.flag2 = flag2;
  }

  public String getTeltx() {
    return this.teltx;
  }

  public void setTeltx(String teltx) {
    this.teltx = teltx;
  }

  public String getFlag3() {
    return this.flag3;
  }

  public void setFlag3(String flag3) {
    this.flag3 = flag3;
  }

  public String getTelx1() {
    return this.telx1;
  }

  public void setTelx1(String telx1) {
    this.telx1 = telx1;
  }

  public String getFlag4() {
    return this.flag4;
  }

  public void setFlag4(String flag4) {
    this.flag4 = flag4;
  }

  public String getMaiad() {
    return this.maiad;
  }

  public void setMaiad(String maiad) {
    this.maiad = maiad;
  }

  public String getMailn() {
    return this.mailn;
  }

  public void setMailn(String mailn) {
    this.mailn = mailn;
  }

  public String getStdko() {
    return this.stdko;
  }

  public void setStdko(String stdko) {
    this.stdko = stdko;
  }

  public String getStdcom() {
    return this.stdcom;
  }

  public void setStdcom(String stdcom) {
    this.stdcom = stdcom;
  }

  public String getDbname() {
    return this.dbname;
  }

  public void setDbname(String dbname) {
    this.dbname = dbname;
  }

  public String getKlasse() {
    return this.klasse;
  }

  public void setKlasse(String klasse) {
    this.klasse = klasse;
  }

  public String getAnrek() {
    return this.anrek;
  }

  public void setAnrek(String anrek) {
    this.anrek = anrek;
  }

  public String getCrnam() {
    return this.crnam;
  }

  public void setCrnam(String crnam) {
    this.crnam = crnam;
  }

  public String getCrdat() {
    return this.crdat;
  }

  public void setCrdat(String crdat) {
    this.crdat = crdat;
  }

  public String getCrtim() {
    return this.crtim;
  }

  public void setCrtim(String crtim) {
    this.crtim = crtim;
  }

  public String getChnam() {
    return this.chnam;
  }

  public void setChnam(String chnam) {
    this.chnam = chnam;
  }

  public String getChdat() {
    return this.chdat;
  }

  public void setChdat(String chdat) {
    this.chdat = chdat;
  }

  public String getChtim() {
    return this.chtim;
  }

  public void setChtim(String chtim) {
    this.chtim = chtim;
  }

  public String getDuefl() {
    return this.duefl;
  }

  public void setDuefl(String duefl) {
    this.duefl = duefl;
  }

  public String getTxjcd() {
    return this.txjcd;
  }

  public void setTxjcd(String txjcd) {
    this.txjcd = txjcd;
  }

  public String getPfort() {
    return this.pfort;
  }

  public void setPfort(String pfort) {
    this.pfort = pfort;
  }

  public String getTzone() {
    return this.tzone;
  }

  public void setTzone(String tzone) {
    this.tzone = tzone;
  }

  public String getBuilding() {
    return this.building;
  }

  public void setBuilding(String building) {
    this.building = building;
  }

  public String getRoomnumber() {
    return this.roomnumber;
  }

  public void setRoomnumber(String roomnumber) {
    this.roomnumber = roomnumber;
  }

  public Date getShadUpdateTs() {
    return this.shadUpdateTs;
  }

  public void setShadUpdateTs(Date shadUpdateTs) {
    this.shadUpdateTs = shadUpdateTs;
  }

  public String getShadUpdateInd() {
    return this.shadUpdateInd;
  }

  public void setShadUpdateInd(String shadUpdateInd) {
    this.shadUpdateInd = shadUpdateInd;
  }

  public Date getSapTs() {
    return this.sapTs;
  }

  public void setSapTs(Date sapTs) {
    this.sapTs = sapTs;
  }

}