/*
This file was automatically generated by the EntityCreator engine on Fri Apr 13 21:49:12 SGT 2018.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the SADR database table.
 * 
 * @author DennisNATAD
 */
@Embeddable
public class SadrPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  private String mandt;

  private String adrnr;

  private String natio;

  public String getMandt(){
    return this.mandt;
  }

  public void setMandt(String mandt){
    this.mandt = mandt;
  }


  public String getAdrnr(){
    return this.adrnr;
  }

  public void setAdrnr(String adrnr){
    this.adrnr = adrnr;
  }


  public String getNatio(){
    return this.natio;
  }

  public void setNatio(String natio){
    this.natio = natio;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof SadrPK)) {
      return false;
    }
    SadrPK o = (SadrPK) other;
    return this.mandt.equals(o.mandt) && this.adrnr.equals(o.adrnr) && this.natio.equals(o.natio);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.mandt != null ? this.mandt.hashCode() : 0);
    hash = hash * prime + (this.adrnr != null ? this.adrnr.hashCode() : 0);
    hash = hash * prime + (this.natio != null ? this.natio.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.mandt) && !StringUtils.isEmpty(this.adrnr) && !StringUtils.isEmpty(this.natio);

  }
}