/*
This file was automatically generated by the EntityCreator engine on Thu Jan 23 16:55:16 IST 2020.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the SALES_BRANCH_OFF database table.
 * 
 * @author RoopakChugh
 */
@Entity
@Table(
    name = "SALES_BRANCH_OFF",
    schema = "CREQCMR")
public class SalesBranchOff extends BaseEntity<SalesBranchOffPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private SalesBranchOffPK id;

  public SalesBranchOffPK getId() {
    return id;
  }

  public void setId(SalesBranchOffPK id) {
    this.id = id;
  }

  @Column(
      name = "SALES_BO_DESC")
  private String salesBoDesc;

  @Column(
      name = "MRC_CD")
  private String mrcCd;

  @Column(
      name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(
      name = "CREATE_BY_ID")
  private String createById;

  @Column(
      name = "UPDATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateTs;

  @Column(
      name = "UPDATE_BY_ID")
  private String updateById;

  @Column(
      name = "CLIENT_TIER")
  private String clientTier;

  @Column(
      name = "ISU_CD")
  private String isuCd;

  public String getSalesBoDesc() {
    return this.salesBoDesc;
  }

  public void setSalesBoDesc(String salesBoDesc) {
    this.salesBoDesc = salesBoDesc;
  }

  public String getMrcCd() {
    return this.mrcCd;
  }

  public void setMrcCd(String mrcCd) {
    this.mrcCd = mrcCd;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateById() {
    return this.createById;
  }

  public void setCreateById(String createById) {
    this.createById = createById;
  }

  public Date getUpdateTs() {
    return this.updateTs;
  }

  public void setUpdateTs(Date updateTs) {
    this.updateTs = updateTs;
  }

  public String getUpdateById() {
    return this.updateById;
  }

  public void setUpdateById(String updateById) {
    this.updateById = updateById;
  }

  public String getClientTier() {
    return this.clientTier;
  }

  public void setClientTier(String clientTier) {
    this.clientTier = clientTier;
  }

  public String getIsuCd() {
    return this.isuCd;
  }

  public void setIsuCd(String isuCd) {
    this.isuCd = isuCd;
  }

}