/*
This file was automatically generated by the EntityCreator engine on Wed Oct 24 20:07:59 SGT 2018.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the SC_ACCOUNT_CMR_STG database table.
 * 
 * @author JeffZAMORA
 */
@Entity
@Table(name = "SC_ACCOUNT_CMR_STG", schema = "SAPR3")
public class ScAccountCmrStg implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private ScAccountCmrStgPK id;

  public ScAccountCmrStgPK getId() {
    return id;
  }

  public void setId(ScAccountCmrStgPK id) {
    this.id = id;
  }

  @Column(name = "CMR_SYS_LOC_CD")
  private String cmrSysLocCd;

  @Column(name = "LEGACY_CMR_NO")
  private String legacyCmrNo;

  /**
   * Create Time stamp
   */
  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  public String getCmrSysLocCd() {
    return this.cmrSysLocCd;
  }

  public void setCmrSysLocCd(String cmrSysLocCd) {
    this.cmrSysLocCd = cmrSysLocCd;
  }

  public String getLegacyCmrNo() {
    return this.legacyCmrNo;
  }

  public void setLegacyCmrNo(String legacyCmrNo) {
    this.legacyCmrNo = legacyCmrNo;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

}