/*
This file was automatically generated by the EntityCreator engine on Mon Jan 09 14:53:55 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the STATUS_DESC database table.
 * 
 * @author Rama mohan
 */
@Entity
@Table(name = "STATUS_DESC", schema = "CREQCMR")
public class StatusDesc extends BaseEntity<StatusDescPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private StatusDescPK id;

  @Override
  public StatusDescPK getId() {
    return id;
  }

  @Override
  public void setId(StatusDescPK id) {
    this.id = id;
  }

  @Column(name = "CMR_ISSUING_CNTRY")
  private String cmrIssuingCntry;

  @Column(name = "STATUS_DESC")
  private String statusDesc;

  public String getCmrIssuingCntry() {
    return this.cmrIssuingCntry;
  }

  public void setCmrIssuingCntry(String cmrIssuingCntry) {
    this.cmrIssuingCntry = cmrIssuingCntry;
  }

  public String getStatusDesc() {
    return this.statusDesc;
  }

  public void setStatusDesc(String statusDesc) {
    this.statusDesc = statusDesc;
  }

}