/*
This file was automatically generated by the EntityCreator engine on Tue Jun 27 15:07:47 CST 2017.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the STATUS_ACT database table.
 * 
 * @author P01925
 */
@Embeddable
public class StatusActPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  private String action;

  public String getAction(){
    return this.action;
  }

  public void setAction(String action){
    this.action = action;
  }




  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof StatusActPK)) {
      return false;
    }
    StatusActPK o = (StatusActPK) other;
    return this.action.equals(o.action);


  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.action != null ? this.action.hashCode() : 0);


    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.action);

  }
}