/*
This file was automatically generated by the EntityCreator engine on Tue Jun 27 15:07:47 CST 2017.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the STATUS_ACT database table.
 * 
 * @author P01925
 */
@Entity
@Table(name = "STATUS_ACT", schema = "CREQCMR")
public class StatusAct extends BaseEntity<StatusActPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private StatusActPK id;

  public StatusActPK getId() {
    return id;
  }

  public void setId(StatusActPK id) {
    this.id = id;
  }
  
  @Column(name = "CMR_ISSUING_CNTRY")
  private String cmrIssuingCntry;

  @Column(name = "ACTION_DESC")
  private String actionDesc;

  public String getCmrIssuingCntry(){
    return this.cmrIssuingCntry;
  }

  public void setCmrIssuingCntry(String cmrIssuingCntry){
    this.cmrIssuingCntry = cmrIssuingCntry;
  }


  public String getActionDesc(){
    return this.actionDesc;
  }

  public void setActionDesc(String actionDesc){
    this.actionDesc = actionDesc;
  }




}