/*
This file was automatically generated by the EntityCreator engine on Wed Sep 21 15:23:03 CST 2016.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the STATUS_TRANS database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(name = "STATUS_TRANS", schema = "CREQCMR")
public class StatusTrans extends BaseEntity<StatusTransPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private StatusTransPK id;

  @Override
  public StatusTransPK getId() {
    return id;
  }

  @Override
  public void setId(StatusTransPK id) {
    this.id = id;
  }

  @Column(name = "NEW_REQ_STATUS")
  private String newReqStatus;

  @Column(name = "NEW_LOCKED_IND")
  private String newLockedInd;

  @Column(name = "DISP_ORDER")
  private int dispOrder;

  @Column(name = "SEP_VAL_IND")
  private String sepValInd;

  @Column(name = "DISABLE_AUTO_PROC")
  private String disableAutoProc;

  public String getNewReqStatus() {
    return this.newReqStatus;
  }

  public void setNewReqStatus(String newReqStatus) {
    this.newReqStatus = newReqStatus;
  }

  public String getNewLockedInd() {
    return this.newLockedInd;
  }

  public void setNewLockedInd(String newLockedInd) {
    this.newLockedInd = newLockedInd;
  }

  public int getDispOrder() {
    return this.dispOrder;
  }

  public void setDispOrder(int dispOrder) {
    this.dispOrder = dispOrder;
  }

  public String getSepValInd() {
    return this.sepValInd;
  }

  public void setSepValInd(String sepValInd) {
    this.sepValInd = sepValInd;
  }

  public String getDisableAutoProc() {
    return this.disableAutoProc;
  }

  public void setDisableAutoProc(String disableAutoProc) {
    this.disableAutoProc = disableAutoProc;
  }

}