/*
This file was automatically generated by the EntityCreator engine on Tue May 25 13:27:08 IST 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Embeddable;

import org.apache.commons.lang3.StringUtils;

/**
 * The primary key class for the STXL database table.
 * 
 * @author PriyRanjan
 */
@Embeddable
public class StxlPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  /**
   * SAP instance
   */
  private String mandt;

  private String relid;

  private String tdobject;

  private String tdname;

  private String tdid;

  private String tdspras;

  private String srtf2;

  /**
   * BIN1 data element for SYST
   */

  public String getMandt() {
    return this.mandt;
  }

  public void setMandt(String mandt) {
    this.mandt = mandt;
  }

  public String getRelid() {
    return this.relid;
  }

  public void setRelid(String relid) {
    this.relid = relid;
  }

  public String getTdobject() {
    return this.tdobject;
  }

  public void setTdobject(String tdobject) {
    this.tdobject = tdobject;
  }

  public String getTdname() {
    return this.tdname;
  }

  public void setTdname(String tdname) {
    this.tdname = tdname;
  }

  public String getTdid() {
    return this.tdid;
  }

  public void setTdid(String tdid) {
    this.tdid = tdid;
  }

  public String getTdspras() {
    return this.tdspras;
  }

  public void setTdspras(String tdspras) {
    this.tdspras = tdspras;
  }

  public String getSrtf2() {
    return srtf2;
  }

  public void setSrtf2(String srtf2) {
    this.srtf2 = srtf2;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof StxlPK)) {
      return false;
    }
    StxlPK o = (StxlPK) other;
    return this.mandt.equals(o.mandt) && this.relid.equals(o.relid) && this.tdobject.equals(o.tdobject) && this.tdname.equals(o.tdname)
        && this.tdid.equals(o.tdid) && this.tdspras.equals(o.tdspras) && this.srtf2.equals(o.srtf2);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.mandt != null ? this.mandt.hashCode() : 0);
    hash = hash * prime + (this.relid != null ? this.relid.hashCode() : 0);
    hash = hash * prime + (this.tdobject != null ? this.tdobject.hashCode() : 0);
    hash = hash * prime + (this.tdname != null ? this.tdname.hashCode() : 0);
    hash = hash * prime + (this.tdid != null ? this.tdid.hashCode() : 0);
    hash = hash * prime + (this.tdspras != null ? this.tdspras.hashCode() : 0);
    hash = hash * prime + (this.srtf2 != null ? this.srtf2.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.mandt) && !StringUtils.isEmpty(this.relid) && !StringUtils.isEmpty(this.tdobject)
        && !StringUtils.isEmpty(this.tdname) && !StringUtils.isEmpty(this.tdid) && !StringUtils.isEmpty(this.tdspras)
        && !StringUtils.isEmpty(this.srtf2);

  }
}