/*
This file was automatically generated by the EntityCreator engine on Fri Oct 09 11:15:33 IST 2020.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the SUPP_CNTRY database table.
 * 
 * @author RoopakChugh
 */
@Entity
@Table(name = "SUPP_CNTRY", schema = "CREQCMR")
public class SuppCntry extends BaseEntity<SuppCntryPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private SuppCntryPK id;

  @Override
  public SuppCntryPK getId() {
    return id;
  }

  @Override
  public void setId(SuppCntryPK id) {
    this.id = id;
  }

  private String nm;

  @Column(name = "CREATE_DT")
  @Temporal(TemporalType.DATE)
  private Date createDt;

  private String cmt;

  @Column(name = "AUTO_PROC_ENABLED")
  private String autoProcEnabled;

  @Column(name = "HOST_SYS_TYP")
  private String hostSysTyp;

  @Column(name = "SUPP_REQ_TYPE")
  private String suppReqType;

  @Column(name = "DEFAULT_LANDED_CNTRY")
  private String defaultLandedCntry;

  @Column(name = "PROCESSING_TYP")
  private String processingTyp;

  /**
   * Automation Engine Indicator
   */
  @Column(name = "AUTO_ENGINE_INDC")
  private String autoEngineIndc;

  /**
   * Recovery Direction
   */
  @Column(name = "RECOVERY_DIRECTION")
  private String recoveryDirection;

  @Column(name = "DNB_PRIMARY_INDC")
  private String dnbPrimaryIndc;

  /**
   * Start from Quick Search
   */
  @Column(name = "START_QUICK_SEARCH")
  private String startQuickSearch;

  /**
   * Tradestyle Name Usage
   */
  @Column(name = "TRADESTYLE_NM_USAGE")
  private String tradestyleNmUsage;

  /**
   * Tradestyle Name Usage
   */
  @Column(name = "DISABLE_CREATE_BY_MODEL")
  private String disableCreateByModel;

  @Column(name = "HIDE_LOCAL_LANG_DATA")
  private String hideLocalLangData;

  public String getNm() {
    return this.nm;
  }

  public void setNm(String nm) {
    this.nm = nm;
  }

  public Date getCreateDt() {
    return this.createDt;
  }

  public void setCreateDt(Date createDt) {
    this.createDt = createDt;
  }

  public String getCmt() {
    return this.cmt;
  }

  public void setCmt(String cmt) {
    this.cmt = cmt;
  }

  public String getAutoProcEnabled() {
    return this.autoProcEnabled;
  }

  public void setAutoProcEnabled(String autoProcEnabled) {
    this.autoProcEnabled = autoProcEnabled;
  }

  public String getHostSysTyp() {
    return this.hostSysTyp;
  }

  public void setHostSysTyp(String hostSysTyp) {
    this.hostSysTyp = hostSysTyp;
  }

  public String getSuppReqType() {
    return this.suppReqType;
  }

  public void setSuppReqType(String suppReqType) {
    this.suppReqType = suppReqType;
  }

  public String getDefaultLandedCntry() {
    return this.defaultLandedCntry;
  }

  public void setDefaultLandedCntry(String defaultLandedCntry) {
    this.defaultLandedCntry = defaultLandedCntry;
  }

  public String getProcessingTyp() {
    return this.processingTyp;
  }

  public void setProcessingTyp(String processingTyp) {
    this.processingTyp = processingTyp;
  }

  public String getAutoEngineIndc() {
    return this.autoEngineIndc;
  }

  public void setAutoEngineIndc(String autoEngineIndc) {
    this.autoEngineIndc = autoEngineIndc;
  }

  public String getRecoveryDirection() {
    return this.recoveryDirection;
  }

  public void setRecoveryDirection(String recoveryDirection) {
    this.recoveryDirection = recoveryDirection;
  }

  public String getDnbPrimaryIndc() {
    return this.dnbPrimaryIndc;
  }

  public void setDnbPrimaryIndc(String dnbPrimaryIndc) {
    this.dnbPrimaryIndc = dnbPrimaryIndc;
  }

  public String getStartQuickSearch() {
    return this.startQuickSearch;
  }

  public void setStartQuickSearch(String startQuickSearch) {
    this.startQuickSearch = startQuickSearch;
  }

  public String getTradestyleNmUsage() {
    return this.tradestyleNmUsage;
  }

  public void setTradestyleNmUsage(String tradestyleNmUsage) {
    this.tradestyleNmUsage = tradestyleNmUsage;
  }

  public String getDisableCreateByModel() {
    return disableCreateByModel;
  }

  public void setDisableCreateByModel(String disableCreateByModel) {
    this.disableCreateByModel = disableCreateByModel;
  }

  public String getHideLocalLangData() {
    return hideLocalLangData;
  }

  public void setHideLocalLangData(String hideLocalLangData) {
    this.hideLocalLangData = hideLocalLangData;
  }

}