/*
This file was automatically generated by the EntityCreator engine on Tue May 02 22:45:02 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the SUPP_CNTRY database table.
 * 
 * @author P01925
 */
@Entity
@Table(
    name = "SUPP_CNTRY",
    schema = "CREQCMR")
public class SuppCntry extends BaseEntity<SuppCntryPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private SuppCntryPK id;

  @Override
  public SuppCntryPK getId() {
    return id;
  }

  @Override
  public void setId(SuppCntryPK id) {
    this.id = id;
  }

  @Column(
      name = "NM")
  private String nm;

  @Column(
      name = "CREATE_DT")
  @Temporal(TemporalType.DATE)
  private Date createDt;

  @Column(
      name = "CMT")
  private String cmt;

  @Column(
      name = "AUTO_PROC_ENABLED")
  private String autoProcEnabled;

  @Column(
      name = "HOST_SYS_TYP")
  private String hostSysTyp;

  @Column(
      name = "SUPP_REQ_TYPE")
  private String suppReqType;

  @Column(
      name = "DEFAULT_LANDED_CNTRY")
  private String defaultLandedCntry;

  @Column(
      name = "PROCESSING_TYP")
  private String processingTyp;

  @Column(
      name = "AUTO_ENGINE_INDC")
  private String autoEngineIndc;

  @Column(
      name = "RECOVERY_DIRECTION")
  private String recoveryDirection;

  @Column(name = "DNB_PRIMARY_INDC")
  private String dnbPrimaryIndc;

  public String getNm() {
    return this.nm;
  }

  public void setNm(String nm) {
    this.nm = nm;
  }

  public Date getCreateDt() {
    return this.createDt;
  }

  public void setCreateDt(Date createDt) {
    this.createDt = createDt;
  }

  public String getCmt() {
    return this.cmt;
  }

  public void setCmt(String cmt) {
    this.cmt = cmt;
  }

  public String getAutoProcEnabled() {
    return this.autoProcEnabled;
  }

  public void setAutoProcEnabled(String autoProcEnabled) {
    this.autoProcEnabled = autoProcEnabled;
  }

  public String getHostSysTyp() {
    return this.hostSysTyp;
  }

  public void setHostSysTyp(String hostSysTyp) {
    this.hostSysTyp = hostSysTyp;
  }

  public String getSuppReqType() {
    return suppReqType;
  }

  public void setSuppReqType(String suppReqType) {
    this.suppReqType = suppReqType;
  }

  public String getDefaultLandedCntry() {
    return defaultLandedCntry;
  }

  public void setDefaultLandedCntry(String defaultLandedCntry) {
    this.defaultLandedCntry = defaultLandedCntry;
  }

  public String getProcessingTyp() {
    return this.processingTyp;
  }

  public void setProcessingTyp(String processingTyp) {
    this.processingTyp = processingTyp;
  }

  public String getAutoEngineIndc() {
    return autoEngineIndc;
  }

  public void setAutoEngineIndc(String autoEngineIndc) {
    this.autoEngineIndc = autoEngineIndc;
  }

  public String getRecoveryDirection() {
    return recoveryDirection;
  }

  public void setRecoveryDirection(String recoveryDirection) {
    this.recoveryDirection = recoveryDirection;
  }

  public String getDnbPrimaryIndc() {
    return dnbPrimaryIndc;
  }

  public void setDnbPrimaryIndc(String dnbPrimaryIndc) {
    this.dnbPrimaryIndc = dnbPrimaryIndc;
  }

}