/*
This file was automatically generated by the EntityCreator engine on Wed Jul 26 23:20:26 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the SYST_PARAMETERS database table.
 * 
 * @author
 */
@Entity
@Table(name = "SYST_PARAMETERS", schema = "CREQCMR")
public class SystParameters extends BaseEntity<SystParametersPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private SystParametersPK id;

  @Override
  public SystParametersPK getId() {
    return id;
  }

  @Override
  public void setId(SystParametersPK id) {
    this.id = id;
  }

  @Column(name = "PARAMETER_NAME")
  private String parameterName;

  @Column(name = "PARAMETER_TYP")
  private String parameterTyp;

  @Column(name = "PARAMETER_VALUE")
  private String parameterValue;

  @Column(name = "CMDE_MAINTAINABLE_INDC")
  private String cmdeMaintainableIndc;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createTs;

  @Column(name = "CREATE_BY")
  private String createBy;

  @Column(name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date lastUpdtTs;

  @Column(name = "LAST_UPDT_BY")
  private String lastUpdtBy;

  public String getParameterName() {
    return this.parameterName;
  }

  public void setParameterName(String parameterName) {
    this.parameterName = parameterName;
  }

  public String getParameterTyp() {
    return this.parameterTyp;
  }

  public void setParameterTyp(String parameterTyp) {
    this.parameterTyp = parameterTyp;
  }

  public String getParameterValue() {
    return this.parameterValue;
  }

  public void setParameterValue(String parameterValue) {
    this.parameterValue = parameterValue;
  }

  public String getCmdeMaintainableIndc() {
    return this.cmdeMaintainableIndc;
  }

  public void setCmdeMaintainableIndc(String cmdeMaintainableIndc) {
    this.cmdeMaintainableIndc = cmdeMaintainableIndc;
  }

  public Date getCreateTs() {
    return this.createTs;
  }

  public void setCreateTs(Date createTs) {
    this.createTs = createTs;
  }

  public String getCreateBy() {
    return this.createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getLastUpdtTs() {
    return this.lastUpdtTs;
  }

  public void setLastUpdtTs(Date lastUpdtTs) {
    this.lastUpdtTs = lastUpdtTs;
  }

  public String getLastUpdtBy() {
    return this.lastUpdtBy;
  }

  public void setLastUpdtBy(String lastUpdtBy) {
    this.lastUpdtBy = lastUpdtBy;
  }

}