/*
This file was automatically generated by the EntityCreator engine on Wed Jul 26 23:20:26 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the SYST_PARAMETERS database table.
 * 
 * @author
 */
@Embeddable
public class SystParametersPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "PARAMETER_CD")
  private String parameterCd;

  public String getParameterCd() {
    return this.parameterCd;
  }

  public void setParameterCd(String parameterCd) {
    this.parameterCd = parameterCd;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof SystParametersPK)) {
      return false;
    }
    SystParametersPK o = (SystParametersPK) other;
    return this.parameterCd.equals(o.parameterCd);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.parameterCd != null ? this.parameterCd.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.parameterCd);

  }
}