/*
This file was automatically generated by the EntityCreator engine on Thu Oct 01 20:28:34 CST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the TGME_CODES database table.
 * 
 * @author Jeffrey Zamora
 */
@Embeddable
public class TgmeCodesPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  private String cd;

  public String getCd() {
    return this.cd;
  }

  public void setCd(String cd) {
    this.cd = cd;
  }

  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof TgmeCodesPK)) {
      return false;
    }
    TgmeCodesPK o = (TgmeCodesPK) other;
    return this.cd.equals(o.cd);

  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.cd != null ? this.cd.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.cd);

  }
}