/*
This file was automatically generated by the EntityCreator engine on Tue May 16 16:18:49 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * The primary key class for the A11T0SCC database table.
 * 
 * @author Jeffrey Zamora
 */
@Embeddable
public class USCMRSccPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(
      name = "SCC_ID")
  private long sccId;

  public long getSccId() {
    return sccId;
  }

  public void setSccId(long sccId) {
    this.sccId = sccId;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof USCMRSccPK)) {
      return false;
    }
    USCMRSccPK o = (USCMRSccPK) other;
    return this.sccId == o.sccId;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.sccId > 0 ? new java.lang.Long(this.sccId).hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.sccId > 0;

  }
}