/*
This file was automatically generated by the EntityCreator engine on Tue May 16 16:18:49 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the A11T0SCC database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(name = "US_CMR_SCC", schema = "CREQCMR")
public class USCMRScc extends BaseEntity<USCMRSccPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  public static long getSerialversionuid() {
    return serialVersionUID;
  }

  @EmbeddedId
  private USCMRSccPK id;

  @Override
  public USCMRSccPK getId() {
    return id;
  }

  @Override
  public void setId(USCMRSccPK id) {
    this.id = id;
  }

  public String getnCity() {
    return nCity;
  }

  public void setnCity(String nCity) {
    this.nCity = nCity;
  }

  public String getnSt() {
    return nSt;
  }

  public void setnSt(String nSt) {
    this.nSt = nSt;
  }

  public String getnCnty() {
    return nCnty;
  }

  public void setnCnty(String nCnty) {
    this.nCnty = nCnty;
  }

  public int getcZip() {
    return cZip;
  }

  public void setcZip(int cZip) {
    this.cZip = cZip;
  }

  public String getnLand() {
    return nLand;
  }

  public void setnLand(String nLand) {
    this.nLand = nLand;
  }

  @Column(name = "N_CITY")
  private String nCity;

  @Column(name = "N_ST")
  private String nSt;

  @Column(name = "N_CNTY")
  private String nCnty;

  @Column(name = "C_ZIP")
  private int cZip;

  @Column(name = "LAND_CNTRY")
  private String nLand;

  @Column(name = "CREATE_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createDate;

  @Column(name = "CREATE_BY")
  private String createBy;

  @Column(name = "LAST_UPDT_BY")
  private String updateBy;

  @Column(name = "LAST_UPDT_TS")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateDate;

  public Date getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  public String getCreateBy() {
    return createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public String getUpdateBy() {
    return updateBy;
  }

  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  public Date getUpdateDate() {
    return updateDate;
  }

  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }

  @Column(name = "C_ST")
  private float cSt;

  @Column(name = "C_CNTY")
  private float cCnty;

  @Column(name = "C_CITY")
  private float cCity;

  public float getcSt() {
    return cSt;
  }

  public void setcSt(float cSt) {
    this.cSt = cSt;
  }

  public float getcCnty() {
    return cCnty;
  }

  public void setcCnty(float cCnty) {
    this.cCnty = cCnty;
  }

  public float getcCity() {
    return cCity;
  }

  public void setcCity(float cCity) {
    this.cCity = cCity;
  }

}