/*
This file was automatically generated by the EntityCreator engine on Wed Apr 28 14:29:09 SGT 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ibm.cio.cmr.request.entity.listeners.GenChangeLogDetails;
import com.ibm.cio.cmr.request.entity.listeners.GenChangeLogListener;

/**
 * The persistent class for the US_Enterprise database table.
 * 
 */
@Entity
@Table(name = "US_COMPANY", schema = "SAPR3")
@EntityListeners(GenChangeLogListener.class)
@GenChangeLogDetails(mandt = "id.mandt", tab_key1 = "id.compNo", tab_key2 = "entNo", pk = "id", tab_nm = "US_COMPANY")

public class USCompany extends BaseEntity<USCompanyPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private USCompanyPK id;

  public USCompanyPK getId() {
    return id;
  }

  public void setId(USCompanyPK id) {
    this.id = id;
  }

  @Column(name = "ENT_NO")
  private String entNo;

  @Column(name = "COMP_LEGAL_NAME")
  private String compLegalName;

  @Column(name = "LOEVM")
  private String loevm;

  @Column(name = "CREATED_BY")
  private String createBy;

  @Column(name = "CREATE_DT")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createDt;

  @Column(name = "UPDATED_BY")
  private String updateBy;

  @Column(name = "UPDATE_DT")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateDt;

  @Column(name = "UPDATE_TYPE")
  private String updateType;

  @Column(name = "KATR10")
  private String katr10;

  public String getEntNo() {
    return entNo;
  }

  public void setEntNo(String entNo) {
    this.entNo = entNo;
  }

  public String getCompLegalName() {
    return compLegalName;
  }

  public void setCompLegalName(String compLegalName) {
    this.compLegalName = compLegalName;
  }

  public String getLoevm() {
    return loevm;
  }

  public void setLoevm(String loevm) {
    this.loevm = loevm;
  }

  public String getCreateBy() {
    return createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getCreateDt() {
    return createDt;
  }

  public void setCreateDt(Date createDt) {
    this.createDt = createDt;
  }

  public String getUpdateBy() {
    return updateBy;
  }

  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  public Date getUpdateDt() {
    return updateDt;
  }

  public void setUpdateDt(Date updateDt) {
    this.updateDt = updateDt;
  }

  public String getUpdateType() {
    return updateType;
  }

  public void setUpdateType(String updateType) {
    this.updateType = updateType;
  }

  public String getKatr10() {
    return katr10;
  }

  public void setKatr10(String katr10) {
    this.katr10 = katr10;
  }

  public static long getSerialversionuid() {
    return serialVersionUID;
  }

}