/*
This file was automatically generated by the EntityCreator engine on Tue Sep 06 17:00:40 CST 2016.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the USERS database table.
 * 
 * @author Jeffrey Zamora
 */
@Embeddable
public class UsersPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "USER_ID")
  private String userId;

  public String getUserId() {
    return this.userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof UsersPK)) {
      return false;
    }
    UsersPK o = (UsersPK) other;
    return this.userId.equals(o.userId);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.userId != null ? this.userId.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.userId);

  }
}