/*
This file was automatically generated by the EntityCreator engine on Fri Oct 27 12:54:02 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the USER_PREF database table.
 * 
 * @author Jeffrey Zamora
 */
@Embeddable
public class UserPrefPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "REQUESTER_ID")
  private String requesterId;

  public String getRequesterId() {
    return this.requesterId;
  }

  public void setRequesterId(String requesterId) {
    this.requesterId = requesterId;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof UserPrefPK)) {
      return false;
    }
    UserPrefPK o = (UserPrefPK) other;
    return this.requesterId.equals(o.requesterId);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.requesterId != null ? this.requesterId.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return !StringUtils.isEmpty(this.requesterId);

  }
}