/*
This file was automatically generated by the EntityCreator engine on Fri Oct 27 12:54:02 CST 2017.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * The persistent class for the USER_PREF database table.
 * 
 * @author Jeffrey Zamora
 */
@Entity
@Table(name = "USER_PREF", schema = "CREQCMR")
public class UserPref extends BaseEntity<UserPrefPK> implements Serializable {
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private UserPrefPK id;

  @Override
  public UserPrefPK getId() {
    return id;
  }

  @Override
  public void setId(UserPrefPK id) {
    this.id = id;
  }

  @Column(name = "REQUESTER_NM")
  private String requesterNm;

  @Column(name = "DFT_ISSUING_CNTRY")
  private String dftIssuingCntry;

  @Column(name = "DFT_STATE_PROV")
  private String dftStateProv;

  @Column(name = "DFT_COUNTY")
  private String dftCounty;

  @Column(name = "DFT_LANDED_CNTRY")
  private String dftLandedCntry;

  @Column(name = "DFT_REVIEWER_ID")
  private String dftReviewerId;

  @Column(name = "DFT_REVIEWER_NM")
  private String dftReviewerNm;

  @Column(name = "RECEIVE_MAIL_IND")
  private String receiveMailInd;

  @Column(name = "PROC_CENTER_NM")
  private String procCenterNm;

  @Column(name = "DEFAULT_LINE_OF_BUSN")
  private String defaultLineOfBusn;

  @Column(name = "DEFAULT_REQUEST_RSN")
  private String defaultRequestRsn;

  @Column(name = "DEFAULT_REQ_TYPE")
  private String defaultReqType;

  @Column(name = "DEFAULT_NO_OF_RECORDS")
  private int defaultNoOfRecords;

  public String getRequesterNm() {
    return this.requesterNm;
  }

  public void setRequesterNm(String requesterNm) {
    this.requesterNm = requesterNm;
  }

  public String getDftIssuingCntry() {
    return this.dftIssuingCntry;
  }

  public void setDftIssuingCntry(String dftIssuingCntry) {
    this.dftIssuingCntry = dftIssuingCntry;
  }

  public String getDftStateProv() {
    return this.dftStateProv;
  }

  public void setDftStateProv(String dftStateProv) {
    this.dftStateProv = dftStateProv;
  }

  public String getDftCounty() {
    return this.dftCounty;
  }

  public void setDftCounty(String dftCounty) {
    this.dftCounty = dftCounty;
  }

  public String getDftLandedCntry() {
    return this.dftLandedCntry;
  }

  public void setDftLandedCntry(String dftLandedCntry) {
    this.dftLandedCntry = dftLandedCntry;
  }

  public String getDftReviewerId() {
    return this.dftReviewerId;
  }

  public void setDftReviewerId(String dftReviewerId) {
    this.dftReviewerId = dftReviewerId;
  }

  public String getDftReviewerNm() {
    return this.dftReviewerNm;
  }

  public void setDftReviewerNm(String dftReviewerNm) {
    this.dftReviewerNm = dftReviewerNm;
  }

  public String getReceiveMailInd() {
    return this.receiveMailInd;
  }

  public void setReceiveMailInd(String receiveMailInd) {
    this.receiveMailInd = receiveMailInd;
  }

  public String getProcCenterNm() {
    return this.procCenterNm;
  }

  public void setProcCenterNm(String procCenterNm) {
    this.procCenterNm = procCenterNm;
  }

  public String getDefaultLineOfBusn() {
    return this.defaultLineOfBusn;
  }

  public void setDefaultLineOfBusn(String defaultLineOfBusn) {
    this.defaultLineOfBusn = defaultLineOfBusn;
  }

  public String getDefaultRequestRsn() {
    return this.defaultRequestRsn;
  }

  public void setDefaultRequestRsn(String defaultRequestRsn) {
    this.defaultRequestRsn = defaultRequestRsn;
  }

  public String getDefaultReqType() {
    return this.defaultReqType;
  }

  public void setDefaultReqType(String defaultReqType) {
    this.defaultReqType = defaultReqType;
  }

  public int getDefaultNoOfRecords() {
    return this.defaultNoOfRecords;
  }

  public void setDefaultNoOfRecords(int defaultNoOfRecords) {
    this.defaultNoOfRecords = defaultNoOfRecords;
  }

}