/*
This file was automatically generated by the EntityCreator engine on Wed Apr 28 14:29:09 SGT 2021.
*/
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityResult;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * The persistent class for the US_TAX_DATA database table.
 * 
 */
@Entity
@Table(name = "US_TAX_DATA", schema = "USINTERIM")
@SqlResultSetMapping(name = "TaxEntityMapping", entities = { @EntityResult(entityClass = Kna1.class), @EntityResult(entityClass = USTaxData.class) })
public class USTaxData extends BaseEntity<USTaxDataPK> implements Serializable {

  public static final String TAX_ENTITY_MAPPING = "TaxEntityMapping";
  private static final long serialVersionUID = 1L;

  @EmbeddedId
  private USTaxDataPK id;

  @Override
  public USTaxDataPK getId() {
    return id;
  }

  @Override
  public void setId(USTaxDataPK id) {
    this.id = id;
  }

  @Column(name = "EA_STATUS")
  private String eaStatus;

  public String getEaStatus() {
    return eaStatus;
  }

  public void setEaStatus(String eaStatus) {
    this.eaStatus = eaStatus;
  }

  @Column(name = "I_TYPE_CUST_1")
  private String iTypeCust1;

  @Column(name = "I_TYPE_CUST_2")
  private String iTypeCust2;
  @Column(name = "I_TYPE_CUST_3")
  private String iTypeCust3;
  @Column(name = "I_TAX_CLASS_1")
  private String iTaxClass1;
  @Column(name = "I_TAX_CLASS_2")
  private String iTaxClass2;
  @Column(name = "I_TAX_CLASS_3")
  private String iTaxClass3;
  @Column(name = "C_TE_CERT_ST_1")
  private String cTeCertST1;
  @Column(name = "C_TE_CERT_ST_2")
  private String cTeCertST2;
  @Column(name = "C_TE_CERT_ST_3")
  private String cTeCertST3;
  @Column(name = "C_ICC_TE")
  private String cICCTe;
  @Column(name = "C_ICC_TAX_CLASS")
  private String CICCTaxClass;
  @Column(name = "C_SCC")
  private String cScc;
  @Column(name = "F_OCL")
  private String fOCL;

  @Column(name = "LOEVM")
  private String loevm;

  public String getLoevm() {
    return loevm;
  }

  public void setLoevm(String loevm) {
    this.loevm = loevm;
  }

  public String getiTypeCust1() {
    return iTypeCust1;
  }

  public void setiTypeCust1(String iTypeCust1) {
    this.iTypeCust1 = iTypeCust1;
  }

  public String getiTypeCust2() {
    return iTypeCust2;
  }

  public void setiTypeCust2(String iTypeCust2) {
    this.iTypeCust2 = iTypeCust2;
  }

  public String getiTypeCust3() {
    return iTypeCust3;
  }

  public void setiTypeCust3(String iTypeCust3) {
    this.iTypeCust3 = iTypeCust3;
  }

  public String getiTaxClass1() {
    return iTaxClass1;
  }

  public void setiTaxClass1(String iTaxClass1) {
    this.iTaxClass1 = iTaxClass1;
  }

  public String getiTaxClass2() {
    return iTaxClass2;
  }

  public void setiTaxClass2(String iTaxClass2) {
    this.iTaxClass2 = iTaxClass2;
  }

  public String getiTaxClass3() {
    return iTaxClass3;
  }

  public void setiTaxClass3(String iTaxClass3) {
    this.iTaxClass3 = iTaxClass3;
  }

  public String getcTeCertST1() {
    return cTeCertST1;
  }

  public void setcTeCertST1(String cTeCertST1) {
    this.cTeCertST1 = cTeCertST1;
  }

  public String getcTeCertST2() {
    return cTeCertST2;
  }

  public void setcTeCertST2(String cTeCertST2) {
    this.cTeCertST2 = cTeCertST2;
  }

  public String getcTeCertST3() {
    return cTeCertST3;
  }

  public void setcTeCertST3(String cTeCertST3) {
    this.cTeCertST3 = cTeCertST3;
  }

  public String getcICCTe() {
    return cICCTe;
  }

  public void setcICCTe(String cICCTe) {
    this.cICCTe = cICCTe;
  }

  public String getCICCTaxClass() {
    return CICCTaxClass;
  }

  public void setCICCTaxClass(String cICCTaxClass) {
    CICCTaxClass = cICCTaxClass;
  }

  public String getcScc() {
    return cScc;
  }

  public void setcScc(String cScc) {
    this.cScc = cScc;
  }

  public String getfOCL() {
    return fOCL;
  }

  public void setfOCL(String fOCL) {
    this.fOCL = fOCL;
  }

  @Column(name = "CREATED_BY")
  private String createBy;

  @Column(name = "CREATE_DT")
  @Temporal(TemporalType.TIMESTAMP)
  private Date createDt;

  @Column(name = "UPDATED_BY")
  private String updateBy;

  @Column(name = "UPDATE_DT")
  @Temporal(TemporalType.TIMESTAMP)
  private Date updateDt;

  @Column(name = "UPDATE_TYPE")
  private String updateType;

  public String getCreateBy() {
    return createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Date getCreateDt() {
    return createDt;
  }

  public void setCreateDt(Date createDt) {
    this.createDt = createDt;
  }

  public String getUpdateBy() {
    return updateBy;
  }

  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  public Date getUpdateDt() {
    return updateDt;
  }

  public void setUpdateDt(Date updateDt) {
    this.updateDt = updateDt;
  }

  public String getUpdateType() {
    return updateType;
  }

  public void setUpdateType(String updateType) {
    this.updateType = updateType;
  }

}