/*
This file was automatically generated by the EntityCreator engine on Mon Dec 19 14:20:26 SGT 2016.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.StringUtils;

/**
 * The primary key class for the VALIDATION_URLS database table.
 * 
 * @author Eduard Bernardo
 */
@Embeddable
public class ValidationUrlPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "DISPLAY_SEQ_NO")
  private long displaySeqNo;

  @Column(name = "CNTRY_CD")
  private String cntryCd;

  public long getDisplaySeqNo() {
    return this.displaySeqNo;
  }

  public void setDisplaySeqNo(long displaySeqNo) {
    this.displaySeqNo = displaySeqNo;
  }

  public String getCntryCd() {
    return this.cntryCd;
  }

  public void setCntryCd(String cntryCd) {
    this.cntryCd = cntryCd;
  }

  @Override
  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof ValidationUrlPK)) {
      return false;
    }
    ValidationUrlPK o = (ValidationUrlPK) other;
    return this.displaySeqNo == o.displaySeqNo && this.cntryCd.equals(o.cntryCd);

  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.displaySeqNo > 0 ? new java.lang.Long(this.displaySeqNo).hashCode() : 0);
    hash = hash * prime + (this.cntryCd != null ? this.cntryCd.hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.displaySeqNo > 0 && !StringUtils.isEmpty(this.cntryCd);

  }
}