/*
This file was automatically generated by the EntityCreator engine on Wed Aug 12 12:52:21 IST 2015.
 */
package com.ibm.cio.cmr.request.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * The primary key class for the WF_HIST database table.
 * 
 * @author Rama mohan
 */
@Embeddable
public class WfHistPK extends BaseEntityPk implements Serializable {

  // default serial version id, required for serializable classes.
  private static final long serialVersionUID = 1L;

  @Column(name = "WF_ID")
  private long wfId;

  public long getWfId() {
    return this.wfId;
  }

  public void setWfId(long wfId) {
    this.wfId = wfId;
  }

  public boolean equals(Object other) {
    if (this == other) {
      return true;
    }
    if (!(other instanceof WfHistPK)) {
      return false;
    }
    WfHistPK o = (WfHistPK) other;
    return this.wfId == o.wfId;

  }

  public int hashCode() {
    final int prime = 31;
    int hash = 17;
    hash = hash * prime + (this.wfId > 0 ? new java.lang.Long(this.wfId).hashCode() : 0);

    return hash;
  }

  @Override
  protected boolean allKeysAssigned() {
    return this.wfId > 0;
  }
}